Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2021-07, with the labels that each got.

#581 Create Events “hpe-dev-munch-learn-series-july-2021”
  content/event/hpe-dev-munch-learn-series-july-2021.md
  static/img/m-l-data-sharing-1024-twitter-july-2021.jpg
  static/img/m-l-data-sharing-640-banner-july-2021.jpg
Labels: netlify-cms/pending_review

#583 Update Events “hpe-dev-munch-learn-series-june-2021”
  content/event/hpe-dev-munch-learn-series-june-2021.md
Labels: netlify-cms/pending_publish

#585 Update Blog “hpe-dev-launches-its-munch-learn-technical-talks”
  content/blog/hpe-dev-launches-its-munch-learn-technical-talks.md
Labels: netlify-cms/pending_publish

#587 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#588 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#586 Update Platforms “hpe-ezmeral-container-platform/home”
  content/platform/hpe-ezmeral-container-platform/home.md
Labels: netlify-cms/pending_review

#592 Update Platforms “spiffe-and-spire-projects/home”
  content/platform/spiffe-and-spire-projects/home.md
Labels: netlify-cms/pending_publish

#596 Update Platforms “smartsim/home”
  content/platform/smartsim/home.md
Labels: netlify-cms/draft

#599 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/draft

#601 Update Platforms “smartsim/home”
  content/platform/smartsim/home.md
  static/admin/config.yml
  static/img/platforms/smartsim_large.png
  static/img/screen-shot-2021-07-07-at-7.09.23-am.png
Labels: netlify-cms/draft

#589 Update Platforms “hpe-ezmeral-data-fabric/home”
  content/platform/hpe-ezmeral-data-fabric/home.md
Labels: netlify-cms/pending_review

#604 Update Platforms “smartsim/home”
  content/platform/smartsim/home.md
  static/img/smartsim-architecture.png
Labels: netlify-cms/pending_review

#609 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#615 Update Blog “building-dynamic-machine-learning-pipelines-with-kubedirector”
  content/blog/building-dynamic-machine-learning-pipelines-with-kubedirector.md
Labels: netlify-cms/pending_publish

#616 Update Platforms “smartsim/home”
  content/platform/smartsim/home.md
  static/img/platforms/smartsim.svg
Labels: netlify-cms/pending_publish

#619 Update Platforms “hpe-simplivity/home”
  content/platform/hpe-simplivity/home.md
  static/img/platforms/simplivity-logo.svg
Labels: netlify-cms/pending_publish

#621 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#620 Update Events “hpe-dev-munch-learn-series-july-2021”
  content/event/hpe-dev-munch-learn-series-july-2021.md
Labels: netlify-cms/pending_review

#623 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_review

#627 Update Blog “getting-started-with-the-redfish-api-part-2”
  content/blog/getting-started-with-the-redfish-api-part-2.md
Labels: netlify-cms/pending_publish

#629 Update Blog “getting-started-with-ilo-restful-api-redfish-api-conformance”
  content/blog/getting-started-with-ilo-restful-api-redfish-api-conformance.md
Labels: netlify-cms/pending_publish

#637 Update Blog “similar-document-search-using-apache-spark-with-tf-idf”
  content/blog/similar-document-search-using-apache-spark-with-tf-idf.md
Labels: netlify-cms/pending_review

#636 Update Blog “comparing-to-kill-a-mockingbird-to-its-sequel-with-apache-spark”
  content/blog/comparing-to-kill-a-mockingbird-to-its-sequel-with-apache-spark.md
Labels: netlify-cms/pending_review

#635 Update Blog “using-docker-wrong-my-journey-to-a-better-container”
  content/blog/using-docker-wrong-my-journey-to-a-better-container.md
Labels: netlify-cms/pending_review

#638 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#640 Create Events “kubecon-na-2021”
  content/event/kubecon-na-2021.md
  static/img/kubeconna2021-event-card-image.png
Labels: netlify-cms/pending_publish

#642 Create Events “hpe-dev-munch-learn-series-august-2021”
  content/event/hpe-dev-munch-learn-series-august-2021.md
  static/img/nigel-twitter-1024.jpg
Labels: netlify-cms/pending_publish

#641 Update Events “hpe-dev-munch-learn-series-july-2021”
  content/event/hpe-dev-munch-learn-series-july-2021.md
Labels: netlify-cms/pending_publish
