Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2021-10, with the labels that each got.

#759 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#760 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/draft

#765 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#766 Create Opensource “determined-ai”
  content/opensource/determined-ai.md
  static/img/logo-final-transparent-.png
  static/img/logo-final-transparent-.svg
Labels: netlify-cms/pending_review

#768 Update Opensource “determined-ai”
  content/opensource/determined-ai.md
  static/img/black-background-transparent-.png
Labels: netlify-cms/pending_publish

#771 Update Opensource “determined-ai”
  content/opensource/determined-ai.md
Labels: netlify-cms/pending_publish

#774 Update Blog “meet-you-in-the-hack-shack”
  content/blog/meet-you-in-the-hack-shack.md
Labels: netlify-cms/pending_publish

#786 Update Blog “hpe-oneview-and-servicenow-integration-with-stackstorm”
  content/blog/hpe-oneview-and-servicenow-integration-with-stackstorm.md
Labels: netlify-cms/pending_review

#767 Create Platforms “determined-ai/home”
  content/platform/determined-ai/home.md
  static/img/platforms/logo-determine-ai-216px.svg
Labels: netlify-cms/pending_publish

#798 Update Opensource “determined-ai”
  content/opensource/determined-ai.md
Labels: netlify-cms/pending_publish

#793 Create Platforms “hpe-ezmeral-runtime/home”
  content/platform/hpe-ezmeral-runtime/home.md
Labels: netlify-cms/pending_publish

#804 Update Opensource “KubeDirector”
  content/opensource/KubeDirector.md
Labels: netlify-cms/pending_review

#805 Update Platforms “hpe-ezmeral-runtime/home”
  content/platform/hpe-ezmeral-runtime/home.md
Labels: netlify-cms/draft
