Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2021-12, with the labels that each got.

#890 Update Blog “oauth2-for-hpe-greenlake-data-services-cloud-console”
  content/blog/oauth2-for-hpe-greenlake-data-services-cloud-console.md
Labels: netlify-cms/pending_publish

#891 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#892 Update Blog “stackstorm-simple-elegant-automation-for-everyone”
  content/blog/stackstorm-simple-elegant-automation-for-everyone.md
Labels: netlify-cms/pending_review

#894 Update Blog “accessing-dtap-in-pods”
  content/blog/accessing-dtap-in-pods.md
Labels: netlify-cms/pending_publish

#895 Update Blog “mapping-kubernetes-services-to-hpe-ezmeral-container-platform-gateway”
  content/blog/mapping-kubernetes-services-to-hpe-ezmeral-container-platform-gateway.md
Labels: netlify-cms/pending_publish

#897 Update Blog “mapping-kubernetes-services-to-hpe-ezmeral-container-platform-gateway”
  content/blog/mapping-kubernetes-services-to-hpe-ezmeral-container-platform-gateway.md
Labels: netlify-cms/pending_review

#898 Update Home Panel “2-be-an-hpe-dev-blogger”
  content/home/2-be-an-hpe-dev-blogger.md
Labels: netlify-cms/pending_publish

#899 Update Blog “accessing-dtap-in-pods”
  content/blog/accessing-dtap-in-pods.md
Labels: netlify-cms/pending_review

#900 Update Blog “how-fine-grained-data-placement-helps-optimize-application-performance”
  content/blog/how-fine-grained-data-placement-helps-optimize-application-performance.md
Labels: netlify-cms/pending_review

#901 Update Blog “mapping-kubernetes-services-to-hpe-ezmeral-container-platform-gateway”
  content/blog/mapping-kubernetes-services-to-hpe-ezmeral-container-platform-gateway.md
Labels: netlify-cms/pending_review

#902 Update Home Panel “2-be-an-hpe-dev-blogger”
  content/home/2-be-an-hpe-dev-blogger.md
Labels: netlify-cms/pending_publish

#903 Update Home Panel “2-be-an-hpe-dev-blogger”
  content/home/2-be-an-hpe-dev-blogger.md
Labels: netlify-cms/pending_review

#904 Update Home Panel “2-be-an-hpe-dev-blogger”
  content/home/2-be-an-hpe-dev-blogger.md
Labels: netlify-cms/pending_review

#905 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#906 Update Blog “using-apache-spark-dataframes-for-processing-of-tabular-data”
  content/blog/using-apache-spark-dataframes-for-processing-of-tabular-data.md
Labels: netlify-cms/pending_publish

#907 Update Blog “getting-started-with-spark-on-mapr-sandbox”
  content/blog/getting-started-with-spark-on-mapr-sandbox.md
Labels: netlify-cms/pending_publish

#912 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#913 Update Blog “getting-started-with-the-hpe-data-services-cloud-console-public-rest-api”
  content/blog/getting-started-with-the-hpe-data-services-cloud-console-public-rest-api.md
Labels: netlify-cms/pending_publish

#914 Update Blog “getting-started-with-the-hpe-data-services-cloud-console-public-rest-api”
  content/blog/getting-started-with-the-hpe-data-services-cloud-console-public-rest-api.md
Labels: netlify-cms/draft

#915 Update Platforms “data-services-cloud-console/home”
  content/platform/data-services-cloud-console/home.md
Labels: netlify-cms/draft

#883 Update Opensource “MapR_Technologies”
  content/opensource/MapR_Technologies.md
Labels: netlify-cms/pending_publish

#916 Create Events “hpe-dev-munch-learn-series-january-2022”
  content/event/hpe-dev-munch-learn-series-january-2022.md
Labels: netlify-cms/pending_publish
