Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2021-02, with the labels that each got.

#139 Update Platform “aruba/home”
  content/platform/aruba/home.md
Labels: netlify-cms/pending_publish

#140 Update Platform “aruba/home”
  content/platform/aruba/home.md
Labels: netlify-cms/pending_publish

#147 Update Platform “hpe-ezmeral-data-fabric/home”
  content/platform/hpe-ezmeral-data-fabric/home.md
Labels: netlify-cms/pending_review

#171 Update Platform “hpe-oneview/home”
  content/platform/hpe-oneview/home.md
Labels: netlify-cms/pending_publish

#169 Update Platform “spiffe-and-spire-projects/home”
  content/platform/spiffe-and-spire-projects/home.md
Labels: netlify-cms/pending_publish

#168 Update Platform “hpe-nimble-sotrage/home”
  content/platform/hpe-nimble-sotrage/home.md
Labels: netlify-cms/pending_publish

#167 Update Platform “hpe-ezmeral-data-fabric/home”
  content/platform/hpe-ezmeral-data-fabric/home.md
Labels: netlify-cms/pending_publish

#166 Update Platform “hpe-oneview-global-dashboard/home”
  content/platform/hpe-oneview-global-dashboard/home.md
Labels: netlify-cms/pending_publish

#165 Update Platform “hpe-greenlake/home”
  content/platform/hpe-greenlake/home.md
Labels: netlify-cms/pending_publish

#162 Update Platform “ilo-restful-api/home”
  content/platform/ilo-restful-api/home.md
Labels: netlify-cms/pending_publish

#159 Update Platform “hpe-ezmeral-container-platform/home”
  content/platform/hpe-ezmeral-container-platform/home.md
Labels: netlify-cms/pending_publish

#158 Update Platform “hpe-deep-learning-cookbook/home”
  content/platform/hpe-deep-learning-cookbook/home.md
Labels: netlify-cms/pending_publish

#157 Update Platform “hpe-3par-and-primera/home”
  content/platform/hpe-3par-and-primera/github.png
  content/platform/hpe-3par-and-primera/home.md
Labels: netlify-cms/pending_publish

#153 Update Platform “aruba/home”
  content/platform/aruba/home.md
Labels: netlify-cms/pending_publish

#119 Update Platform “grommet/home”
  content/platform/aruba/grommet.svg
  content/platform/aruba/home.md
  content/platform/grommet/home.md
Labels: netlify-cms/pending_publish

#184 Update Platform “spiffe-and-spire-projects/home”
  content/platform/spiffe-and-spire-projects/home.md
Labels: netlify-cms/pending_publish

#183 Update Platform “hpe-nimble-sotrage/home”
  content/platform/hpe-nimble-sotrage/home.md
Labels: netlify-cms/pending_publish

#182 Update Platform “hpe-greenlake/home”
  content/platform/hpe-greenlake/home.md
Labels: netlify-cms/pending_publish

#181 Update Platform “hpe-ezmeral-data-fabric/home”
  content/platform/hpe-ezmeral-data-fabric/home.md
Labels: netlify-cms/pending_publish

#180 Update Platform “grommet/home”
  content/platform/grommet/home.md
Labels: netlify-cms/pending_publish

#179 Update Platform “aruba/home”
  content/platform/aruba/home.md
Labels: netlify-cms/pending_publish

#187 Update Platform “aruba/home”
  content/platform/aruba/home.md
Labels: netlify-cms/pending_publish

#197 Update Platform “aruba/home”
  content/platform/aruba/home.md
Labels: netlify-cms/pending_publish

#196 Update Platform “grommet/home”
  content/platform/grommet/home.md
Labels: netlify-cms/pending_publish

#204 Update Platform “hpe-simplivity/home”
  content/platform/hpe-simplivity/home.md
Labels: netlify-cms/pending_publish

#208 Update Event “technology-and-solutions-summit-2020-paris”
  content/event/technology-and-solutions-summit-2020-paris.md
Labels: netlify-cms/pending_publish

#205 Update Event “hpedev-much-learn-1”
  content/event/hpedev-much-learn-1.md
Labels: netlify-cms/pending_publish

#207 Update Event “kube-con-na-2020”
  content/event/kube-con-na-2020.md
Labels: netlify-cms/pending_publish

#232 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#194 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#240 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish
