Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2021-11, with the labels that each got.

#830 Update Platforms “determined-ai/home”
  content/platform/determined-ai/home.md
Labels: netlify-cms/pending_publish

#818 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#832 Create Blog “build-transformative-ai-applications-at-scale-with-hpe-cray-ai-development-environment”
  content/blog/build-transformative-ai-applications-at-scale-with-hpe-cray-ai-development-environment.md
Labels: netlify-cms/pending_publish

#834 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#835 Update Blog “build-transformative-ai-applications-at-scale-with-hpe-cray-ai-development-environment”
  content/blog/build-transformative-ai-applications-at-scale-with-hpe-cray-ai-development-environment.md
Labels: netlify-cms/pending_publish

#840 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#842 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/draft

#844 Create Events “hpe-dev-munch-learn-series-november-2021”
  content/event/hpe-dev-munch-learn-series-november-2021.md
Labels: netlify-cms/pending_publish

#845 Create Events “lunch-and-learn-model-porting-with-determined”
  content/event/lunch-and-learn-model-porting-with-determined.md
Labels: netlify-cms/pending_publish

#846 Update Platforms “hpe-ezmeral-runtime/home”
  content/platform/hpe-ezmeral-runtime/home.md
Labels: netlify-cms/pending_publish

#847 Update Home Panel “06-featured-platform-2”
  content/home/06-featured-platform-2.md
Labels: netlify-cms/pending_review

#848 Update Blog “analyzing-the-success-of-the-hpe-dev-workshops-on-demand”
  content/blog/analyzing-the-success-of-the-hpe-dev-workshops-on-demand.md
Labels: netlify-cms/pending_review

#849 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/draft

#850 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_review

#851 Update Blog “analyzing-the-success-of-the-hpe-dev-workshops-on-demand”
  content/blog/analyzing-the-success-of-the-hpe-dev-workshops-on-demand.md
Labels: netlify-cms/pending_publish

#853 Create Events “hpe-data-world-2021”
  content/event/hpe-data-world-2021.md
  static/img/hpe-data-world-2021.png
Labels: netlify-cms/pending_review

#854 Create Events “hpe-dev-munch-learn-series-december-2021”
  content/event/hpe-dev-munch-learn-series-december-2021.md
Labels: netlify-cms/pending_publish

#857 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#859 Update Blog “data-analytic-with-pyspark-using-hpe-ezmeral-container-platform”
  content/blog/data-analytic-with-pyspark-using-hpe-ezmeral-container-platform.md
Labels: netlify-cms/pending_review

#860 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#861 Update Blog “data-analytic-with-pyspark-using-hpe-ezmeral-container-platform”
  content/blog/data-analytic-with-pyspark-using-hpe-ezmeral-container-platform.md
Labels: netlify-cms/pending_review

#863 Update Blog “data-analytic-with-pyspark-using-hpe-ezmeral-container-platform”
  content/blog/data-analytic-with-pyspark-using-hpe-ezmeral-container-platform.md
Labels: netlify-cms/pending_publish

#864 Update Blog “secure-containerized-and-traditional-apps-concurrently”
  content/blog/secure-containerized-and-traditional-apps-concurrently.md
Labels: netlify-cms/pending_publish

#865 Update Blog “accessing-dtap-in-pods”
  content/blog/accessing-dtap-in-pods.md
Labels: netlify-cms/pending_publish

#866 Update Blog “on-premise-adventures-how-to-build-an-apache-spark-lab-on-kubernetes”
  content/blog/on-premise-adventures-how-to-build-an-apache-spark-lab-on-kubernetes.md
Labels: netlify-cms/pending_publish

#867 Update Blog “ways-to-interact-with-kubernetes-clusters-managed-by-hpe-ezmeral-container-platform”
  content/blog/ways-to-interact-with-kubernetes-clusters-managed-by-hpe-ezmeral-container-platform.md
Labels: netlify-cms/pending_publish

#868 Update Blog “application-modernization-with-the-application-workbench”
  content/blog/application-modernization-with-the-application-workbench.md
Labels: netlify-cms/pending_publish

#869 Update Blog “boost-your-analytics-factory-into-hyperdrive”
  content/blog/boost-your-analytics-factory-into-hyperdrive.md
Labels: netlify-cms/pending_publish

#870 Update Blog “the-challenges-of-sharing-gpus-and-how-to-solve-them”
  content/blog/the-challenges-of-sharing-gpus-and-how-to-solve-them.md
Labels: netlify-cms/pending_publish

#871 Update Blog “exploring-data-fabric-and-containers-in-hpe-devs-new-munch-learn-monthly”
  content/blog/exploring-data-fabric-and-containers-in-hpe-devs-new-munch-learn-monthly.md
Labels: netlify-cms/pending_publish

#872 Update Blog “making-ai-a-reality”
  content/blog/making-ai-a-reality.md
Labels: netlify-cms/pending_publish

#873 Update Blog “building-dynamic-machine-learning-pipelines-with-kubedirector”
  content/blog/building-dynamic-machine-learning-pipelines-with-kubedirector.md
Labels: netlify-cms/pending_publish

#874 Update Blog “hpe-achieves-gold-for-large-scale-enterprise-kubernetes-deployments”
  content/blog/hpe-achieves-gold-for-large-scale-enterprise-kubernetes-deployments.md
Labels: netlify-cms/pending_publish

#876 Update Blog “hpe-container-platform-rest-api-part-1-authenticating”
  content/blog/hpe-container-platform-rest-api-part-1-authenticating.md
Labels: netlify-cms/pending_publish

#875 Update Blog “hpe-container-platform-rest-api-part-2-deploying-containerized-applicati”
  content/blog/hpe-container-platform-rest-api-part-2-deploying-containerized-applicati.md
Labels: netlify-cms/pending_publish

#877 Update Blog “app-dev-and-the-hpe-container-platform”
  content/blog/app-dev-and-the-hpe-container-platform.md
Labels: netlify-cms/pending_publish

#878 Update Blog “think-container-first”
  content/blog/think-container-first.md
Labels: netlify-cms/pending_publish

#879 Update Blog “running-non-cloud-native-apps-on-kubernetes-with-kubedirector”
  content/blog/running-non-cloud-native-apps-on-kubernetes-with-kubedirector.md
Labels: netlify-cms/pending_publish

#880 Create Blog “autopilot-kubernetes-deployments-on-hpe-ezmeral-runtime-enterprise”
  content/blog/autopilot-kubernetes-deployments-on-hpe-ezmeral-runtime-enterprise.md
  static/img/fig1-k8s-complex-gopaddle.png
  static/img/fig10-hpe-volumes-gopaddle.png
  static/img/fig2-hpe-gopaddle-solution.png
  static/img/fig3-hpe-cluster-dashboard-gopaddle.png
  static/img/fig4-hpe-addons-builds-apps-gopaddle.png
  static/img/fig5-hpe-node-detail-gopaddle.png
  static/img/fig6-hpe-node-logs-gopaddle.png
  static/img/fig7-hpe-code-rep-reg-updated-gopaddle.png
  static/img/fig8-hpe-gpctl-init-1-gopaddle.png
  static/img/fig9-enable-ci-gopaddle.png
  static/img/vinothini-192x192.jpg
Labels: netlify-cms/pending_publish

#886 Update Blog “api-console-for-data-services-cloud-console”
  content/blog/api-console-for-data-services-cloud-console.md
Labels: netlify-cms/pending_publish

#887 Update Blog “oauth2-for-hpe-greenlake-data-services-cloud-console”
  content/blog/oauth2-for-hpe-greenlake-data-services-cloud-console.md
Labels: netlify-cms/pending_publish

#888 Update Blog “oauth2-for-hpe-greenlake-data-services-cloud-console”
  content/blog/oauth2-for-hpe-greenlake-data-services-cloud-console.md
Labels: netlify-cms/pending_publish
