Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2021-04, with the labels that each got.

#356 Update Platforms “hpe-oneview/home”
  content/platform/hpe-oneview/home.md
Labels: netlify-cms/pending_publish

#358 Update Platforms “hpe-oneview/home”
  content/platform/hpe-oneview/home.md
Labels: netlify-cms/pending_publish

#362 Create Blog “2021-04-06-managing-multiple-instances-of-python-in-microsoft-windows”
  content/blog/2021-04-06-managing-multiple-instances-of-python-in-microsoft-windows.md
Labels: netlify-cms/pending_publish

#363 Update Blog “2021-04-06-managing-multiple-instances-of-python-in-microsoft-windows”
  content/blog/2021-04-06-managing-multiple-instances-of-python-in-microsoft-windows.md
Labels: netlify-cms/pending_publish

#367 Create Blog “2021-04-12-from-jupyter-notebooks-as-a-service-to-hpe-dev-workshops-on-demand”
  content/blog/2021-04-12-from-jupyter-notebooks-as-a-service-to-hpe-dev-workshops-on-demand.md
Labels: netlify-cms/pending_publish

#364 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#366 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#298 Update Platforms “hpe-simplivity/home”
  content/platform/hpe-simplivity/adding-certificates.md
  content/platform/hpe-simplivity/architecture-and-object-model.md
  content/platform/hpe-simplivity/authenticating-against-hpe-omnistack-api.md
  content/platform/hpe-simplivity/authorization-related-rest-api-log-messages-and-responses.md
  content/platform/hpe-simplivity/enumerations.md
  content/platform/hpe-simplivity/errors-and-exceptions.md
  content/platform/hpe-simplivity/feature-and-function-support-by-rest-api-version.md
  content/platform/hpe-simplivity/get-backups.md
  content/platform/hpe-simplivity/getting-a-certificate.md
  content/platform/hpe-simplivity/getting-a-root-certificate.md
  content/platform/hpe-simplivity/home.md
  content/platform/hpe-simplivity/hpesvtcli-powershell-commands.md
  content/platform/hpe-simplivity/http-error-code-reference.md
  content/platform/hpe-simplivity/interactive-rest-api-reference.md
  content/platform/hpe-simplivity/java.md
  content/platform/hpe-simplivity/metrics.md
  content/platform/hpe-simplivity/optimize-get-requests.md
  content/platform/hpe-simplivity/powershell.md
  content/platform/hpe-simplivity/ps-getoathtoken.md
  content/platform/hpe-simplivity/python.md
  content/platform/hpe-simplivity/remove-certificate.md
  content/platform/hpe-simplivity/request-authentication-by-emergency-grant.md
  content/platform/hpe-simplivity/restore-virtual-machines.md
  content/platform/hpe-simplivity/revoke-oath-2-token.md
  content/platform/hpe-simplivity/sample-code.md
  content/platform/hpe-simplivity/simplivity.jpg
  content/platform/hpe-simplivity/tls-certificate-validation.md
  content/platform/hpe-simplivity/versioning.md
  content/platform/hpe-simplivity/whats-new.md
  static/img/simplivity.jpg
Labels: netlify-cms/pending_review

#383 Create Blog “2021-04-15-kubecon-cloudnativecon-europe-be-involved-via-this-virtual-opportunity”
  content/blog/2021-04-15-kubecon-cloudnativecon-europe-be-involved-via-this-virtual-opportunity.md
  static/img/kubecon-eu-2021-1.jpg
  static/img/small-162.jpg
Labels: netlify-cms/pending_publish

#380 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#386 Update Blog “2021-04-15-kubecon-cloudnativecon-europe-be-involved-via-this-virtual-opportunity”
  content/blog/2021-04-15-kubecon-cloudnativecon-europe-be-involved-via-this-virtual-opportunity.md
  static/img/blog-author-rensing-96.jpg
Labels: netlify-cms/pending_publish

#376 Create Blog “2021-04-13-how-to-integrate-chef-automation-with-hpe-greenlake-for-private-cloud”
  content/blog/2021-04-13-how-to-integrate-chef-automation-with-hpe-greenlake-for-private-cloud.md
  static/img/gettyimages-521980823_16x9_1600_0_72_rgb.jpg
  static/img/gettyimages-521980823_4x3_1600_0_72_rgb.jpg
  static/img/glpc-chef-integration-image1.png
  static/img/glpc-chef-integration-image10.png
  static/img/glpc-chef-integration-image11.png
  static/img/glpc-chef-integration-image12.png
  static/img/glpc-chef-integration-image13.png
  static/img/glpc-chef-integration-image14.png
  static/img/glpc-chef-integration-image15.png
  static/img/glpc-chef-integration-image16.png
  static/img/glpc-chef-integration-image17.png
  static/img/glpc-chef-integration-image2.png
  static/img/glpc-chef-integration-image3-bis.png
  static/img/glpc-chef-integration-image3.png
  static/img/glpc-chef-integration-image4.png
  static/img/glpc-chef-integration-image5.png
  static/img/glpc-chef-integration-image6.png
  static/img/glpc-chef-integration-image7.png
  static/img/glpc-chef-integration-image8.png
  static/img/glpc-chef-integration-image9.png
Labels: netlify-cms/pending_publish

#388 Update Platforms “hpe-greenlake/home”
  content/platform/hpe-greenlake/home.md
Labels: netlify-cms/pending_publish

#389 Update Campaign “links”
  content/campaign/links.md
Labels: netlify-cms/pending_publish

#391 Update Blog “hpe-container-platform-rest-api-part-1-authenticating”
  content/blog/hpe-container-platform-rest-api-part-1-authenticating.md
Labels: netlify-cms/pending_publish

#392 Update Blog “hpe-container-platform-rest-api-part-2-deploying-containerized-applicati”
  content/blog/hpe-container-platform-rest-api-part-2-deploying-containerized-applicati.md
Labels: netlify-cms/pending_publish

#394 Update Blog “spire-maintainer-agustn-martnez-fay-reveals-his-passion-for-information-”
  content/blog/spire-maintainer-agustn-martnez-fay-reveals-his-passion-for-information-.md
Labels: netlify-cms/pending_publish

#385 Update Blog “the-challenges-of-sharing-gpus-and-how-to-solve-them”
  content/blog/the-challenges-of-sharing-gpus-and-how-to-solve-them.md
Labels: netlify-cms/pending_publish

#395 Create Blog “2021-04-16-get-involved-in-the-open-source-community-part-1-getting-started-with-git”
  content/blog/2021-04-16-get-involved-in-the-open-source-community-part-1-getting-started-with-git.md
  static/img/github-mark.png
Labels: netlify-cms/pending_publish

#377 Create Blog “2021-04-14-hpe-developer-community-meets-a-changing-world-head-on”
  content/blog/2021-04-14-hpe-developer-community-meets-a-changing-world-head-on.md
  static/img/hpedev-world-is-changing-image1-small.png
  static/img/hpedev-world-is-changing-image1.png
  static/img/hpedev-world-is-changing-image2.png
  static/img/hpedev-world-is-changing-v2-portal-reveal-575-by-375.jpg
  static/img/hpedev-world-is-changing-v2-portal-reveal-982x639.jpg
Labels: netlify-cms/pending_publish

#399 Update Home Panel “02-featured-blog”
  content/home/02-featured-blog.md
Labels: netlify-cms/draft

#407 Create Blog “meet-open-source-grommet-lead-developer-and-architect-shimrit-yacobi”
  content/blog/meet-open-source-grommet-lead-developer-and-architect-shimrit-yacobi.md
  static/img/shimi-yacobi-375.jpg
  static/img/shimi-yacobi-small.jpg
Labels: netlify-cms/pending_publish

#410 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#412 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#419 Update Home Panel “05-featured-platform-1”
  content/home/05-featured-platform-1.md
  static/img/spiffeandspire.svg
Labels: netlify-cms/draft

#420 Update Blog “making-ai-a-reality”
  content/blog/making-ai-a-reality.md
Labels: netlify-cms/draft

#421 Update Blog “hpe-developer-community-meets-a-changing-world-head-on”
  content/blog/hpe-developer-community-meets-a-changing-world-head-on.md
Labels: netlify-cms/draft

#405 Update Blog “the-hack-shack-returns-to-hpe-tss-paris-2020”
  content/blog/the-hack-shack-returns-to-hpe-tss-paris-2020.md
Labels: netlify-cms/pending_publish

#403 Update Blog “jupyter-saved-my-day”
  content/blog/jupyter-saved-my-day.md
Labels: netlify-cms/pending_publish

#402 Update Blog “using-jitsi-meet-to-reach-out-to-others”
  content/blog/using-jitsi-meet-to-reach-out-to-others.md
Labels: netlify-cms/pending_publish

#429 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish
