Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2021-09, with the labels that each got.

#683 Update Events “hpe-dev-munch-learn-series-august-2021”
  content/event/hpe-dev-munch-learn-series-august-2021.md
Labels: netlify-cms/pending_publish

#682 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#685 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#686 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#691 Update Blog “meet-linux-distinguished-technologist-and-open-source-evangelist-bruno-cornec”
  content/blog/meet-linux-distinguished-technologist-and-open-source-evangelist-bruno-cornec.md
Labels: netlify-cms/pending_review

#698 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#701 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#712 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#713 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#717 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#725 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#714 Create Skillup “skillup”
  content/skillup/skillup.md
  static/img/youtube_logo_icon_168737.png
Labels: netlify-cms/pending_publish

#734 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#736 Update Blog “spire-maintainer-agustn-martnez-fay-reveals-his-passion-for-information-”
  content/blog/spire-maintainer-agustn-martnez-fay-reveals-his-passion-for-information-.md
Labels: netlify-cms/pending_publish

#738 Update Blog “hpe-dev-launches-its-munch-learn-technical-talks”
  content/blog/hpe-dev-launches-its-munch-learn-technical-talks.md
Labels: netlify-cms/pending_publish

#731 Create Blog “sir-hackington-rides-again”
  content/blog/sir-hackington-rides-again.md
  static/img/virtual-booth-image.jpg
  static/img/virtual-booth-update-2.jpg
  static/img/virtual-booth-update-3.jpg
  static/img/vmworld_collage-1538516807872-2-.jpg
Labels: netlify-cms/pending_publish

#746 Update What's Your Role “data-scientist/home”
  content/role/data-scientist/home.md
Labels: netlify-cms/draft

#744 Update What's Your Role “it-system/home”
  content/role/it-system/home.md
Labels: netlify-cms/draft

#745 Create What's Your Role “cloud-datacenter-owners/home”
  content/role/cloud-datacenter-owners/home.md
Labels: netlify-cms/draft

#747 Update What's Your Role “developer/home”
  content/role/developer/home.md
Labels: netlify-cms/draft

#748 Update What's Your Role “designer/home”
  content/role/designer/home.md
Labels: netlify-cms/draft

#749 Update What's Your Role “open-source/home”
  content/role/open-source/home.md
Labels: netlify-cms/draft

#750 Update What's Your Role “cloud-datacenter-owners/home”
  content/role/cloud-datacenter-owners/home.md
  static/img/role/cloud-data-center-owner.png
Labels: netlify-cms/draft

#751 Update What's Your Role “developer/home”
  content/role/developer/home.md
Labels: netlify-cms/draft

#752 Update What's Your Role “cloud-datacenter-owners/home”
  content/role/cloud-datacenter-owners/home.md
Labels: netlify-cms/draft

#753 Update What's Your Role “it-system/home”
  content/role/it-system/home.md
Labels: netlify-cms/draft

#743 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#758 Update Blog “sir-hackington-rides-again”
  content/blog/sir-hackington-rides-again.md
  static/img/sirhackington.png
Labels: netlify-cms/draft

#756 Create Blog “secure-containerized-and-traditional-apps-concurrently”
  content/blog/secure-containerized-and-traditional-apps-concurrently.md
  static/img/runecast.png
Labels: netlify-cms/pending_publish
