Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2021-08, with the labels that each got.

#643 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#648 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#650 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#651 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#652 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_review

#653 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#654 Create Blog “be-an-hpe-dev-blogger”
  content/blog/be-an-hpe-dev-blogger.md
  static/img/blogger-aristotle.jpg
  static/img/blogger-two-paths-2.jpg
  static/img/blogger-workflow.jpg
Labels: netlify-cms/pending_review

#655 Update Blog “be-an-hpe-dev-blogger”
  content/blog/be-an-hpe-dev-blogger.md
Labels: netlify-cms/draft

#656 Update Blog “calling-all-developers-make-your-voices-heard”
  content/blog/calling-all-developers-make-your-voices-heard.md
Labels: netlify-cms/draft

#657 Update Blog “be-an-hpe-dev-blogger”
  content/blog/be-an-hpe-dev-blogger.md
  static/img/hpe-dev-logo-large.png
Labels: netlify-cms/pending_publish

#658 Create Home Panel “2-be-an-hpe-dev-blogger”
  content/home/2-be-an-hpe-dev-blogger.md
Labels: netlify-cms/pending_review

#663 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#666 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#668 Update Blog “hpe-dev-launches-its-munch-learn-technical-talks”
  content/blog/hpe-dev-launches-its-munch-learn-technical-talks.md
Labels: netlify-cms/pending_review

#669 Create Events “hpe-webinar-is-there-life-after-hadoop”
  content/event/hpe-webinar-is-there-life-after-hadoop.md
  static/img/brighttalk-logo-large.png
Labels: netlify-cms/pending_review

#670 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#665 Update Platforms “grommet/home”
  content/platform/grommet/home.md
Labels: netlify-cms/pending_publish

#672 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#673 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#674 Create Blog “meet-linux-distinguished-technologist-and-open-source-evangelist-bruno-cornec”
  content/blog/meet-linux-distinguished-technologist-and-open-source-evangelist-bruno-cornec.md
Labels: netlify-cms/pending_publish

#675 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#676 Create Blog “discovering-hpe-dev-one-developer’s-journey”
  content/blog/discovering-hpe-dev-one-developer’s-journey.md
  static/img/jay_profile_pic_3.jpg
Labels: netlify-cms/pending_review

#671 Update Platforms “hpe-ezmeral-data-fabric/home”
  content/platform/hpe-ezmeral-data-fabric/home.md
Labels: netlify-cms/pending_publish
