Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2021-03, with the labels that each got.

#193 Update Platform “hpe-greenlake/home”
  content/platform/hpe-greenlake/home.md
Labels: netlify-cms/pending_publish

#217 Update Platform “hpe-oneview/home”
  content/platform/hpe-oneview/home.md
Labels: netlify-cms/pending_publish

#272 Create Events “hpe-dev-munch-learn-series”
  content/event/hpe-dev-munch-learn-series.md
Labels: netlify-cms/pending_publish

#280 Update Events “hpe-dev-munch-learn-series”
  content/event/hpe-dev-munch-learn-series.md
  static/img/events/munch-and-learn-3.jpg
Labels: netlify-cms/draft

#281 Create Home Panel “7-munch-learn-technology-talks”
  content/home/7-munch-learn-technology-talks.md
Labels: netlify-cms/draft

#282 Update Home Panel “7-munch-learn-technology-talks”
  content/home/7-munch-learn-technology-talks.md
  static/img/home/munch-and-learn-216.svg
Labels: netlify-cms/draft

#285 Update Blog “dark-mode-theming-in-grommet-adding-dark-and-light-theme-modes”
  content/blog/dark-mode-theming-in-grommet-adding-dark-and-light-theme-modes.md
Labels: netlify-cms/draft

#293 Update Events “hpe-dev-munch-learn-series”
  content/event/hpe-dev-munch-learn-series.md
Labels: netlify-cms/draft

#295 Update Events “hpedev-much-learn-2”
  content/event/hpedev-much-learn-2.md
Labels: netlify-cms/draft

#294 Update Events “hpedev-much-learn-1”
  content/event/hpedev-much-learn-1.md
Labels: netlify-cms/draft

#287 Create Blog “2021-03-05-from-pig-to-spark-an-easy-journey-to-spark-for-apache-pig-developers”
  content/blog/2021-03-05-from-pig-to-spark-an-easy-journey-to-spark-for-apache-pig-developers.md
Labels: netlify-cms/pending_publish

#308 Update Blog “hpe-dev-launches-its-munch-learn-technical-talks”
  content/blog/hpe-dev-launches-its-munch-learn-technical-talks.md
Labels: netlify-cms/pending_publish

#307 Update Blog “exploring-data-fabric-and-containers-in-hpe-devs-new-munch-learn-monthly”
  content/blog/exploring-data-fabric-and-containers-in-hpe-devs-new-munch-learn-monthly.md
Labels: netlify-cms/pending_publish

#310 Update Blog “exploring-data-fabric-and-containers-in-hpe-devs-new-munch-learn-monthly”
  content/blog/exploring-data-fabric-and-containers-in-hpe-devs-new-munch-learn-monthly.md
Labels: netlify-cms/pending_publish

#301 Create Blog “2021-03-09-boost-your-analytics-factory-into-hyperdrive”
  content/blog/2021-03-09-boost-your-analytics-factory-into-hyperdrive.md
Labels: netlify-cms/pending_publish

#316 Update Blog “hpe-dev-launches-its-munch-learn-technical-talks”
  content/blog/hpe-dev-launches-its-munch-learn-technical-talks.md
Labels: netlify-cms/pending_publish

#317 Create Blog “2021-03-24-open-source-contributor-explains-how-kubedirector-empowers-data-intensive-apps”
  content/blog/2021-03-24-open-source-contributor-explains-how-kubedirector-empowers-data-intensive-apps.md
Labels: netlify-cms/pending_publish

#318 Update Blog “2021-03-24-open-source-contributor-explains-how-kubedirector-empowers-data-intensive-apps”
  content/blog/2021-03-24-open-source-contributor-explains-how-kubedirector-empowers-data-intensive-apps.md
Labels: netlify-cms/pending_publish

#319 Update Platforms “hpe-ezmeral-container-platform/home”
  content/platform/hpe-ezmeral-container-platform/home.md
Labels: netlify-cms/pending_publish

#322 Update Blog “spire-maintainer-agustn-martnez-fay-reveals-his-passion-for-information-”
  content/blog/spire-maintainer-agustn-martnez-fay-reveals-his-passion-for-information-.md
Labels: netlify-cms/pending_publish

#325 Update Platforms “ilo-restful-api/home”
  content/platform/ilo-restful-api/home.md
Labels: netlify-cms/pending_publish

#326 Create Events “hpe-dev-munch-learn-series-april-2021”
  content/event/hpe-dev-munch-learn-series-april-2021.md
Labels: netlify-cms/pending_publish

#328 Update Events “hpe-dev-munch-learn-series-april-2021”
  content/event/hpe-dev-munch-learn-series-april-2021.md
Labels: netlify-cms/pending_publish

#330 Update Platforms “hpe-greenlake/home”
  content/platform/hpe-greenlake/home.md
Labels: netlify-cms/pending_publish

#334 Update Blog “hpe-dev-launches-its-munch-learn-technical-talks”
  content/blog/hpe-dev-launches-its-munch-learn-technical-talks.md
Labels: netlify-cms/pending_publish

#337 Update Blog “synchronized-volume-snapshots-for-distributed-workloads-on-kubernetes”
  content/blog/synchronized-volume-snapshots-for-distributed-workloads-on-kubernetes.md
Labels: netlify-cms/pending_publish

#336 Create Events “hpe-discover”
  content/event/hpe-discover.md
  static/img/discover-event-logo.png
Labels: netlify-cms/pending_publish

#339 Update Blog “hpe-dev-launches-its-munch-learn-technical-talks”
  content/blog/hpe-dev-launches-its-munch-learn-technical-talks.md
Labels: netlify-cms/pending_publish

#340 Update Blog “introducing-kubernetes-csi-sidecar-containers-from-hpe”
  content/blog/introducing-kubernetes-csi-sidecar-containers-from-hpe.md
Labels: netlify-cms/pending_review

#341 Update Blog “get-started-with-the-hpe-nimble-storage-content-collection-for-ansible”
  content/blog/get-started-with-the-hpe-nimble-storage-content-collection-for-ansible.md
Labels: netlify-cms/pending_publish

#345 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/draft

#347 Create Blog “2021-03-31-kubernetes-tutorial-part-2-of-3-how-to-install-and-deploy-applications-at-scale-on-k8s”
  content/blog/2021-03-31-kubernetes-tutorial-part-2-of-3-how-to-install-and-deploy-applications-at-scale-on-k8s.md
Labels: netlify-cms/pending_publish

#348 Create Blog “2021-03-31-streaming-ml-pipeline-for-sentiment-analysis-using-apache-apis-kafka-spark-and-drill-part-2”
  content/blog/2021-03-31-streaming-ml-pipeline-for-sentiment-analysis-using-apache-apis-kafka-spark-and-drill-part-2.md
Labels: netlify-cms/pending_publish

#350 Update Blog “2021-03-31-streaming-ml-pipeline-for-sentiment-analysis-using-apache-apis-kafka-spark-and-drill-part-2”
  content/blog/2021-03-31-streaming-ml-pipeline-for-sentiment-analysis-using-apache-apis-kafka-spark-and-drill-part-2.md
Labels: netlify-cms/pending_publish

#349 Update Blog “streaming-machine-learning-pipeline-for-sentiment-analysis-using-apache-”
  content/blog/streaming-machine-learning-pipeline-for-sentiment-analysis-using-apache-.md
Labels: netlify-cms/pending_publish

#353 Update Blog “kubernetes-tutorial-how-to-install-and-deploy-applications-at-scale-on-k”
  content/blog/kubernetes-tutorial-how-to-install-and-deploy-applications-at-scale-on-k.md
Labels: netlify-cms/pending_review

#352 Update Blog “2021-03-31-kubernetes-tutorial-part-2-of-3-how-to-install-and-deploy-applications-at-scale-on-k8s”
  content/blog/2021-03-31-kubernetes-tutorial-part-2-of-3-how-to-install-and-deploy-applications-at-scale-on-k8s.md
Labels: netlify-cms/pending_review

#355 Update Blog “streaming-machine-learning-pipeline-for-sentiment-analysis-using-apache-”
  content/blog/streaming-machine-learning-pipeline-for-sentiment-analysis-using-apache-.md
Labels: netlify-cms/pending_publish

#354 Update Blog “2021-03-31-streaming-ml-pipeline-for-sentiment-analysis-using-apache-apis-kafka-spark-and-drill-part-2”
  content/blog/2021-03-31-streaming-ml-pipeline-for-sentiment-analysis-using-apache-apis-kafka-spark-and-drill-part-2.md
Labels: netlify-cms/pending_publish
