Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2021-06, with the labels that each got.

#512 Update Platforms “spiffe-and-spire-projects/home”
  content/platform/spiffe-and-spire-projects/home.md
Labels: netlify-cms/pending_review

#517 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/draft

#518 Update Blog “ways-to-interact-with-kubernetes-clusters-managed-by-hpe-ezmeral-container-platform”
  content/blog/ways-to-interact-with-kubernetes-clusters-managed-by-hpe-ezmeral-container-platform.md
Labels: netlify-cms/pending_publish

#516 Update Home Panel “02-featured-blog”
  content/home/02-featured-blog.md
Labels: netlify-cms/pending_publish

#519 Update Home Panel “02-featured-blog”
  content/home/02-featured-blog.md
Labels: netlify-cms/pending_publish

#520 Update Blog “calling-all-developers-make-your-voices-heard”
  content/blog/calling-all-developers-make-your-voices-heard.md
Labels: netlify-cms/pending_publish

#522 Update Blog “the-challenges-of-sharing-gpus-and-how-to-solve-them”
  content/blog/the-challenges-of-sharing-gpus-and-how-to-solve-them.md
Labels: netlify-cms/pending_publish

#528 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#541 Create Blog “on-premise-adventures-how-to-build-an-apache-spark-lab-on-kubernetes”
  content/blog/on-premise-adventures-how-to-build-an-apache-spark-lab-on-kubernetes.md
  static/img/spark-on-ezmeral-architecture.jpg
  static/img/spark-on-ezmeral-image10.png
  static/img/spark-on-ezmeral-image11.png
  static/img/spark-on-ezmeral-image12.png
  static/img/spark-on-ezmeral-image13.png
  static/img/spark-on-ezmeral-image14.png
  static/img/spark-on-ezmeral-image15.png
  static/img/spark-on-ezmeral-image16.png
  static/img/spark-on-ezmeral-image17.png
  static/img/spark-on-ezmeral-image2.png
  static/img/spark-on-ezmeral-image3.png
  static/img/spark-on-ezmeral-image4.png
  static/img/spark-on-ezmeral-image5.png
  static/img/spark-on-ezmeral-image6.png
  static/img/spark-on-ezmeral-image7.png
  static/img/spark-on-ezmeral-image8.png
  static/img/spark-on-ezmeral-image9.png
Labels: netlify-cms/pending_publish

#554 Update Blog “host-based-volume-encryption-with-hpe-csi-driver-for-kubernetes”
  content/blog/host-based-volume-encryption-with-hpe-csi-driver-for-kubernetes.md
Labels: netlify-cms/pending_publish

#553 Update Blog “multitenancy-for-kubernetes-clusters-using-hpe-alletra-6000-and-nimble-storage”
  content/blog/multitenancy-for-kubernetes-clusters-using-hpe-alletra-6000-and-nimble-storage.md
Labels: netlify-cms/pending_publish

#559 Create Blog “become-a-legend”
  content/blog/become-a-legend.md
  static/img/15_workshops_legend_no_bg-img1.png
  static/img/complete_set_of_option_2-img3.png
  static/img/data_fabric_no_bg-img2.png
Labels: netlify-cms/pending_publish

#560 Update Blog “become-a-legend”
  content/blog/become-a-legend.md
  static/img/hpe-dev-logo.png
Labels: netlify-cms/pending_publish

#561 Update Home Panel “02-featured-blog”
  content/home/02-featured-blog.md
Labels: netlify-cms/pending_publish

#562 Update Blog “hpe-discover-2021-don’t-miss-these-hpe-dev-industry-expert-talks-and-hands-on-workshops”
  content/blog/hpe-discover-2021-don’t-miss-these-hpe-dev-industry-expert-talks-and-hands-on-workshops.md
Labels: netlify-cms/pending_publish

#563 Update Blog “calling-all-developers-make-your-voices-heard”
  content/blog/calling-all-developers-make-your-voices-heard.md
Labels: netlify-cms/pending_publish

#567 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#566 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#578 Update Events “hpe-dev-munch-learn-series-april-2021”
  content/event/hpe-dev-munch-learn-series-april-2021.md
Labels: netlify-cms/pending_publish

#579 Update Events “hpe-dev-munch-learn-series”
  content/event/hpe-dev-munch-learn-series.md
Labels: netlify-cms/pending_publish

#580 Update Events “hpe-dev-munch-learn-series-may-2021”
  content/event/hpe-dev-munch-learn-series-may-2021.md
Labels: netlify-cms/pending_publish

#582 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish
