Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2022-05, with the labels that each got.

#1136 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1137 Update Blog “how-fine-grained-data-placement-helps-optimize-application-performance”
  content/blog/how-fine-grained-data-placement-helps-optimize-application-performance.md
Labels: netlify-cms/pending_review

#1138 Update Blog “file-objects-databases-and-streams-–-oh-my”
  content/blog/file-objects-databases-and-streams-–-oh-my.md
Labels: netlify-cms/pending_review

#1139 Update Blog “kubecon-cloudnativecon-europe-16-20-may-2022”
  content/blog/kubecon-cloudnativecon-europe-16-20-may-2022.md
Labels: netlify-cms/pending_review

#1141 Update Events “kubecon-eu-2022”
  content/event/kubecon-eu-2022.md
Labels: netlify-cms/pending_publish

#1142 Update Blog “file-objects-databases-and-streams-–-oh-my”
  content/blog/file-objects-databases-and-streams-–-oh-my.md
Labels: netlify-cms/pending_publish

#1143 Update Blog “becoming-a-linux-kernel-contributor-following-the-journey-of-souptick-joarder”
  content/blog/becoming-a-linux-kernel-contributor-following-the-journey-of-souptick-joarder.md
Labels: netlify-cms/pending_publish

#1144 Update Blog “be-an-hpe-dev-blogger”
  content/blog/be-an-hpe-dev-blogger.md
Labels: netlify-cms/pending_publish

#1145 Update Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform”
  content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform.md
Labels: netlify-cms/pending_publish

#1146 Update Home Panel “06-featured-platform-2”
  content/home/06-featured-platform-2.md
Labels: netlify-cms/pending_publish

#1140 Create Events “hpe-dev-munch-learn-series-may-2022”
  content/event/hpe-dev-munch-learn-series-may-2022.md
  static/img/event-meetups-newlogo.png
  static/img/event-munch-and-learns-newlogo500x451.png
Labels: netlify-cms/pending_publish

#1148 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#1150 Update Events “hpe-dev-meetups-4”
  content/event/hpe-dev-meetups-4.md
  static/img/event-meetups-newlogo-200x466.png
Labels: netlify-cms/pending_publish

#1147 Create Blog “deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-–-part-2”
  content/blog/deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-–-part-2.md
  static/img/webui-myexp-adaptive-graphs-v2.png
  static/img/webui-myexp-const-graph.png
  static/img/webui-myexp-const-status.png
Labels: netlify-cms/pending_publish

#1126 Create Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2”
  content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2.md
  static/img/terraform-greenlake-part2-blog-picture1-1.png
  static/img/terraform-greenlake-part2-blog-picture1.png
  static/img/terraform-greenlake-part2-blog-picture2-2.png
  static/img/terraform-greenlake-part2-blog-picture2.png
  static/img/terraform-greenlake-part2-blog-picture3.png
  static/img/terraform-greenlake-part2-blog-picture4.png
  static/img/terraform-greenlake-part2-blog-picture5.png
  static/img/terraform-greenlake-part2-blog-picture6.png
Labels: netlify-cms/pending_review

#1154 Update Blog “deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-–-part-2”
  content/blog/deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-–-part-2.md
Labels: netlify-cms/pending_publish

#1152 Update Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform”
  content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform.md
Labels: netlify-cms/draft

#1155 Update Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform”
  content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform.md
Labels: netlify-cms/draft

#1158 Update Events “hpe-dev-meetups-4”
  content/event/hpe-dev-meetups-4.md
  static/img/event-meetups-newlogo-400x400.png
Labels: netlify-cms/pending_publish

#1159 Update Events “hpe-dev-munch-learn-series-may-2022”
  content/event/hpe-dev-munch-learn-series-may-2022.md
  static/img/event-munch-and-learn-newlogo400x400.png
Labels: netlify-cms/pending_publish

#1164 Update Blog “deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-part-1”
  content/blog/deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-part-1.md
Labels: netlify-cms/pending_publish

#1165 Update Platforms “determined-ai/home”
  content/platform/determined-ai/home.md
Labels: netlify-cms/pending_review

#1167 Update Blog “understanding-hpe-greenlake-identity-access-management”
  content/blog/understanding-hpe-greenlake-identity-access-management.md
Labels: netlify-cms/pending_publish

#1170 Update Blog “deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-part-1”
  content/blog/deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-part-1.md
Labels: netlify-cms/pending_review

#1173 Update Blog “deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-part-1”
  content/blog/deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-part-1.md
Labels: netlify-cms/pending_review

#1174 Update Platforms “grommet/home”
  content/platform/grommet/home.md
Labels: netlify-cms/pending_publish

#1176 Update Blog “it’s-all-fun-and-games-at-the-hack-shack”
  content/blog/it’s-all-fun-and-games-at-the-hack-shack.md
Labels: netlify-cms/pending_publish

#1120 Create Events “hpe-discover-2022”
  content/event/hpe-discover-2022.md
  static/img/hpe-discover-2022-event.png
Labels: netlify-cms/pending_publish

#1177 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1180 Update Home Panel “02-file-objects-databases-and-streams-oh-my”
  content/home/02-file-objects-databases-and-streams-oh-my.md
Labels: netlify-cms/draft

#1181 Update Blog “kubecon-cloudnativecon-europe-16-20-may-2022”
  content/blog/kubecon-cloudnativecon-europe-16-20-may-2022.md
Labels: netlify-cms/pending_publish

#1182 Update Blog “it’s-all-fun-and-games-at-the-hack-shack”
  content/blog/it’s-all-fun-and-games-at-the-hack-shack.md
Labels: netlify-cms/pending_publish

#1189 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1190 Create Events “opensearch-–-the-open-source-search-and-analytics-suite-you-can-run-yourself”
  content/event/opensearch-–-the-open-source-search-and-analytics-suite-you-can-run-yourself.md
Labels: netlify-cms/draft
