Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2022-02, with the labels that each got.

#967 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#973 Create Blog “writing-deep-learning-tools-for-all-data-scientists-not-just-unicorns”
  content/blog/writing-deep-learning-tools-for-all-data-scientists-not-just-unicorns.md
  static/img/updated-unicorns-picture-smaller.png
  static/img/updated-unicorns-picture.png
Labels: netlify-cms/pending_publish

#986 Update Blog “writing-deep-learning-tools-for-all-data-scientists-not-just-unicorns”
  content/blog/writing-deep-learning-tools-for-all-data-scientists-not-just-unicorns.md
Labels: netlify-cms/pending_review

#989 Update Blog “hpe-greenlake-for-private-cloud”
  content/blog/hpe-greenlake-for-private-cloud.md
Labels: netlify-cms/pending_publish

#988 Create Events “engage-with-the-hpe-dev-team-at-hpe-technology-and-solution-summit-2022”
  content/event/engage-with-the-hpe-dev-team-at-hpe-technology-and-solution-summit-2022.md
  static/img/tss-fred-blog-1.png
Labels: netlify-cms/pending_publish

#991 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#992 Update Events “hpe-dev-munch-learn-series-february-2022”
  content/event/hpe-dev-munch-learn-series-february-2022.md
Labels: netlify-cms/draft

#993 Create Events “hpe-dev-munch-learn-series-march-2022”
  content/event/hpe-dev-munch-learn-series-march-2022.md
Labels: netlify-cms/pending_review

#999 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#1000 Update Blog “writing-deep-learning-tools-for-all-data-scientists-not-just-unicorns”
  content/blog/writing-deep-learning-tools-for-all-data-scientists-not-just-unicorns.md
Labels: netlify-cms/pending_publish

#1001 Update Events “hpe-dev-meetups-1”
  content/event/hpe-dev-meetups-1.md
Labels: netlify-cms/pending_review

#1003 Update Events “hpe-dev-meetups-2”
  content/event/hpe-dev-meetups-2.md
Labels: netlify-cms/pending_review

#1002 Update Events “hpe-dev-munch-learn-series-march-2022”
  content/event/hpe-dev-munch-learn-series-march-2022.md
Labels: netlify-cms/pending_review

#1004 Create Blog “come-and-engage-with-the-hpe-dev-team-at-hpe-technology-and-solution-summit-2022”
  content/blog/come-and-engage-with-the-hpe-dev-team-at-hpe-technology-and-solution-summit-2022.md
  static/img/tss-fred-blog-1.png
  static/img/tss-fred-blog-2.png
  static/img/tss-fred-blog-3.png
Labels: netlify-cms/pending_review

#1005 Update Events “engage-with-the-hpe-dev-team-at-hpe-technology-and-solution-summit-2022”
  content/event/engage-with-the-hpe-dev-team-at-hpe-technology-and-solution-summit-2022.md
Labels: netlify-cms/pending_publish

#1012 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_publish

#1013 Update Events “hpe-dev-meetups-1”
  content/event/hpe-dev-meetups-1.md
Labels: netlify-cms/pending_publish

#1014 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_publish
