Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2022-12, with the labels that each got.

#1555 Update Hackshack Home Cards “hackshackhome-2”
  content/hackshackhome/hackshackhome-2.md
Labels: netlify-cms/draft

#1556 Update Events “introduction-to-kubeflow”
  content/event/introduction-to-kubeflow.md
Labels: netlify-cms/draft

#1544 Create Hackshack Home Cards “hackshackhome-4”
  content/hackshackhome/hackshackhome-4.md
Labels: netlify-cms/pending_review

#1554 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1549 Create Blog “explore-the-hpe-greenlake-for-compute-ops-management-rest-api-using-curl-and-postman”
  content/blog/explore-the-hpe-greenlake-for-compute-ops-management-rest-api-using-curl-and-postman.md
  static/img/greenlake-com-ops-api-curl1.png
  static/img/greenlake-com-ops-api-curl10.png
  static/img/greenlake-com-ops-api-curl12.png
  static/img/greenlake-com-ops-api-curl15.png
  static/img/greenlake-com-ops-api-curl16.png
  static/img/greenlake-com-ops-api-curl17.png
  static/img/greenlake-com-ops-api-curl18.png
  static/img/greenlake-com-ops-api-curl19.png
  static/img/greenlake-com-ops-api-curl2.png
  static/img/greenlake-com-ops-api-curl20.png
  static/img/greenlake-com-ops-api-curl21.png
  static/img/greenlake-com-ops-api-curl22.png
  static/img/greenlake-com-ops-api-curl23.png
  static/img/greenlake-com-ops-api-curl24.png
  static/img/greenlake-com-ops-api-curl25.png
  static/img/greenlake-com-ops-api-curl26.png
  static/img/greenlake-com-ops-api-curl4.png
  static/img/greenlake-com-ops-api-curl5.png
  static/img/greenlake-com-ops-api-curl7.png
  static/img/greenlake-com-ops-api-curl8.png
  static/img/greenlake-com-ops-api-curl9.png
  static/img/lj-vb-fp.png
  static/img/lj-vb-fp192.png
  static/img/vb-fp.png
  static/img/vb-fp192.png
Labels: netlify-cms/pending_review

#1498 Update Campaign “ezmeral-early-access-program”
  content/campaign/ezmeral-early-access-program.md
Labels: netlify-cms/pending_publish

#1474 Update Skillup “skillup-2”
  content/skillup/skillup-2.md
Labels: netlify-cms/pending_publish

#1496 Update Blog “call-for-hpe-ezmeral-unified-analytics-beta-testers”
  content/blog/call-for-hpe-ezmeral-unified-analytics-beta-testers.md
Labels: netlify-cms/pending_publish

#1503 Create Events “hpe-greenlake-for-data-fabric”
  content/event/hpe-greenlake-for-data-fabric.md
Labels: netlify-cms/pending_publish

#1502 Create Events “hpe-ezmeral-unified-analytics”
  content/event/hpe-ezmeral-unified-analytics.md
Labels: netlify-cms/pending_publish

#1403 Create Platforms “hpe-greenlake-for-data-fabric/home”
  content/platform/hpe-greenlake-for-data-fabric/home.md
Labels: netlify-cms/pending_publish

#1561 Update Platforms “project-data-map/home”
  content/platform/project-data-map/home.md
Labels: netlify-cms/pending_review

#1562 Update Platforms “hpe-greenlake-for-compute-ops-management/home”
  content/platform/hpe-greenlake-for-compute-ops-management/home.md
Labels: netlify-cms/pending_review

#1563 Update Platforms “data-services-cloud-console/home”
  content/platform/data-services-cloud-console/home.md
Labels: netlify-cms/pending_review

#1564 Update Platforms “hpe-greenlake-for-data-fabric/home”
  content/platform/hpe-greenlake-for-data-fabric/home.md
Labels: netlify-cms/draft

#1566 Update Blog “hpe-ezmeral-early-access-gives-developers-hands-on-experience-with-the-new-hpe-greenlake-for-data-fabric”
  content/blog/hpe-ezmeral-early-access-gives-developers-hands-on-experience-with-the-new-hpe-greenlake-for-data-fabric.md
Labels: netlify-cms/pending_review

#1565 Update Blog “call-for-hpe-ezmeral-unified-analytics-beta-testers”
  content/blog/call-for-hpe-ezmeral-unified-analytics-beta-testers.md
Labels: netlify-cms/pending_review

#1568 Update Blog “deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-–-part-2”
  content/blog/deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-–-part-2.md
Labels: netlify-cms/pending_review

#1567 Update Blog “spiffe-spire-graduates-enabling-greater-security-solutions”
  content/blog/spiffe-spire-graduates-enabling-greater-security-solutions.md
Labels: netlify-cms/pending_review

#1569 Update Blog “how-to-monitor-hpe-compute-ops-management”
  content/blog/how-to-monitor-hpe-compute-ops-management.md
Labels: netlify-cms/pending_review

#1570 Update Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2”
  content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2.md
Labels: netlify-cms/pending_review

#1572 Update Events “hpe-ezmeral-unified-analytics”
  content/event/hpe-ezmeral-unified-analytics.md
  static/img/event-hpe-ezmeral-early-access-webinar-224.png
Labels: netlify-cms/pending_review

#1573 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#1574 Update Skillup “EzmeralLearnOnDemand”
  content/skillup/EzmeralLearnOnDemand.md
Labels: netlify-cms/pending_review

#1576 Update Events “hpe-greenlake-for-data-fabric”
  content/event/hpe-greenlake-for-data-fabric.md
Labels: netlify-cms/pending_review

#1578 Update Hackshack Home Cards “hackshackhome-3”
  content/hackshackhome/hackshackhome-3.md
Labels: netlify-cms/draft

#1575 Update Home Panel “2-spiffe-spire-graduates-enabling-greater-security-solutions”
  content/home/2-spiffe-spire-graduates-enabling-greater-security-solutions.md
Labels: netlify-cms/pending_review

#1577 Update Events “running-reliable-systems-part-1-an-overview-of-sre”
  content/event/running-reliable-systems-part-1-an-overview-of-sre.md
Labels: netlify-cms/draft

#1579 Update Events “hpe-ezmeral-unified-analytics”
  content/event/hpe-ezmeral-unified-analytics.md
  static/img/event-hpe-ezmeral-early-access-webinar-400x400.png
Labels: netlify-cms/draft

#1580 Update Events “hpe-greenlake-for-data-fabric”
  content/event/hpe-greenlake-for-data-fabric.md
Labels: netlify-cms/pending_review

#1581 Update Home Panel “2-spiffe-spire-graduates-enabling-greater-security-solutions”
  content/home/2-spiffe-spire-graduates-enabling-greater-security-solutions.md
  static/img/alaric_0.1-192x263.jpg
Labels: netlify-cms/pending_review

#1582 Update Events “hpe-ezmeral-unified-analytics”
  content/event/hpe-ezmeral-unified-analytics.md
  static/img/event-hpe-ezmeral-early-access-webinar-294x306.png
Labels: netlify-cms/pending_review

#1584 Update Events “hpe-ezmeral-unified-analytics”
  content/event/hpe-ezmeral-unified-analytics.md
Labels: netlify-cms/pending_review

#1586 Update Platforms “hpe-ezmeral/home”
  content/platform/hpe-ezmeral/home.md
Labels: netlify-cms/pending_review

#1591 Update Blog “wow-a-practiced-and-perfected-design-process-part-1-uncovering-the-merit”
  content/blog/wow-a-practiced-and-perfected-design-process-part-1-uncovering-the-merit.md
Labels: netlify-cms/draft

#1594 Update Events “running-reliable-systems-part-1-an-overview-of-sre”
  content/event/running-reliable-systems-part-1-an-overview-of-sre.md
Labels: netlify-cms/draft

#1593 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1598 Update Blog “get-started-building-dscc-api-client-libraries-for-python-using-openapi-generator”
  content/blog/get-started-building-dscc-api-client-libraries-for-python-using-openapi-generator.md
Labels: netlify-cms/draft

#1596 Update Blog “explore-the-hpe-greenlake-for-compute-ops-management-rest-api-using-curl-and-postman”
  content/blog/explore-the-hpe-greenlake-for-compute-ops-management-rest-api-using-curl-and-postman.md
Labels: netlify-cms/pending_publish

#1605 Update GreenLake “hpe-greenlake-for-compute-ops-management/home”
  content/greenlake/hpe-greenlake-for-compute-ops-management/home.md
Labels: netlify-cms/draft

#1606 Update GreenLake “data-services-cloud-console/home”
  content/greenlake/data-services-cloud-console/home.md
Labels: netlify-cms/draft

#1607 Update Hackshack Home Cards “hackshackhome”
  content/hackshackhome/hackshackhome.md
Labels: netlify-cms/draft

#1608 Update Events “running-reliable-systems-part-2-service-level-objective-slo-math”
  content/event/running-reliable-systems-part-2-service-level-objective-slo-math.md
Labels: netlify-cms/draft

#1546 Create Hackshack Home Cards “hackshackhome-5”
  content/hackshackhome/hackshackhome-5.md
Labels: netlify-cms/pending_publish

#1547 Create Hackshack Home Cards “hackshackhome-6”
  content/hackshackhome/hackshackhome-6.md
Labels: netlify-cms/pending_publish

#1610 Create Blog “developing-an-open-source-metadata-framework-to-enhance-the-ml-pipeline-experience”
  content/blog/developing-an-open-source-metadata-framework-to-enhance-the-ml-pipeline-experience.md
Labels: netlify-cms/pending_review

#1613 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1614 Update Blog “sir-hackington-appbuilder-iii-tells-you-what-happened-at-oscon”
  content/blog/sir-hackington-appbuilder-iii-tells-you-what-happened-at-oscon.md
Labels: netlify-cms/draft

#1615 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1618 Update Events “running-reliable-systems-part-2-service-level-objective-slo-math”
  content/event/running-reliable-systems-part-2-service-level-objective-slo-math.md
Labels: netlify-cms/draft

#1619 Update Campaign “ezmeral-early-access-program”
  content/campaign/ezmeral-early-access-program.md
Labels: netlify-cms/draft

#1620 Update Campaign “ezmeral-early-access-program”
  content/campaign/ezmeral-early-access-program.md
Labels: netlify-cms/draft

#1621 Update Platforms “swarm-learning/home”
  content/platform/swarm-learning/home.md
Labels: netlify-cms/pending_publish

#1625 Update Platforms “hpe-ezmeral/home”
  content/platform/hpe-ezmeral/home.md
Labels: netlify-cms/pending_review

#1624 Update Platforms “hpe-ezmeral-data-fabric/home”
  content/platform/hpe-ezmeral-data-fabric/home.md
Labels: netlify-cms/pending_review

#1626 Update Platforms “project-data-map/home”
  content/platform/project-data-map/home.md
Labels: netlify-cms/pending_review

#1623 Update Platforms “swarm-learning/home”
  content/platform/swarm-learning/home.md
Labels: netlify-cms/pending_review

#1627 Update Blog “deploying-mongodb-application-on-hpe-greenlake-for-containers”
  content/blog/deploying-mongodb-application-on-hpe-greenlake-for-containers.md
Labels: netlify-cms/pending_review
