Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2022-10, with the labels that each got.

#1398 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1400 Create Events “hpe-sustainability-strategy-and-sustainability-research-at-hewlett-packard-labs”
  content/event/hpe-sustainability-strategy-and-sustainability-research-at-hewlett-packard-labs.md
Labels: netlify-cms/pending_publish

#1401 Create Hackshack Home Cards “hackshackhome-1”
  content/hackshackhome/hackshackhome-1.md
Labels: netlify-cms/pending_review

#1386 Create Blog “beta-test-our-new-hpe-greenlake-for-data-fabric”
  content/blog/beta-test-our-new-hpe-greenlake-for-data-fabric.md
  static/img/1338228_zh3kqtu6roaxv7asnc97_sw-dc-ezmeralwebinars-220921-gldatafabric-v1c.jpg
  static/img/alaric_0.1.jpg
Labels: netlify-cms/pending_review

#1385 Create Blog “call-for-hpe-ezmeral-unified-analytics-beta-testers”
  content/blog/call-for-hpe-ezmeral-unified-analytics-beta-testers.md
  static/img/1338228_24a2hpcq2kxibhbz2uuv_sw-dc-ezmeralwebinars-220921-ezmeralunifanlytcs-v3c.jpg
  static/img/skyler-thomas.jpg
Labels: netlify-cms/pending_review

#1402 Update Blog “beta-test-our-new-hpe-greenlake-for-data-fabric”
  content/blog/beta-test-our-new-hpe-greenlake-for-data-fabric.md
Labels: netlify-cms/draft

#1365 Create Campaign “ezmeral-early-access-program”
  content/campaign/ezmeral-early-access-program.md
Labels: netlify-cms/pending_review

#1367 Create Skillup “skillup-2”
  content/skillup/skillup-2.md
  static/img/ezmeral.jpg
  static/img/speedomoter_04_rgb.png
Labels: netlify-cms/pending_review

#1404 Create Blog “catch-hpe-at-kubecon-na-2022”
  content/blog/catch-hpe-at-kubecon-na-2022.md
  static/img/1338228_7dgv1delrhc291yqzimg_sw-dc-kubeconna-220920-v1.jpg
Labels: netlify-cms/pending_publish

#1405 Update Blog “catch-hpe-at-kubecon-na-2022”
  content/blog/catch-hpe-at-kubecon-na-2022.md
Labels: netlify-cms/draft

#1407 Update Blog “configuring-azure-ad-with-greenlake-cloud-platform-and-aruba-central”
  content/blog/configuring-azure-ad-with-greenlake-cloud-platform-and-aruba-central.md
Labels: netlify-cms/pending_publish

#1408 Update Blog “lift-and-transform-apps-with-hpe-csi-driver-for-kubernetes”
  content/blog/lift-and-transform-apps-with-hpe-csi-driver-for-kubernetes.md
Labels: netlify-cms/pending_publish

#1406 Update Blog “why-open-source-is-more-than-software-the-example-of-the-linux-foundations-agstack-project”
  content/blog/why-open-source-is-more-than-software-the-example-of-the-linux-foundations-agstack-project.md
Labels: netlify-cms/pending_publish

#1409 Update Blog “catch-hpe-at-kubecon-na-2022”
  content/blog/catch-hpe-at-kubecon-na-2022.md
Labels: netlify-cms/pending_publish

#1410 Update Blog “call-for-hpe-ezmeral-unified-analytics-beta-testers”
  content/blog/call-for-hpe-ezmeral-unified-analytics-beta-testers.md
Labels: netlify-cms/pending_publish

#1413 Update Blog “beta-test-our-new-hpe-greenlake-for-data-fabric”
  content/blog/beta-test-our-new-hpe-greenlake-for-data-fabric.md
Labels: netlify-cms/pending_publish

#1411 Update Blog “deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-–-part-2”
  content/blog/deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-–-part-2.md
Labels: netlify-cms/pending_review

#1412 Update Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2”
  content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2.md
Labels: netlify-cms/pending_publish

#1414 Update Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2”
  content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2.md
Labels: netlify-cms/pending_publish

#1415 Update Blog “call-for-hpe-ezmeral-unified-analytics-beta-testers”
  content/blog/call-for-hpe-ezmeral-unified-analytics-beta-testers.md
Labels: netlify-cms/draft

#1416 Update Home Panel “02-file-objects-databases-and-streams-oh-my”
  content/home/02-file-objects-databases-and-streams-oh-my.md
Labels: netlify-cms/pending_review

#1417 Update Home Panel “02-file-objects-databases-and-streams-oh-my”
  content/home/02-file-objects-databases-and-streams-oh-my.md
Labels: netlify-cms/pending_publish

#1423 Update Blog “catch-hpe-at-kubecon-na-2022”
  content/blog/catch-hpe-at-kubecon-na-2022.md
Labels: netlify-cms/draft

#1422 Update Blog “call-for-hpe-ezmeral-unified-analytics-beta-testers”
  content/blog/call-for-hpe-ezmeral-unified-analytics-beta-testers.md
Labels: netlify-cms/draft

#1421 Update Blog “beta-test-our-new-hpe-greenlake-for-data-fabric”
  content/blog/beta-test-our-new-hpe-greenlake-for-data-fabric.md
Labels: netlify-cms/draft

#1424 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1425 Update Platforms “spiffe-and-spire-projects/home”
  content/platform/spiffe-and-spire-projects/home.md
Labels: netlify-cms/pending_review

#1431 Create Blog “open-source-contributor-helps-istio-integrate-with-spire”
  content/blog/open-source-contributor-helps-istio-integrate-with-spire.md
Labels: netlify-cms/pending_review

#1435 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1436 Create Events “introduction-to-kubeflow”
  content/event/introduction-to-kubeflow.md
Labels: netlify-cms/pending_review

#1429 Update Blog “beta-test-our-new-hpe-greenlake-for-data-fabric”
  content/blog/beta-test-our-new-hpe-greenlake-for-data-fabric.md
Labels: netlify-cms/pending_publish

#1439 Update Blog “call-for-hpe-ezmeral-unified-analytics-beta-testers”
  content/blog/call-for-hpe-ezmeral-unified-analytics-beta-testers.md
Labels: netlify-cms/draft

#1441 Update Blog “deploy-stateful-mongodb-application-on-kubernetes-clusters-in-hpe-greenlake-for-containers-1”
  content/blog/deploy-stateful-mongodb-application-on-kubernetes-clusters-in-hpe-greenlake-for-containers-1.md
Labels: netlify-cms/draft

#1419 Update Campaign “ezmeral-early-access-program”
  content/campaign/ezmeral-early-access-program.md
Labels: netlify-cms/pending_review

#1450 Update Blog “open-source-contributor-helps-istio-integrate-with-spire”
  content/blog/open-source-contributor-helps-istio-integrate-with-spire.md
  static/img/max-lambrecht-istio-with-spire-1200-x-675.jpg
Labels: netlify-cms/draft

#1449 Update Blog “mellanox-switch-automation-welcome-to-2012”
  content/blog/mellanox-switch-automation-welcome-to-2012.md
  static/img/rick-kaufmann-network-automation-1200-x-675.jpg
Labels: netlify-cms/draft

#1451 Update Hackshack Home Cards “hackshackhome-1”
  content/hackshackhome/hackshackhome-1.md
Labels: netlify-cms/pending_review

#1437 Create Hackshack Home Cards “hackshackhome-2”
  content/hackshackhome/hackshackhome-2.md
Labels: netlify-cms/pending_publish

#1452 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#1455 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1457 Create Events “calling-all-citizen-developers-can-low-code-platforms-accelerate-your-impact”
  content/event/calling-all-citizen-developers-can-low-code-platforms-accelerate-your-impact.md
Labels: netlify-cms/pending_review

#1461 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#1459 Update Events “machine-learning-data-version-control-dvc-reproducibility-and-collaboration-in-your-ml-projects”
  content/event/machine-learning-data-version-control-dvc-reproducibility-and-collaboration-in-your-ml-projects.md
Labels: netlify-cms/pending_publish

#1462 Update Events “hpe-sustainability-strategy-and-sustainability-research-at-hewlett-packard-labs”
  content/event/hpe-sustainability-strategy-and-sustainability-research-at-hewlett-packard-labs.md
Labels: netlify-cms/pending_publish

#1464 Update Blog “mellanox-switch-automation-welcome-to-2012”
  content/blog/mellanox-switch-automation-welcome-to-2012.md
Labels: netlify-cms/pending_review

#1465 Update Blog “how-to-monitor-hpe-oneview-infrastructure-with-grafana-metrics-dashboards-and-influxdb”
  content/blog/how-to-monitor-hpe-oneview-infrastructure-with-grafana-metrics-dashboards-and-influxdb.md
Labels: netlify-cms/pending_review

#1470 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1468 Create Blog “spiffe-spire-graduates-enabling-greater-security-solutions”
  content/blog/spiffe-spire-graduates-enabling-greater-security-solutions.md
  static/img/spiffe-spire-graduation-card-1200-x-675.jpg
Labels: netlify-cms/draft

#1473 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#1475 Update Skillup “EzmeralLearnOnDemand”
  content/skillup/EzmeralLearnOnDemand.md
Labels: netlify-cms/pending_review

#1472 Create Skillup “skillup-3”
  content/skillup/skillup-3.md
  static/img/stoplight-02-positive_1600_0_72_rgb.jpg
  static/img/stoplight.jpg
Labels: netlify-cms/pending_review

#1477 Update Community “Twitter”
  content/community/Twitter.md
Labels: netlify-cms/pending_publish

#1476 Create Blog “reflections-on-helping-linux-become-enterprise-ready”
  content/blog/reflections-on-helping-linux-become-enterprise-ready.md
  static/img/making-linux-enterprise-ready.jpg
Labels: netlify-cms/pending_review

#1481 Update Blog “deploy-stateful-mongodb-application-on-kubernetes-clusters-in-hpe-greenlake-for-containers-1”
  content/blog/deploy-stateful-mongodb-application-on-kubernetes-clusters-in-hpe-greenlake-for-containers-1.md
Labels: netlify-cms/draft

#1482 Update Blog “how-to-monitor-hpe-compute-ops-management”
  content/blog/how-to-monitor-hpe-compute-ops-management.md
Labels: netlify-cms/draft

#1483 Update Blog “spiffe-spire-graduates-enabling-greater-security-solutions”
  content/blog/spiffe-spire-graduates-enabling-greater-security-solutions.md
Labels: netlify-cms/draft

#1484 Update Blog “catch-hpe-at-kubecon-na-2022”
  content/blog/catch-hpe-at-kubecon-na-2022.md
Labels: netlify-cms/draft

#1486 Update Hackshack Home Cards “treasurehunt”
  content/hackshackhome/treasurehunt.md
Labels: netlify-cms/pending_review

#1485 Update Hackshack Home Cards “hackshackhome”
  content/hackshackhome/hackshackhome.md
Labels: netlify-cms/pending_review

#1453 Create Events “running-reliable-systems-part-1-an-overview-of-sre”
  content/event/running-reliable-systems-part-1-an-overview-of-sre.md
Labels: netlify-cms/pending_review

#1489 Create Home Panel “2-spiffe-spire-graduates-enabling-greater-security-solutions”
  content/home/2-spiffe-spire-graduates-enabling-greater-security-solutions.md
Labels: netlify-cms/pending_publish
