Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2022-01, with the labels that each got.

#918 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#920 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#922 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_review

#925 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_publish

#926 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
  static/img/cap_02_rgb.png
Labels: netlify-cms/pending_review

#923 Update Skillup “MunchandLearn”
  content/skillup/MunchandLearn.md
  static/img/microscope_01_rgb.png
Labels: netlify-cms/pending_review

#911 Create Blog “here’s-to-2021-and-the-hpe-dev-community-take-a-bow-–-you-deserve-it”
  content/blog/here’s-to-2021-and-the-hpe-dev-community-take-a-bow-–-you-deserve-it.md
  static/img/dsc_3470-web-copy-2-.jpg
  static/img/hpedev-website.png
  static/img/new-portal-benefits.png
  static/img/sir-hackington-2021-small.png
  static/img/sir-hackington-2021.png
Labels: netlify-cms/pending_publish

#919 Create Blog “new-for-2022-hpe-dev-meetups”
  content/blog/new-for-2022-hpe-dev-meetups.md
  static/img/didier-lalli.png
  static/img/gettyimages-1213470242_v2_1600_0_72_rgb.jpg
Labels: netlify-cms/pending_publish

#928 Update Skillup “skillup”
  content/skillup/skillup.md
Labels: netlify-cms/pending_publish

#929 Update Skillup “skillup-1”
  content/skillup/skillup-1.md
Labels: netlify-cms/draft

#930 Create Events “hpe-dev-meetups”
  content/event/hpe-dev-meetups.md
Labels: netlify-cms/pending_publish

#931 Create Events “hpe-dev-meetups-1”
  content/event/hpe-dev-meetups-1.md
Labels: netlify-cms/pending_publish

#935 Update Campaign “devtalks”
  content/campaign/devtalks.md
Labels: netlify-cms/pending_review

#946 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#948 Create Events “hpe-dev-munch-learn-series-february-2022”
  content/event/hpe-dev-munch-learn-series-february-2022.md
Labels: netlify-cms/pending_publish

#951 Update Events “hpe-dev-meetups-1”
  content/event/hpe-dev-meetups-1.md
Labels: netlify-cms/pending_publish

#950 Update Events “hpe-dev-meetups”
  content/event/hpe-dev-meetups.md
Labels: netlify-cms/pending_review

#953 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#955 Update Blog “hpe-dev-launches-its-munch-learn-technical-talks”
  content/blog/hpe-dev-launches-its-munch-learn-technical-talks.md
  static/img/munch-learn-2-at-224.png
Labels: netlify-cms/pending_publish

#956 Update Blog “better-complex-event-processing-at-scale-using-a-microservices-based-str”
  content/blog/better-complex-event-processing-at-scale-using-a-microservices-based-str.md
Labels: netlify-cms/pending_review

#957 Update Blog “real-time-smart-city-traffic-monitoring-using-microservices-based-streaming-architecture-part-2”
  content/blog/real-time-smart-city-traffic-monitoring-using-microservices-based-streaming-architecture-part-2.md
Labels: netlify-cms/pending_review

#960 Update Events “hpe-dev-munch-learn-series-december-2021”
  content/event/hpe-dev-munch-learn-series-december-2021.md
Labels: netlify-cms/pending_review

#962 Update Events “hpe-dev-munch-learn-series-november-2021”
  content/event/hpe-dev-munch-learn-series-november-2021.md
Labels: netlify-cms/draft

#961 Update Events “hpe-dev-munch-learn-series-january-2022”
  content/event/hpe-dev-munch-learn-series-january-2022.md
Labels: netlify-cms/pending_review

#959 Update Events “hpe-dev-meetups”
  content/event/hpe-dev-meetups.md
Labels: netlify-cms/pending_review

#958 Create Events “hpe-dev-meetups-2”
  content/event/hpe-dev-meetups-2.md
Labels: netlify-cms/pending_review

#964 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#952 Create Blog “new-powershell-toolkit-available-for-managing-hpe-data-services-cloud-console”
  content/blog/new-powershell-toolkit-available-for-managing-hpe-data-services-cloud-console.md
  static/img/hpe-powershell-blog1.png
  static/img/hpe-powershell-blog10.png
  static/img/hpe-powershell-blog11.png
  static/img/hpe-powershell-blog12.png
  static/img/hpe-powershell-blog13.png
  static/img/hpe-powershell-blog14.png
  static/img/hpe-powershell-blog15.png
  static/img/hpe-powershell-blog2.png
  static/img/hpe-powershell-blog3.png
  static/img/hpe-powershell-blog4.png
  static/img/hpe-powershell-blog5.png
  static/img/hpe-powershell-blog6.png
  static/img/hpe-powershell-blog7.png
  static/img/hpe-powershell-blog8.png
  static/img/hpe-powershell-blog9.png
  static/img/powershell-api-client-credentials-img.png
  static/img/powershell-codeblock-dscc-img1.png
  static/img/powershell-codeblock-dscc-img10.png
  static/img/powershell-codeblock-dscc-img11.png
  static/img/powershell-codeblock-dscc-img2.png
  static/img/powershell-codeblock-dscc-img3.png
  static/img/powershell-codeblock-dscc-img4.png
  static/img/powershell-codeblock-dscc-img5.png
  static/img/powershell-codeblock-dscc-img6.png
  static/img/powershell-codeblock-dscc-img7.png
  static/img/powershell-codeblock-dscc-img8.png
  static/img/powershell-codeblock-dscc-img9.png
  static/img/powershell-create-credentials-img.png
  static/img/powershell-credentials-created-img.png
  static/img/powershell-manage-account-img.png
Labels: netlify-cms/pending_publish

#965 Update Blog “new-powershell-toolkit-available-for-managing-hpe-data-services-cloud-console”
  content/blog/new-powershell-toolkit-available-for-managing-hpe-data-services-cloud-console.md
Labels: netlify-cms/pending_publish

#966 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_publish
