Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2022-04, with the labels that each got.

#1084 Create Blog “highlighting-key-features-of-hpe-ezmeral-runtime-enterprise-release-5-4”
  content/blog/highlighting-key-features-of-hpe-ezmeral-runtime-enterprise-release-5-4.md
  static/img/srik.jpg
Labels: netlify-cms/pending_review

#1080 Create Blog “file-objects-databases-and-streams-–-oh-my”
  content/blog/file-objects-databases-and-streams-–-oh-my.md
  static/img/architecture-edf-7.png
  static/img/data-fabric-7-1200-x-675.png
  static/img/sridhar-reddy.png
Labels: netlify-cms/pending_review

#1087 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1089 Update Blog “get-started-building-dscc-api-client-libraries-for-python-using-openapi-generator”
  content/blog/get-started-building-dscc-api-client-libraries-for-python-using-openapi-generator.md
Labels: netlify-cms/draft

#1090 Update Blog “highlighting-key-features-of-hpe-ezmeral-runtime-enterprise-release-5-4”
  content/blog/highlighting-key-features-of-hpe-ezmeral-runtime-enterprise-release-5-4.md
Labels: netlify-cms/draft

#1095 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_publish

#1094 Update Blog “file-objects-databases-and-streams-–-oh-my”
  content/blog/file-objects-databases-and-streams-–-oh-my.md
  static/img/architecture-edf-7-963x500.png
Labels: netlify-cms/pending_review

#1101 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#1100 Create Events “hpe-dev-meetups-4”
  content/event/hpe-dev-meetups-4.md
Labels: netlify-cms/pending_review

#1109 Update Blog “be-an-hpe-dev-blogger”
  content/blog/be-an-hpe-dev-blogger.md
Labels: netlify-cms/draft

#1110 Update Events “engage-with-the-hpe-dev-team-at-hpe-technology-and-solution-summit-2022”
  content/event/engage-with-the-hpe-dev-team-at-hpe-technology-and-solution-summit-2022.md
Labels: netlify-cms/draft

#1118 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1119 Create Blog “it’s-all-fun-and-games-at-the-hack-shack”
  content/blog/it’s-all-fun-and-games-at-the-hack-shack.md
  static/img/lets-hack-shack-512.png
Labels: netlify-cms/pending_publish

#1122 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1121 Create Blog “kubecon-cloudnativecon-europe-16-20-may-2022”
  content/blog/kubecon-cloudnativecon-europe-16-20-may-2022.md
  static/img/kubecon-eu-2022-1200-x-675.png
Labels: netlify-cms/pending_review

#1125 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1124 Create Blog “becoming-a-linux-kernel-contributor-following-the-journey-of-souptick-joarder”
  content/blog/becoming-a-linux-kernel-contributor-following-the-journey-of-souptick-joarder.md
  static/img/linux_source_code_primary_site.png
  static/img/mm_mailing_list.png
Labels: netlify-cms/pending_review

#1128 Update Platforms “hpe-ezmeral-data-fabric/home”
  content/platform/hpe-ezmeral-data-fabric/home.md
Labels: netlify-cms/pending_review

#1131 Update Blog “kubecon-cloudnativecon-europe-16-20-may-2022”
  content/blog/kubecon-cloudnativecon-europe-16-20-may-2022.md
Labels: netlify-cms/pending_review

#1132 Update Home Panel “02-file-objects-databases-and-streams-oh-my”
  content/home/02-file-objects-databases-and-streams-oh-my.md
Labels: netlify-cms/pending_publish

#1133 Update Blog “deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-part-1”
  content/blog/deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-part-1.md
Labels: netlify-cms/pending_review

#1134 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review
