Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2022-09, with the labels that each got.

#1352 Update Platforms “project-data-map/home”
  content/platform/project-data-map/home.md
Labels: netlify-cms/pending_publish

#1358 Create Events “watch-party-nvidias-earth-2-digital-twins-for-weather-and-climate”
  content/event/watch-party-nvidias-earth-2-digital-twins-for-weather-and-climate.md
  static/img/nvida-watch-pary.jpg
Labels: netlify-cms/pending_review

#1356 Create Events “kubecon-na-2022”
  content/event/kubecon-na-2022.md
  static/img/kunecon-na-2022-eventcard.png
Labels: netlify-cms/pending_review

#1361 Update Blog “mapr-for-predictive-maintenance”
  content/blog/mapr-for-predictive-maintenance.md
Labels: netlify-cms/draft

#1362 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1364 Update Events “nvidia-deep-learning-institute”
  content/event/nvidia-deep-learning-institute.md
  static/img/self-paced-dli-fundamentals-course-fb-ig-no-copy-2048x2048.jpg
Labels: netlify-cms/draft

#1368 Create Events “intel-innovation-2022”
  content/event/intel-innovation-2022.md
  static/img/intelinnovation.jpg
Labels: netlify-cms/pending_review

#1371 Update Community “openSource”
  content/community/openSource.md
Labels: netlify-cms/pending_review

#1370 Update Community “EzmeralSoftwareForum”
  content/community/EzmeralSoftwareForum.md
Labels: netlify-cms/pending_review

#1369 Create Blog “chapel-scales-new-heights-with-1-28-0”
  content/blog/chapel-scales-new-heights-with-1-28-0.md
  static/img/gettyimages-571979257_1600_0_72_rgb-1200-x-675.jpg
  static/img/gettyimages-571979257_1600_0_72_rgb.jpg
Labels: netlify-cms/draft

#1373 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#1375 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1380 Update Community “openSource”
  content/community/openSource.md
Labels: netlify-cms/draft

#1376 Update Community “EzmeralSoftwareForum”
  content/community/EzmeralSoftwareForum.md
Labels: netlify-cms/draft

#1377 Update Community “newsletter”
  content/community/newsletter.md
Labels: netlify-cms/draft

#1381 Update Community “openSource”
  content/community/openSource.md
Labels: netlify-cms/draft

#1382 Update Community “newsletter”
  content/community/newsletter.md
Labels: netlify-cms/draft

#1374 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#1383 Update Blog “meet-open-source-grommet-lead-developer-and-architect-shimrit-yacobi”
  content/blog/meet-open-source-grommet-lead-developer-and-architect-shimrit-yacobi.md
Labels: netlify-cms/draft

#1360 Update Be an open source contributor “osscontribute”
  content/osscontribute/osscontribute.md
Labels: netlify-cms/pending_review

#1379 Update Community “OSScontribute”
  content/community/OSScontribute.md
Labels: netlify-cms/draft

#1384 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1387 Update Platforms “hpe-greenlake/home”
  content/platform/hpe-greenlake/home.md
Labels: netlify-cms/draft

#1390 Update Hackshack Home Cards “hackshackhome”
  content/hackshackhome/hackshackhome.md
Labels: netlify-cms/pending_review

#1391 Create Events “boost-spark-ai-workloads-with-pepperdata”
  content/event/boost-spark-ai-workloads-with-pepperdata.md
Labels: netlify-cms/pending_review

#1392 Update Blog “data-modeling-guidelines-for-nosql-json-document-databases”
  content/blog/data-modeling-guidelines-for-nosql-json-document-databases.md
Labels: netlify-cms/pending_review

#1395 Create Blog “hpe-greenlake-delivers-nvidia-ai-as-a-service”
  content/blog/hpe-greenlake-delivers-nvidia-ai-as-a-service.md
  static/img/gettyimages-180966749_1600_0_72_rgb-1200-x-675.jpg
Labels: netlify-cms/draft

#1396 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#1397 Update Events “accelerate-public-sector-ai-use-cases-using-a-powerful-ml-ops-platform”
  content/event/accelerate-public-sector-ai-use-cases-using-a-powerful-ml-ops-platform.md
Labels: netlify-cms/pending_review
