Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2022-08, with the labels that each got.

#1321 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#1324 Create Events “opentelemetry-getting-started-and-the-road-to-production”
  content/event/opentelemetry-getting-started-and-the-road-to-production.md
Labels: netlify-cms/draft

#1326 Update Events “finding-vulnerabilities-in-production-with-open-source-threatmapper”
  content/event/finding-vulnerabilities-in-production-with-open-source-threatmapper.md
Labels: netlify-cms/draft

#1325 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1329 Update Hackshack Home Cards “hackshackhome”
  content/hackshackhome/hackshackhome.md
Labels: netlify-cms/pending_review

#1328 Update Hackshack Home Cards “workshop”
  content/hackshackhome/workshop.md
Labels: netlify-cms/pending_review

#1323 Update Platforms “hpe-ezmeral/home”
  content/platform/hpe-ezmeral/home.md
Labels: netlify-cms/pending_review

#1322 Update Platforms “hpe-ezmeral-data-fabric/home”
  content/platform/hpe-ezmeral-data-fabric/home.md
Labels: netlify-cms/pending_review

#1331 Update Blog “summary-from-the-9th-annual-chapel-implementers-and-users-workshop-chiuw-2022”
  content/blog/summary-from-the-9th-annual-chapel-implementers-and-users-workshop-chiuw-2022.md
Labels: netlify-cms/draft

#1327 Create Events “machine-learning-data-version-control-dvc-reproducibility-and-collaboration-in-your-ml-projects”
  content/event/machine-learning-data-version-control-dvc-reproducibility-and-collaboration-in-your-ml-projects.md
Labels: netlify-cms/pending_review

#1330 Update Hackshack Home Cards “hpediscover2022”
  content/hackshackhome/hpediscover2022.md
Labels: netlify-cms/pending_review

#1338 Update Platforms “hpe-ezmeral-data-fabric/home”
  content/platform/hpe-ezmeral-data-fabric/home.md
Labels: netlify-cms/pending_publish

#1337 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1314 Create Platforms “hpe-greenlake-for-compute-ops-management/home”
  content/platform/hpe-greenlake-for-compute-ops-management/home.md
Labels: netlify-cms/pending_publish

#1340 Update Platforms “hpe-greenlake-for-compute-ops-management/home”
  content/platform/hpe-greenlake-for-compute-ops-management/home.md
Labels: netlify-cms/draft

#1333 Update Platforms “ilo-restful-api/home”
  content/platform/ilo-restful-api/home.md
Labels: netlify-cms/pending_publish

#1292 Create Events “nvidia-deep-learning-institute”
  content/event/nvidia-deep-learning-institute.md
  static/img/nvidia-dli-free-training-qrcode.png
Labels: netlify-cms/pending_review

#1344 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1346 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#1341 Update Hackshack Home Cards “hackshackhome”
  content/hackshackhome/hackshackhome.md
Labels: netlify-cms/pending_review

#1343 Create Events “accelerate-public-sector-ai-use-cases-using-a-powerful-ml-ops-platform”
  content/event/accelerate-public-sector-ai-use-cases-using-a-powerful-ml-ops-platform.md
Labels: netlify-cms/pending_review

#1347 Update Platforms “hpe-ezmeral-data-fabric/home”
  content/platform/hpe-ezmeral-data-fabric/home.md
Labels: netlify-cms/pending_review

#1348 Update Blog “mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service”
  content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
Labels: netlify-cms/pending_review

#1349 Create Blog “attend-nvidia-gtc-–-the-developer-conference-for-the-era-of-ai”
  content/blog/attend-nvidia-gtc-–-the-developer-conference-for-the-era-of-ai.md
Labels: netlify-cms/pending_review

#1350 Update Blog “attend-nvidia-gtc-–-the-developer-conference-for-the-era-of-ai”
  content/blog/attend-nvidia-gtc-–-the-developer-conference-for-the-era-of-ai.md
Labels: netlify-cms/pending_publish

#1339 Create Events “nvidia-gtc-–-the-developer-conference-for-the-era-of-ai”
  content/event/nvidia-gtc-–-the-developer-conference-for-the-era-of-ai.md
  static/img/gtc-nvidia-2022.jpg
  static/img/gtc22-co-branded-2048x1024-hpe.jpg
Labels: netlify-cms/pending_review

#1353 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1354 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#1355 Update Events “machine-learns-from-data-to-be-artificially-intelligent-use-cases-lessons-learned”
  content/event/machine-learns-from-data-to-be-artificially-intelligent-use-cases-lessons-learned.md
Labels: netlify-cms/pending_review
