Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2022-07, with the labels that each got.

#1285 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#1293 Update Blog “don’t-miss-all-things-software-in-the-hack-shack-at-hpe-discover”
  content/blog/don’t-miss-all-things-software-in-the-hack-shack-at-hpe-discover.md
Labels: netlify-cms/draft

#1294 Update Blog “why-open-source-is-more-than-software-the-example-of-the-linux-foundations-agstack-project”
  content/blog/why-open-source-is-more-than-software-the-example-of-the-linux-foundations-agstack-project.md
Labels: netlify-cms/draft

#1295 Update Blog “configuring-azure-ad-with-greenlake-cloud-platform-and-aruba-central”
  content/blog/configuring-azure-ad-with-greenlake-cloud-platform-and-aruba-central.md
Labels: netlify-cms/pending_review

#1297 Update Blog “lift-and-transform-apps-with-hpe-csi-driver-for-kubernetes”
  content/blog/lift-and-transform-apps-with-hpe-csi-driver-for-kubernetes.md
Labels: netlify-cms/pending_review

#1298 Update Blog “it’s-all-fun-and-games-at-the-hack-shack”
  content/blog/it’s-all-fun-and-games-at-the-hack-shack.md
Labels: netlify-cms/pending_review

#1299 Update Home Panel “02-file-objects-databases-and-streams-oh-my”
  content/home/02-file-objects-databases-and-streams-oh-my.md
Labels: netlify-cms/pending_review

#1301 Update Blog “scale-kubernetes-cluster-using-hpe-greenlake-terraform-provider”
  content/blog/scale-kubernetes-cluster-using-hpe-greenlake-terraform-provider.md
Labels: netlify-cms/pending_publish

#1300 Create Blog “discover-the-importance-of-hpe-greenlake-to-our-community”
  content/blog/discover-the-importance-of-hpe-greenlake-to-our-community.md
  static/img/hpe-dev-on-screen.jpg
Labels: netlify-cms/draft

#1302 Update Blog “configuring-azure-ad-with-greenlake-cloud-platform-and-aruba-central”
  content/blog/configuring-azure-ad-with-greenlake-cloud-platform-and-aruba-central.md
Labels: netlify-cms/draft

#1303 Update Blog “configuring-azure-ad-with-greenlake-cloud-platform-and-aruba-central”
  content/blog/configuring-azure-ad-with-greenlake-cloud-platform-and-aruba-central.md
Labels: netlify-cms/draft

#1310 Create Blog “introducing-the-hpe-greenlake-developer-portal”
  content/blog/introducing-the-hpe-greenlake-developer-portal.md
  static/img/gl-dev-portal-long-1200-x-675.jpg
Labels: netlify-cms/pending_publish

#1313 Create Blog “insights-from-a-hack-shack-staffers-diary”
  content/blog/insights-from-a-hack-shack-staffers-diary.md
  static/img/fred-1b-3-501-pix-.jpg
  static/img/fred-2-b-3-475-pix.jpg
  static/img/fred-2.jpg
  static/img/fred-3-b-3-405-pix-.jpg
  static/img/fred-4-b-3-450-pix-.jpg
  static/img/fred-5-b-3-512-pix-.jpg
  static/img/fred-6-b-3-512-.jpg
Labels: netlify-cms/pending_publish

#1296 Create Events “machine-learns-from-data-to-be-artificially-intelligent-use-cases-lessons-learned”
  content/event/machine-learns-from-data-to-be-artificially-intelligent-use-cases-lessons-learned.md
Labels: netlify-cms/pending_review

#1316 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#1318 Update Events “machine-learns-from-data-to-be-artificially-intelligent-use-cases-lessons-learned”
  content/event/machine-learns-from-data-to-be-artificially-intelligent-use-cases-lessons-learned.md
Labels: netlify-cms/pending_publish

#1317 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#1319 Update Blog “build-transformative-ai-applications-at-scale-with-hpe-cray-ai-development-environment”
  content/blog/build-transformative-ai-applications-at-scale-with-hpe-cray-ai-development-environment.md
Labels: netlify-cms/pending_publish

#1320 Update Blog “summary-from-the-9th-annual-chapel-implementers-and-users-workshop-chiuw-2022”
  content/blog/summary-from-the-9th-annual-chapel-implementers-and-users-workshop-chiuw-2022.md
Labels: netlify-cms/draft
