Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2022-11, with the labels that each got.

#1488 Create Blog “hpe-greenlake-test-drive-on-your-mark-get-set-go”
  content/blog/hpe-greenlake-test-drive-on-your-mark-get-set-go.md
  static/img/fred-1.png
  static/img/fred-2.png
  static/img/fred-3-ppt-a.png
  static/img/fred-3-test-drive-vs-hoste-trial-1040x773.png
  static/img/fred-3.png
  static/img/fred-4-ppt-a.png
  static/img/fred-4-ppt-c-425.png
  static/img/fred-4.png
  static/img/fred-5-ppt-b.jpg
  static/img/fred-6-ppt-b.jpg
  static/img/fred-6.png
  static/img/fred-7-ppt-a.png
  static/img/fred-7-ppt-b.jpg
  static/img/fred-8-ppt-a.png
  static/img/fred-9-ppt-a.png
  static/img/fred-9-ppt-b.jpg
  static/img/fred-9.png
  static/img/hpe-gl-test-drive-1200-x-675.jpg
Labels: netlify-cms/pending_publish

#1499 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1501 Create Hackshack Home Cards “hackshackhome-3”
  content/hackshackhome/hackshackhome-3.md
Labels: netlify-cms/pending_publish

#1506 Create Blog “how-citizen-developers-can-build-award-winning-enterprise-apps-with-low-code-development-platforms”
  content/blog/how-citizen-developers-can-build-award-winning-enterprise-apps-with-low-code-development-platforms.md
  static/img/blog-post-citizen-dev-award-winning-apps.jpg
  static/img/medium_am_fougerej_3109.jpg
Labels: netlify-cms/pending_review

#1512 Update Blog “get-started-building-dscc-api-client-libraries-for-python-using-openapi-generator”
  content/blog/get-started-building-dscc-api-client-libraries-for-python-using-openapi-generator.md
Labels: netlify-cms/pending_review

#1513 Update Platforms “data-services-cloud-console/home”
  content/platform/data-services-cloud-console/home.md
Labels: netlify-cms/pending_review

#1518 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1519 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1521 Update Blog “the-hpe-dev-community-hack-shack-a-place-to-gather-learn-and-play”
  content/blog/the-hpe-dev-community-hack-shack-a-place-to-gather-learn-and-play.md
Labels: netlify-cms/pending_review

#1522 Update Blog “exploring-the-role-of-the-citizen-developer”
  content/blog/exploring-the-role-of-the-citizen-developer.md
Labels: netlify-cms/draft

#1523 Update Blog “getting-started-with-the-hpe-data-services-cloud-console-public-rest-api”
  content/blog/getting-started-with-the-hpe-data-services-cloud-console-public-rest-api.md
Labels: netlify-cms/draft

#1524 Update Blog “api-console-for-data-services-cloud-console”
  content/blog/api-console-for-data-services-cloud-console.md
Labels: netlify-cms/draft

#1525 Update Blog “oauth2-for-hpe-greenlake-data-services-cloud-console”
  content/blog/oauth2-for-hpe-greenlake-data-services-cloud-console.md
Labels: netlify-cms/draft

#1527 Update Blog “get-started-building-dscc-api-client-libraries-for-python-using-openapi-generator”
  content/blog/get-started-building-dscc-api-client-libraries-for-python-using-openapi-generator.md
Labels: netlify-cms/draft

#1526 Update Blog “new-powershell-toolkit-available-for-managing-hpe-data-services-cloud-console”
  content/blog/new-powershell-toolkit-available-for-managing-hpe-data-services-cloud-console.md
Labels: netlify-cms/draft

#1528 Update Blog “how-to-use-an-api-access-token-for-hpe-greenlake-for-compute-ops-management”
  content/blog/how-to-use-an-api-access-token-for-hpe-greenlake-for-compute-ops-management.md
Labels: netlify-cms/draft

#1529 Update Blog “deploy-stateful-mongodb-application-on-kubernetes-clusters-in-hpe-greenlake-for-containers-1”
  content/blog/deploy-stateful-mongodb-application-on-kubernetes-clusters-in-hpe-greenlake-for-containers-1.md
Labels: netlify-cms/draft

#1530 Update Blog “introducing-the-hpe-greenlake-developer-portal”
  content/blog/introducing-the-hpe-greenlake-developer-portal.md
Labels: netlify-cms/draft

#1531 Update Blog “create-a-general-purpose-kubeconfig-file-in-hpe-greenlake-for-containers”
  content/blog/create-a-general-purpose-kubeconfig-file-in-hpe-greenlake-for-containers.md
Labels: netlify-cms/draft

#1532 Update Blog “how-to-set-up-an-automation-pipeline-to-view-historical-trend-data-of-clusters-with-hpe-greenlake-for-containers”
  content/blog/how-to-set-up-an-automation-pipeline-to-view-historical-trend-data-of-clusters-with-hpe-greenlake-for-containers.md
Labels: netlify-cms/draft

#1533 Update Blog “mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service”
  content/blog/mlops-–-deploying-an-ml-model-in-greenlake-platform-mlops-service.md
Labels: netlify-cms/draft

#1534 Update Blog “how-to-set-up-credentials-to-authenticate-container-registry-in-hpe-greenlake-for-containers”
  content/blog/how-to-set-up-credentials-to-authenticate-container-registry-in-hpe-greenlake-for-containers.md
Labels: netlify-cms/draft

#1539 Update Hackshack Home Cards “hackshackhome”
  content/hackshackhome/hackshackhome.md
Labels: netlify-cms/pending_review

#1540 Update Events “boost-spark-ai-workloads-with-pepperdata”
  content/event/boost-spark-ai-workloads-with-pepperdata.md
Labels: netlify-cms/pending_review

#1541 Update Events “calling-all-citizen-developers-can-low-code-platforms-accelerate-your-impact”
  content/event/calling-all-citizen-developers-can-low-code-platforms-accelerate-your-impact.md
Labels: netlify-cms/pending_review

#1538 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1542 Update Hackshack Home Cards “hackshackhome”
  content/hackshackhome/hackshackhome.md
Labels: netlify-cms/pending_review

#1548 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#1543 Create Events “hpe-greenlake-and-infrastructure-as-code-iac”
  content/event/hpe-greenlake-and-infrastructure-as-code-iac.md
Labels: netlify-cms/pending_review
