Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2022-03, with the labels that each got.

#1015 Create Events “storage-applications-in-kubernetes”
  content/event/storage-applications-in-kubernetes.md
  static/img/k8s-storage-apps-512.jpg
Labels: netlify-cms/pending_publish

#1017 Update Blog “curate-and-expose-service-catalog-items-using-hpe-greenlake-for-private-cloud”
  content/blog/curate-and-expose-service-catalog-items-using-hpe-greenlake-for-private-cloud.md
Labels: netlify-cms/pending_review

#1018 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_publish

#1020 Update Opensource “Spark”
  content/opensource/Spark.md
Labels: netlify-cms/draft

#1025 Update Events “hpe-dev-meetups-3”
  content/event/hpe-dev-meetups-3.md
  static/img/event-meetups_microscope_new.png
  static/img/event-ml_cap_02_rgb.png
Labels: netlify-cms/pending_publish

#1026 Update Events “hpe-dev-munch-learn-series-march-2022”
  content/event/hpe-dev-munch-learn-series-march-2022.md
Labels: netlify-cms/pending_publish

#1030 Update Blog “new-for-2022-hpe-dev-meetups”
  content/blog/new-for-2022-hpe-dev-meetups.md
Labels: netlify-cms/draft

#1029 Create Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform”
  content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform.md
  static/img/greenlakeapiclients.png
  static/img/greenlakeforprivatecloud.png
  static/img/greenlakeinstancecomplete.png
  static/img/greenlakeselectingspace.png
  static/img/greenlaketenantid.png
  static/img/greenlaketerraformapiclient.png
  static/img/picture-1.png
  static/img/terraformprovider.png
Labels: netlify-cms/pending_review

#1044 Update Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform”
  content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform.md
Labels: netlify-cms/pending_publish

#1047 Create Events “kubecon-eu-2022”
  content/event/kubecon-eu-2022.md
  static/img/kubeconeu-2022-event-card-image.png
Labels: netlify-cms/pending_publish

#1052 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#1060 Update Blog “get-started-building-dscc-api-client-libraries-for-python-using-openapi-generator”
  content/blog/get-started-building-dscc-api-client-libraries-for-python-using-openapi-generator.md
Labels: netlify-cms/pending_review

#1061 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1062 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#1063 Update Events “hpe-dev-munch-learn-series-march-2022”
  content/event/hpe-dev-munch-learn-series-march-2022.md
Labels: netlify-cms/pending_review

#1064 Create Events “hpe-dev-munch-learn-series-april-2022”
  content/event/hpe-dev-munch-learn-series-april-2022.md
Labels: netlify-cms/pending_review

#1065 Create Hackshack Home Cards “hackshackhome”
  content/hackshackhome/hackshackhome.md
Labels: netlify-cms/pending_review

#1068 Update Hackshack Home Cards “hackshackhome”
  content/hackshackhome/hackshackhome.md
Labels: netlify-cms/draft

#1069 Create Events “world-artificial-intelligence-cannes-festival”
  content/event/world-artificial-intelligence-cannes-festival.md
  static/img/waicf-event-image.png
Labels: netlify-cms/pending_review

#1083 Update Home Panel “06-featured-platform-2”
  content/home/06-featured-platform-2.md
Labels: netlify-cms/pending_review
