Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2022-06, with the labels that each got.

#1194 Update Events “hpe-dev-meetups-4”
  content/event/hpe-dev-meetups-4.md
Labels: netlify-cms/draft

#1188 Create Blog “don’t-miss-all-things-software-in-the-hack-shack-at-hpe-discover”
  content/blog/don’t-miss-all-things-software-in-the-hack-shack-at-hpe-discover.md
  static/img/3b80von6qmg5y9jpuzfn_hpe_discover-202022_ppt_sessionsnot2miss-blogsize-v1-hackshack.jpg
Labels: netlify-cms/pending_publish

#1197 Update Blog “highlighting-key-features-of-hpe-ezmeral-runtime-enterprise-release-5-4”
  content/blog/highlighting-key-features-of-hpe-ezmeral-runtime-enterprise-release-5-4.md
Labels: netlify-cms/pending_publish

#1198 Update Blog “it’s-all-fun-and-games-at-the-hack-shack”
  content/blog/it’s-all-fun-and-games-at-the-hack-shack.md
Labels: netlify-cms/pending_publish

#1200 Update Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2”
  content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2.md
Labels: netlify-cms/pending_publish

#1201 Update Blog “it’s-all-fun-and-games-at-the-hack-shack”
  content/blog/it’s-all-fun-and-games-at-the-hack-shack.md
Labels: netlify-cms/pending_publish

#1202 Update Blog “becoming-a-linux-kernel-contributor-following-the-journey-of-souptick-joarder”
  content/blog/becoming-a-linux-kernel-contributor-following-the-journey-of-souptick-joarder.md
Labels: netlify-cms/pending_publish

#1195 Create Blog “why-open-source-is-more-than-software-the-example-of-the-linux-foundations-agstack-project”
  content/blog/why-open-source-is-more-than-software-the-example-of-the-linux-foundations-agstack-project.md
  static/img/agstack-512.png
Labels: netlify-cms/pending_publish

#1204 Update Blog “becoming-a-linux-kernel-contributor-following-the-journey-of-souptick-joarder”
  content/blog/becoming-a-linux-kernel-contributor-following-the-journey-of-souptick-joarder.md
Labels: netlify-cms/pending_publish

#1205 Update Blog “why-open-source-is-more-than-software-the-example-of-the-linux-foundations-agstack-project”
  content/blog/why-open-source-is-more-than-software-the-example-of-the-linux-foundations-agstack-project.md
Labels: netlify-cms/pending_publish

#1206 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1211 Update Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform”
  content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform.md
Labels: netlify-cms/draft

#1209 Update Blog “don’t-miss-all-things-software-in-the-hack-shack-at-hpe-discover”
  content/blog/don’t-miss-all-things-software-in-the-hack-shack-at-hpe-discover.md
Labels: netlify-cms/draft

#1186 Create Blog “benefits-of-the-platform-level-data-model-for-firmware-update-standard”
  content/blog/benefits-of-the-platform-level-data-model-for-firmware-update-standard.md
Labels: netlify-cms/pending_publish

#1171 Create Blog “overview-of-the-platform-level-data-model-for-redfish®-device-enablement-standard”
  content/blog/overview-of-the-platform-level-data-model-for-redfish®-device-enablement-standard.md
  static/img/setrdenetworkadapterproperty.png
Labels: netlify-cms/pending_publish

#1214 Update Blog “overview-of-the-platform-level-data-model-for-redfish®-device-enablement-standard”
  content/blog/overview-of-the-platform-level-data-model-for-redfish®-device-enablement-standard.md
Labels: netlify-cms/pending_publish

#1216 Update Blog “benefits-of-the-platform-level-data-model-for-firmware-update-standard”
  content/blog/benefits-of-the-platform-level-data-model-for-firmware-update-standard.md
Labels: netlify-cms/pending_publish

#1217 Update Blog “it’s-all-fun-and-games-at-the-hack-shack”
  content/blog/it’s-all-fun-and-games-at-the-hack-shack.md
Labels: netlify-cms/draft

#1220 Update Blog “hpe-firmware-updates-part-1-file-types-and-smart-components”
  content/blog/hpe-firmware-updates-part-1-file-types-and-smart-components.md
Labels: netlify-cms/pending_publish

#1223 Update Blog “hpe-firmware-updates-part-1-file-types-and-smart-components”
  content/blog/hpe-firmware-updates-part-1-file-types-and-smart-components.md
Labels: netlify-cms/pending_publish

#1224 Update Blog “hpe-firmware-updates-part-2-interaction-in-operating-modes”
  content/blog/hpe-firmware-updates-part-2-interaction-in-operating-modes.md
Labels: netlify-cms/pending_publish

#1229 Update Blog “overview-of-the-platform-level-data-model-for-redfish®-device-enablement-standard”
  content/blog/overview-of-the-platform-level-data-model-for-redfish®-device-enablement-standard.md
Labels: netlify-cms/pending_publish

#1234 Update Blog “how-to-set-up-an-automation-pipeline-to-view-historical-trend-data-of-clusters-with-hpe-greenlake-for-containers”
  content/blog/how-to-set-up-an-automation-pipeline-to-view-historical-trend-data-of-clusters-with-hpe-greenlake-for-containers.md
  static/img/sweta-blog-post-v2-1200-x-675.jpg
Labels: netlify-cms/pending_publish

#1235 Update Blog “it’s-all-fun-and-games-at-the-hack-shack”
  content/blog/it’s-all-fun-and-games-at-the-hack-shack.md
Labels: netlify-cms/draft

#1219 Create Platforms “zerto/home”
  content/platform/zerto/home.md
Labels: netlify-cms/pending_review

#1240 Update Blog “lift-and-transform-apps-with-hpe-csi-driver-for-kubernetes”
  content/blog/lift-and-transform-apps-with-hpe-csi-driver-for-kubernetes.md
Labels: netlify-cms/pending_publish

#1225 Update Blog “storage-management-with-redfish”
  content/blog/storage-management-with-redfish.md
Labels: netlify-cms/pending_publish

#1241 Update What's Your Role “data-ml-engineer/home”
  content/role/data-ml-engineer/home.md
Labels: netlify-cms/pending_review

#1242 Update What's Your Role “data-scientist/home”
  content/role/data-scientist/home.md
Labels: netlify-cms/pending_review

#1243 Update Platforms “hpe-ezmeral-data-fabric/home”
  content/platform/hpe-ezmeral-data-fabric/home.md
Labels: netlify-cms/draft

#1245 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1244 Create Events “finding-vulnerabilities-in-production-with-open-source-threatmapper”
  content/event/finding-vulnerabilities-in-production-with-open-source-threatmapper.md
Labels: netlify-cms/pending_publish

#1247 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1248 Update Events “finding-vulnerabilities-in-production-with-open-source-threatmapper”
  content/event/finding-vulnerabilities-in-production-with-open-source-threatmapper.md
Labels: netlify-cms/pending_publish

#1250 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1207 Update Platforms “hpe-greenlake/home”
  content/platform/hpe-greenlake/home.md
Labels: netlify-cms/pending_publish

#1253 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1257 Update Events “opensearch-–-the-open-source-search-and-analytics-suite-you-can-run-yourself”
  content/event/opensearch-–-the-open-source-search-and-analytics-suite-you-can-run-yourself.md
Labels: netlify-cms/draft

#1265 Update Platforms “ilo-restful-api/home”
  content/platform/ilo-restful-api/home.md
Labels: netlify-cms/draft

#1266 Update Platforms “hpe-simplivity/home”
  content/platform/hpe-simplivity/home.md
Labels: netlify-cms/draft

#1268 Update Platforms “hpe-oneview-global-dashboard/home”
  content/platform/hpe-oneview-global-dashboard/home.md
Labels: netlify-cms/draft

#1269 Update Platforms “hpe-oneview/home”
  content/platform/hpe-oneview/home.md
Labels: netlify-cms/draft

#1270 Update Platforms “aruba/home”
  content/platform/aruba/home.md
Labels: netlify-cms/draft

#1271 Update Platforms “hpe-nimble-storage/home”
  content/platform/hpe-nimble-storage/home.md
Labels: netlify-cms/draft

#1272 Update Platforms “hpe-3par-and-primera/home”
  content/platform/hpe-3par-and-primera/home.md
Labels: netlify-cms/draft

#1267 Update Platforms “zerto/home”
  content/platform/zerto/home.md
Labels: netlify-cms/draft

#1274 Update Platforms “smartsim/home”
  content/platform/smartsim/home.md
Labels: netlify-cms/draft

#1275 Update Platforms “chapel/home”
  content/platform/chapel/home.md
Labels: netlify-cms/draft

#1276 Update Platforms “grommet/home”
  content/platform/grommet/home.md
Labels: netlify-cms/draft

#1277 Update Platforms “spiffe-and-spire-projects/home”
  content/platform/spiffe-and-spire-projects/home.md
Labels: netlify-cms/draft

#1263 Update Platforms “hpe-ezmeral-data-fabric/home”
  content/platform/hpe-ezmeral-data-fabric/home.md
Labels: netlify-cms/pending_review

#1262 Update Platforms “hpe-ezmeral/home”
  content/platform/hpe-ezmeral/home.md
Labels: netlify-cms/pending_review

#1259 Update Platforms “data-services-cloud-console/home”
  content/platform/data-services-cloud-console/home.md
Labels: netlify-cms/pending_review

#1261 Update Platforms “hpe-greenlake/home”
  content/platform/hpe-greenlake/home.md
Labels: netlify-cms/pending_review

#1260 Update What's Your Role “data-scientist/home”
  content/role/data-scientist/home.md
Labels: netlify-cms/draft

#1256 Create Platforms “project-data-map/home”
  content/platform/project-data-map/home.md
  static/img/hpe-element.png
  static/img/platforms/hpe-element.png
Labels: netlify-cms/pending_publish

#1258 Update Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform”
  content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform.md
Labels: netlify-cms/draft

#1280 Create Blog “service-mesh-security-hardening-–-using-spire-with-istio”
  content/blog/service-mesh-security-hardening-–-using-spire-with-istio.md
Labels: netlify-cms/pending_publish

#1281 Update Blog “service-mesh-security-hardening-–-using-spire-with-istio”
  content/blog/service-mesh-security-hardening-–-using-spire-with-istio.md
  static/img/service-mesh-security-istio-1200-x-675.png
Labels: netlify-cms/pending_publish

#1282 Update Blog “service-mesh-security-hardening-–-using-spire-with-istio”
  content/blog/service-mesh-security-hardening-–-using-spire-with-istio.md
  static/img/service-mesh-istio-512-x-393.jpg
Labels: netlify-cms/pending_publish
