Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2023-12, with the labels that each got.

#2202 Create Blog “automate-itops-announcing-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform”
  content/blog/automate-itops-announcing-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform.md
Labels: netlify-cms/pending_review

#2190 Update GreenLake “hpe-greenlake-platform/home”
  content/greenlake/hpe-greenlake-platform/home.md
Labels: netlify-cms/pending_review

#2213 Update Events “automated-continuous-deployment-of-container-based-applications-onto-hpe-greenlake-for-private-cloud-enterprise”
  content/event/automated-continuous-deployment-of-container-based-applications-onto-hpe-greenlake-for-private-cloud-enterprise.md
Labels: netlify-cms/draft

#2214 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2215 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2217 Update Blog “sc23-from-the-chapel-language-perspective”
  content/blog/sc23-from-the-chapel-language-perspective.md
Labels: netlify-cms/draft

#2218 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2219 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2220 Update Hackshack Home Cards “hackshackhome-24”
  content/hackshackhome/hackshackhome-24.md
Labels: netlify-cms/pending_review

#2221 Update Events “exploring-hpe-greenlake-platform-apis-through-use-cases”
  content/event/exploring-hpe-greenlake-platform-apis-through-use-cases.md
Labels: netlify-cms/pending_review

#2224 Update Blog “hpe-firmware-updates-part-3-the-redfish-update-service”
  content/blog/hpe-firmware-updates-part-3-the-redfish-update-service.md
Labels: netlify-cms/pending_review

#2227 Update Blog “announcing-chapel-1-33”
  content/blog/announcing-chapel-1-33.md
Labels: netlify-cms/pending_review

#2233 Create Events “apis-for-hpe-greenlake-for-block-storage-and-next-gen-platforms”
  content/event/apis-for-hpe-greenlake-for-block-storage-and-next-gen-platforms.md
Labels: netlify-cms/pending_review

#2232 Create Events “getting-started-with-aruba-central-automation”
  content/event/getting-started-with-aruba-central-automation.md
Labels: netlify-cms/pending_review

#2231 Create Events “getting-started-with-hpe-greenlake-for-compute-ops-management-apis”
  content/event/getting-started-with-hpe-greenlake-for-compute-ops-management-apis.md
Labels: netlify-cms/pending_review

#2230 Create Hackshack Home Cards “hackshackhome-27”
  content/hackshackhome/hackshackhome-27.md
Labels: netlify-cms/pending_review

#2229 Create Hackshack Home Cards “hackshackhome-26”
  content/hackshackhome/hackshackhome-26.md
Labels: netlify-cms/pending_review

#2228 Create Hackshack Home Cards “hackshackhome-25”
  content/hackshackhome/hackshackhome-25.md
Labels: netlify-cms/pending_review

#2237 Update Platforms “hpe-cray-programming-environment/home”
  content/platform/hpe-cray-programming-environment/home.md
Labels: netlify-cms/draft

#2238 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2239 Update Events “exploring-hpe-greenlake-platform-apis-through-use-cases”
  content/event/exploring-hpe-greenlake-platform-apis-through-use-cases.md
Labels: netlify-cms/pending_review

#2240 Update Blog “dark-mode-theming-in-grommet-adding-dark-and-light-theme-modes”
  content/blog/dark-mode-theming-in-grommet-adding-dark-and-light-theme-modes.md
Labels: netlify-cms/draft

#2242 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2246 Update Hackshack Home Cards “hackshackhome-27”
  content/hackshackhome/hackshackhome-27.md
Labels: netlify-cms/pending_publish

#2245 Update Hackshack Home Cards “hackshackhome-26”
  content/hackshackhome/hackshackhome-26.md
Labels: netlify-cms/pending_publish

#2244 Update Hackshack Home Cards “hackshackhome-25”
  content/hackshackhome/hackshackhome-25.md
Labels: netlify-cms/pending_publish

#2248 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2243 Create Events “using-hpe-greenlake-edge-to-cloud-platform-to-build-a-private-cloud”
  content/event/using-hpe-greenlake-edge-to-cloud-platform-to-build-a-private-cloud.md
Labels: netlify-cms/pending_review

#2247 Create Hackshack Home Cards “hackshackhome-28”
  content/hackshackhome/hackshackhome-28.md
Labels: netlify-cms/pending_review

#2249 Update Hackshack Home Cards “hackshackhome-27”
  content/hackshackhome/hackshackhome-27.md
Labels: netlify-cms/draft
