Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2023-03, with the labels that each got.

#1773 Update Events “accelerating-scientific-research-through-high-performance-computing-democratization”
  content/event/accelerating-scientific-research-through-high-performance-computing-democratization.md
Labels: netlify-cms/draft

#1774 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1775 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1776 Update Events “galadriel-an-alternative-approach-to-spire-federation”
  content/event/galadriel-an-alternative-approach-to-spire-federation.md
Labels: netlify-cms/draft

#1778 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1779 Create Events “determined-ai-model-training-hackathon”
  content/event/determined-ai-model-training-hackathon.md
Labels: netlify-cms/pending_review

#1663 Create Blog “open-sourcing-workshops-on-demand-part2-deploying-the-backend”
  content/blog/open-sourcing-workshops-on-demand-part2-deploying-the-backend.md
  static/img/wod-blogserie2-repos.png
  static/img/wod-blogserie2-tree1.png
  static/img/wod-blogserie2-tree2.png
  static/img/wod-blogserie2-tree3.png
  static/img/wod-blogserie2-tree4.png
  static/img/wod-blogserie2backend-workflow.png
  static/img/wod-blogserie2repos.png
  static/img/wod-blogserie3-archi3.png
Labels: netlify-cms/pending_review

#1782 Update Blog “open-sourcing-workshops-on-demand-part2-deploying-the-backend”
  content/blog/open-sourcing-workshops-on-demand-part2-deploying-the-backend.md
Labels: netlify-cms/draft

#1786 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1787 Create Events “leveraging-tech-to-address-global-challenges-health”
  content/event/leveraging-tech-to-address-global-challenges-health.md
Labels: netlify-cms/pending_review

#1794 Update Hackshack Home Cards “hackshackhome-9”
  content/hackshackhome/hackshackhome-9.md
Labels: netlify-cms/draft

#1793 Update Events “extraordinary-claims-require-extraordinary-engineering-and-tamo-isn’t-an-option”
  content/event/extraordinary-claims-require-extraordinary-engineering-and-tamo-isn’t-an-option.md
Labels: netlify-cms/draft

#1792 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1789 Create Hackshack Home Cards “hackshackhome-12”
  content/hackshackhome/hackshackhome-12.md
Labels: netlify-cms/pending_review

#1795 Update Hackshack Home Cards “hackshackhome-12”
  content/hackshackhome/hackshackhome-12.md
Labels: netlify-cms/draft

#1777 Create Platforms “hpe-cray-programming-environment/home”
  content/platform/hpe-cray-programming-environment/home.md
  static/img/cray_logo_-2018-.svg.png
Labels: netlify-cms/draft

#1796 Update Platforms “hpe-cray-programming-environment/home”
  content/platform/hpe-cray-programming-environment/home.md
Labels: netlify-cms/draft

#1798 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1799 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1800 Update Blog “bare-metal-provisioning-on-hpe-greenlake-using-terraform”
  content/blog/bare-metal-provisioning-on-hpe-greenlake-using-terraform.md
Labels: netlify-cms/draft

#1801 Update Blog “custom-docker-images-for-emr-serverless”
  content/blog/custom-docker-images-for-emr-serverless.md
Labels: netlify-cms/draft

#1802 Update Blog “custom-docker-images-for-emr-serverless”
  content/blog/custom-docker-images-for-emr-serverless.md
Labels: netlify-cms/draft

#1811 Update Blog “announcing-chapel-1-30-0”
  content/blog/announcing-chapel-1-30-0.md
Labels: netlify-cms/draft

#1812 Update Blog “chapel-scales-new-heights-with-1-28-0”
  content/blog/chapel-scales-new-heights-with-1-28-0.md
Labels: netlify-cms/draft

#1813 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1814 Update Events “collaborating-at-scale-with-postman”
  content/event/collaborating-at-scale-with-postman.md
Labels: netlify-cms/draft

#1815 Update Hackshack Home Cards “hackshackhome-10”
  content/hackshackhome/hackshackhome-10.md
Labels: netlify-cms/draft

#1790 Create Hackshack Home Cards “hackshackhome-13”
  content/hackshackhome/hackshackhome-13.md
Labels: netlify-cms/pending_publish

#1816 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1821 Update Blog “introducing-python-sdk-for-dscc”
  content/blog/introducing-python-sdk-for-dscc.md
Labels: netlify-cms/draft

#1820 Update Blog “automating-operations-on-dscc-using-ansible-playbooks”
  content/blog/automating-operations-on-dscc-using-ansible-playbooks.md
Labels: netlify-cms/draft

#1823 Update Blog “automating-operations-on-dscc-using-ansible-playbooks”
  content/blog/automating-operations-on-dscc-using-ansible-playbooks.md
Labels: netlify-cms/draft

#1822 Update Blog “creating-dscc-block-storage-resources-using-dscc-ansible-playbooks”
  content/blog/creating-dscc-block-storage-resources-using-dscc-ansible-playbooks.md
Labels: netlify-cms/draft

#1826 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1824 Update Events “collaborating-at-scale-with-postman”
  content/event/collaborating-at-scale-with-postman.md
Labels: netlify-cms/draft

#1825 Update Events “extraordinary-claims-require-extraordinary-engineering-and-tamo-isn’t-an-option”
  content/event/extraordinary-claims-require-extraordinary-engineering-and-tamo-isn’t-an-option.md
Labels: netlify-cms/draft

#1827 Update Platforms “ilo-restful-api/home”
  content/platform/ilo-restful-api/home.md
Labels: netlify-cms/pending_review
