Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2023-06, with the labels that each got.

#1926 Update Events “hpe-machine-learning-development-environment-and-the-open-source-ml-advantage”
  content/event/hpe-machine-learning-development-environment-and-the-open-source-ml-advantage.md
Labels: netlify-cms/draft

#1924 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1927 Update Home Panel “07-spiffe-spire-graduates-enabling-greater-security-solutions”
  content/home/07-spiffe-spire-graduates-enabling-greater-security-solutions.md
Labels: netlify-cms/draft

#1928 Update Blog “meet-our-new-hpe-dev-team-representative-at-hpe-technology-and-solution-summit-2023”
  content/blog/meet-our-new-hpe-dev-team-representative-at-hpe-technology-and-solution-summit-2023.md
Labels: netlify-cms/draft

#1929 Update Blog “new-for-hpe-discover-2023-hack-shack-serves-as-home-base-for-hpe’s-office-of-the-cto”
  content/blog/new-for-hpe-discover-2023-hack-shack-serves-as-home-base-for-hpe’s-office-of-the-cto.md
Labels: netlify-cms/draft

#1932 Update Blog “new-powershell-library-for-the-hpe-greenlake-cloud-platform”
  content/blog/new-powershell-library-for-the-hpe-greenlake-cloud-platform.md
Labels: netlify-cms/draft

#1933 Update Blog “new-powershell-library-for-the-hpe-greenlake-cloud-platform”
  content/blog/new-powershell-library-for-the-hpe-greenlake-cloud-platform.md
Labels: netlify-cms/draft

#1935 Update Events “hpe-machine-learning-development-environment-and-the-open-source-ml-advantage”
  content/event/hpe-machine-learning-development-environment-and-the-open-source-ml-advantage.md
Labels: netlify-cms/draft

#1936 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1937 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1662 Create Blog “why-devsecops-approach-is-key-to-mainstream-container-use”
  content/blog/why-devsecops-approach-is-key-to-mainstream-container-use.md
Labels: netlify-cms/pending_publish

#1661 Create Blog “3-ways-a-data-fabric-enables-a-data-first-approach”
  content/blog/3-ways-a-data-fabric-enables-a-data-first-approach.md
  static/img/3waysadatafabric-enablesadatafirstapproach-quote.png
Labels: netlify-cms/pending_publish

#1947 Update Platforms “determined-ai/home”
  content/platform/determined-ai/home.md
Labels: netlify-cms/draft

#1948 Update Blog “deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-part-1”
  content/blog/deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-part-1.md
Labels: netlify-cms/draft

#1949 Update Blog “deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-–-part-2”
  content/blog/deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-–-part-2.md
Labels: netlify-cms/draft

#1950 Update Blog “writing-deep-learning-tools-for-all-data-scientists-not-just-unicorns”
  content/blog/writing-deep-learning-tools-for-all-data-scientists-not-just-unicorns.md
Labels: netlify-cms/draft

#1951 Update Blog “intro-to-core-api-part-1-integer-incrementing”
  content/blog/intro-to-core-api-part-1-integer-incrementing.md
Labels: netlify-cms/draft

#1953 Update Events “digital-twins-the-metaverse-and-augmented-reality-developer-insights-and-it-foundations-for-immersive-technologies-powered-by-ai”
  content/event/digital-twins-the-metaverse-and-augmented-reality-developer-insights-and-it-foundations-for-immersive-technologies-powered-by-ai.md
Labels: netlify-cms/draft

#1954 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1958 Update Platforms “hpe-machine-learning-development-environment/home”
  content/platform/hpe-machine-learning-development-environment/home.md
Labels: netlify-cms/draft

#1959 Update Platforms “hpe-machine-learning-development-environment/home”
  content/platform/hpe-machine-learning-development-environment/home.md
Labels: netlify-cms/draft

#1942 Update Hackshack Home Cards “hackshackhome-14”
  content/hackshackhome/hackshackhome-14.md
Labels: netlify-cms/draft

#1965 Update Blog “meet-open-source-contributor-and-fpart-fpsync-project-developer-ganael-laplanche”
  content/blog/meet-open-source-contributor-and-fpart-fpsync-project-developer-ganael-laplanche.md
Labels: netlify-cms/draft

#1967 Create Events “ml-at-scale-‘23”
  content/event/ml-at-scale-‘23.md
  static/img/ml-at-scale-hopin-1500x600-copy.png
Labels: netlify-cms/pending_review

#1969 Update Blog “production-ready-object-detection-model-training-workflow-with-hpe-machine-learning-development-environment”
  content/blog/production-ready-object-detection-model-training-workflow-with-hpe-machine-learning-development-environment.md
Labels: netlify-cms/draft

#1971 Update Blog “announcing-chapel-1-31”
  content/blog/announcing-chapel-1-31.md
Labels: netlify-cms/draft

#1974 Update Hackshack Home Cards “hackshackhome-14”
  content/hackshackhome/hackshackhome-14.md
Labels: netlify-cms/draft

#1975 Update Events “digital-twins-the-metaverse-and-augmented-reality-developer-insights-and-it-foundations-for-immersive-technologies-powered-by-ai”
  content/event/digital-twins-the-metaverse-and-augmented-reality-developer-insights-and-it-foundations-for-immersive-technologies-powered-by-ai.md
Labels: netlify-cms/draft

#1976 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1977 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1978 Create Events “observability-in-action”
  content/event/observability-in-action.md
Labels: netlify-cms/draft

#1979 Create Hackshack Home Cards “hackshackhome-17”
  content/hackshackhome/hackshackhome-17.md
Labels: netlify-cms/draft
