Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2023-02, with the labels that each got.

#1725 Update Blog “deploying-mongodb-application-on-hpe-greenlake-for-containers”
  content/blog/deploying-mongodb-application-on-hpe-greenlake-for-containers.md
Labels: netlify-cms/draft

#1727 Update Events “hpe-greenlake-and-infrastructure-as-code-iac”
  content/event/hpe-greenlake-and-infrastructure-as-code-iac.md
Labels: netlify-cms/draft

#1699 Create Blog “learn-what-you-can-do-with-hpe-data-services-cloud-console-api-in-just-3-minutes”
  content/blog/learn-what-you-can-do-with-hpe-data-services-cloud-console-api-in-just-3-minutes.md
  static/img/authorization-dscc-collection-postman-figure4.png
  static/img/authorization-inherited-dscc-collection-postman-figure5.png
  static/img/getallstoragesystems-dscc-collection-postman-figure6.png
  static/img/search-dscc-collection-postman-figure1.png
  static/img/tests-capturebearertoken-dscc-collection-postman-figure3.png
  static/img/variables-dscc-collection-postman-figure2.png
Labels: netlify-cms/pending_review

#1728 Update Blog “get-started-with-application-performance-monitoring-tools-overview”
  content/blog/get-started-with-application-performance-monitoring-tools-overview.md
Labels: netlify-cms/draft

#1729 Update Blog “set-up-apache-skywalking-for-k8s-and-vm-monitoring-in-hpe-greenlake-private-cloud”
  content/blog/set-up-apache-skywalking-for-k8s-and-vm-monitoring-in-hpe-greenlake-private-cloud.md
Labels: netlify-cms/draft

#1730 Update Blog “set-up-apache-skywalking-for-k8s-monitoring-in-hpe-greenlake-for-private-cloud-enterprise”
  content/blog/set-up-apache-skywalking-for-k8s-monitoring-in-hpe-greenlake-for-private-cloud-enterprise.md
Labels: netlify-cms/draft

#1732 Update Blog “how-to-deploy-application-across-hybrid-clouds-beyond-hpe-greenlake-for-private-cloud-enterprise”
  content/blog/how-to-deploy-application-across-hybrid-clouds-beyond-hpe-greenlake-for-private-cloud-enterprise.md
Labels: netlify-cms/draft

#1734 Update Blog “announcing-chapel-1-29-0”
  content/blog/announcing-chapel-1-29-0.md
Labels: netlify-cms/draft

#1736 Update Blog “kubernetes-clusters-as-code-part1”
  content/blog/kubernetes-clusters-as-code-part1.md
Labels: netlify-cms/draft

#1737 Update Blog “kubernetes-cluster-as-code-part-2”
  content/blog/kubernetes-cluster-as-code-part-2.md
Labels: netlify-cms/draft

#1738 Update Blog “scale-kubernetes-cluster-using-hpe-greenlake-terraform-provider”
  content/blog/scale-kubernetes-cluster-using-hpe-greenlake-terraform-provider.md
Labels: netlify-cms/draft

#1739 Update Blog “scale-kubernetes-cluster-using-hpe-greenlake-terraform-provider”
  content/blog/scale-kubernetes-cluster-using-hpe-greenlake-terraform-provider.md
Labels: netlify-cms/draft

#1741 Update Blog “greenlake-platform-infrastructure-monitoring-with-apache-skywalking”
  content/blog/greenlake-platform-infrastructure-monitoring-with-apache-skywalking.md
Labels: netlify-cms/draft

#1743 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1744 Update Blog “deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-part-1”
  content/blog/deep-learning-model-training-–-a-first-time-user’s-experience-with-determined-part-1.md
Labels: netlify-cms/pending_review

#1746 Create Blog “smart-use-cases-for-smartsim”
  content/blog/smart-use-cases-for-smartsim.md
Labels: netlify-cms/pending_review

#1751 Update Events “accelerating-scientific-research-through-high-performance-computing-democratization”
  content/event/accelerating-scientific-research-through-high-performance-computing-democratization.md
Labels: netlify-cms/draft

#1753 Update Hackshack Home Cards “hackshackhome-8”
  content/hackshackhome/hackshackhome-8.md
Labels: netlify-cms/draft

#1752 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1681 Create Hackshack Home Cards “hackshackhome-10”
  content/hackshackhome/hackshackhome-10.md
Labels: netlify-cms/pending_publish

#1757 Update Events “galadriel-an-alternative-approach-to-spire-federation”
  content/event/galadriel-an-alternative-approach-to-spire-federation.md
Labels: netlify-cms/draft

#1758 Update Hackshack Home Cards “hackshackhome-7”
  content/hackshackhome/hackshackhome-7.md
Labels: netlify-cms/draft

#1759 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1760 Update Blog “a-guide-to-enable-managed-istio-service-mesh-in-a-kubernetes-cluster-on-hpe-greenlake-for-private-cloud-enterprise”
  content/blog/a-guide-to-enable-managed-istio-service-mesh-in-a-kubernetes-cluster-on-hpe-greenlake-for-private-cloud-enterprise.md
Labels: netlify-cms/draft

#1762 Update Hackshack Home Cards “hackshackhome-9”
  content/hackshackhome/hackshackhome-9.md
Labels: netlify-cms/pending_publish

#1763 Update Hackshack Home Cards “hackshackhome-10”
  content/hackshackhome/hackshackhome-10.md
Labels: netlify-cms/pending_publish

#1764 Create Events “divide-and-conquer-with-microfrontends”
  content/event/divide-and-conquer-with-microfrontends.md
Labels: netlify-cms/pending_review

#1765 Create Hackshack Home Cards “hackshackhome-11”
  content/hackshackhome/hackshackhome-11.md
Labels: netlify-cms/pending_review

#1766 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#1761 Update Blog “a-guide-to-enable-managed-istio-service-mesh-in-a-kubernetes-cluster-on-hpe-greenlake-for-private-cloud-enterprise”
  content/blog/a-guide-to-enable-managed-istio-service-mesh-in-a-kubernetes-cluster-on-hpe-greenlake-for-private-cloud-enterprise.md
Labels: netlify-cms/draft

#1768 Update Blog “okta-sso-integration-for-green-lake-and-aruba-central”
  content/blog/okta-sso-integration-for-green-lake-and-aruba-central.md
Labels: netlify-cms/draft
