Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2023-01, with the labels that each got.

#1635 Create Blog “getting-started-with-the-hpe-greenlake-compute-ops-management-api-in-just-3mn”
  content/blog/getting-started-with-the-hpe-greenlake-compute-ops-management-api-in-just-3mn.md
  static/img/apicalls.png
  static/img/postman_-software-.png
  static/img/stopwatch1.jpg
  static/img/stopwatch2.jpg
Labels: netlify-cms/pending_review

#1641 Update Blog “greenlake-platform-infrastructure-monitoring-with-apache-skywalking”
  content/blog/greenlake-platform-infrastructure-monitoring-with-apache-skywalking.md
Labels: netlify-cms/pending_publish

#1646 Create Blog “announcing-chapel-1-29-0”
  content/blog/announcing-chapel-1-29-0.md
Labels: netlify-cms/pending_publish

#1648 Update Blog “deploy-stateful-mongodb-application-on-kubernetes-clusters-in-hpe-greenlake-for-containers-1”
  content/blog/deploy-stateful-mongodb-application-on-kubernetes-clusters-in-hpe-greenlake-for-containers-1.md
Labels: netlify-cms/draft

#1649 Update Blog “how-to-set-up-an-automation-pipeline-to-view-historical-trend-data-of-clusters-with-hpe-greenlake-for-containers”
  content/blog/how-to-set-up-an-automation-pipeline-to-view-historical-trend-data-of-clusters-with-hpe-greenlake-for-containers.md
Labels: netlify-cms/draft

#1650 Update Blog “create-a-general-purpose-kubeconfig-file-in-hpe-greenlake-for-containers”
  content/blog/create-a-general-purpose-kubeconfig-file-in-hpe-greenlake-for-containers.md
Labels: netlify-cms/draft

#1651 Update Blog “how-to-set-up-credentials-to-authenticate-container-registry-in-hpe-greenlake-for-containers”
  content/blog/how-to-set-up-credentials-to-authenticate-container-registry-in-hpe-greenlake-for-containers.md
Labels: netlify-cms/draft

#1652 Update Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform”
  content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform.md
Labels: netlify-cms/draft

#1653 Update Blog “infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2”
  content/blog/infrastructure-as-code-on-hpe-greenlake-using-terraform-–-part-2.md
Labels: netlify-cms/draft

#1654 Update Blog “how-to-create-a-virtual-network-in-hpe-greenlake-for-private-cloud”
  content/blog/how-to-create-a-virtual-network-in-hpe-greenlake-for-private-cloud.md
Labels: netlify-cms/draft

#1655 Update Blog “how-to-integrate-chef-automation-with-hpe-greenlake-for-private-cloud”
  content/blog/how-to-integrate-chef-automation-with-hpe-greenlake-for-private-cloud.md
Labels: netlify-cms/draft

#1656 Update Blog “how-to-set-and-enforce-tagging-policies-in-hpe-greenlake-for-private-clo”
  content/blog/how-to-set-and-enforce-tagging-policies-in-hpe-greenlake-for-private-clo.md
Labels: netlify-cms/draft

#1657 Update Blog “how-to-provision-hpe-greenlake-private-cloud-resources-from-servicenow-service-catalog”
  content/blog/how-to-provision-hpe-greenlake-private-cloud-resources-from-servicenow-service-catalog.md
Labels: netlify-cms/draft

#1659 Update Blog “curate-and-expose-service-catalog-items-using-hpe-greenlake-for-private-cloud”
  content/blog/curate-and-expose-service-catalog-items-using-hpe-greenlake-for-private-cloud.md
Labels: netlify-cms/draft

#1628 Create Events “galadriel-an-alternative-approach-to-spire-federation”
  content/event/galadriel-an-alternative-approach-to-spire-federation.md
Labels: netlify-cms/pending_review

#1664 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1665 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#1667 Update Hackshack Home Cards “hackshackhome-5”
  content/hackshackhome/hackshackhome-5.md
Labels: netlify-cms/draft

#1629 Create Hackshack Home Cards “hackshackhome-7”
  content/hackshackhome/hackshackhome-7.md
Labels: netlify-cms/pending_review

#1668 Update Blog “understanding-hpe-greenlake-identity-access-management”
  content/blog/understanding-hpe-greenlake-identity-access-management.md
Labels: netlify-cms/pending_review

#1669 Create Blog “intro-to-core-api-part-1-integer-incrementing”
  content/blog/intro-to-core-api-part-1-integer-incrementing.md
  static/img/isha-determined-ai.png
  static/img/isha.jpeg
Labels: netlify-cms/pending_publish

#1671 Update Blog “monitor-application-performance-across-hybrid-cloud-environment-using-apache-skywalking-and-service-mesh”
  content/blog/monitor-application-performance-across-hybrid-cloud-environment-using-apache-skywalking-and-service-mesh.md
Labels: netlify-cms/draft

#1672 Update Hackshack Home Cards “hackshackhome-6”
  content/hackshackhome/hackshackhome-6.md
Labels: netlify-cms/pending_review

#1675 Update Campaign “ezmeral-early-access-program”
  content/campaign/ezmeral-early-access-program.md
Labels: netlify-cms/pending_review

#1674 Update Events “hpe-greenlake-for-data-fabric”
  content/event/hpe-greenlake-for-data-fabric.md
Labels: netlify-cms/pending_review

#1673 Update Events “hpe-ezmeral-unified-analytics”
  content/event/hpe-ezmeral-unified-analytics.md
Labels: netlify-cms/pending_review

#1677 Update Hackshack Home Cards “hackshackhome-4”
  content/hackshackhome/hackshackhome-4.md
Labels: netlify-cms/draft

#1678 Create Hackshack Home Cards “hackshackhome-8”
  content/hackshackhome/hackshackhome-8.md
Labels: netlify-cms/pending_review

#1676 Create Events “accelerating-scientific-research-through-high-performance-computing-democratization”
  content/event/accelerating-scientific-research-through-high-performance-computing-democratization.md
Labels: netlify-cms/pending_review

#1679 Create Events “extraordinary-claims-require-extraordinary-engineering-and-tamo-isn’t-an-option”
  content/event/extraordinary-claims-require-extraordinary-engineering-and-tamo-isn’t-an-option.md
Labels: netlify-cms/pending_review

#1683 Update Skillup “skillup”
  content/skillup/skillup.md
Labels: netlify-cms/draft

#1603 Create Blog “willing-to-build-up-your-own-workshops-on-demand-infrastructure”
  content/blog/willing-to-build-up-your-own-workshops-on-demand-infrastructure.md
  static/img/howto-wod-10.png
  static/img/howto-wod-2.png
  static/img/howto-wod-3.png
  static/img/howto-wod-5.png
  static/img/howto-wod-6.png
  static/img/wod-osrb1.png
Labels: netlify-cms/pending_publish

#1686 Update Blog “kubernetes-clusters-as-code-part1”
  content/blog/kubernetes-clusters-as-code-part1.md
Labels: netlify-cms/draft

#1688 Update Blog “scale-kubernetes-cluster-using-hpe-greenlake-terraform-provider”
  content/blog/scale-kubernetes-cluster-using-hpe-greenlake-terraform-provider.md
Labels: netlify-cms/draft

#1687 Update Blog “kubernetes-cluster-as-code-part-2”
  content/blog/kubernetes-cluster-as-code-part-2.md
Labels: netlify-cms/draft

#1690 Update Campaign “ezmeral-early-access-program”
  content/campaign/ezmeral-early-access-program.md
Labels: netlify-cms/draft

#1689 Update Events “hpe-ezmeral-unified-analytics”
  content/event/hpe-ezmeral-unified-analytics.md
Labels: netlify-cms/draft

#1622 Create Blog “hpe-joins-the-linux-foundation’s-spdx-workgroup-as-an-spdx-supporter”
  content/blog/hpe-joins-the-linux-foundation’s-spdx-workgroup-as-an-spdx-supporter.md
Labels: netlify-cms/pending_review

#1685 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1694 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#1696 Update Hackshack Home Cards “hackshackhome-4”
  content/hackshackhome/hackshackhome-4.md
Labels: netlify-cms/draft

#1695 Update Events “hpe-greenlake-and-infrastructure-as-code-iac”
  content/event/hpe-greenlake-and-infrastructure-as-code-iac.md
Labels: netlify-cms/draft

#1693 Update Campaign “ezmeral-early-access-program”
  content/campaign/ezmeral-early-access-program.md
Labels: netlify-cms/draft

#1692 Update Events “hpe-greenlake-for-data-fabric”
  content/event/hpe-greenlake-for-data-fabric.md
Labels: netlify-cms/draft

#1697 Update Hackshack Home Cards “hackshackhome-7”
  content/hackshackhome/hackshackhome-7.md
Labels: netlify-cms/draft

#1698 Update Hackshack Home Cards “hackshackhome-8”
  content/hackshackhome/hackshackhome-8.md
Labels: netlify-cms/draft

#1680 Create Hackshack Home Cards “hackshackhome-9”
  content/hackshackhome/hackshackhome-9.md
Labels: netlify-cms/draft

#1701 Update Blog “call-for-hpe-ezmeral-unified-analytics-beta-testers”
  content/blog/call-for-hpe-ezmeral-unified-analytics-beta-testers.md
Labels: netlify-cms/draft

#1702 Update Blog “hpe-ezmeral-early-access-gives-developers-hands-on-experience-with-the-new-hpe-greenlake-for-data-fabric”
  content/blog/hpe-ezmeral-early-access-gives-developers-hands-on-experience-with-the-new-hpe-greenlake-for-data-fabric.md
Labels: netlify-cms/draft

#1684 Create Blog “living-the-open-source-culture-at-hpe”
  content/blog/living-the-open-source-culture-at-hpe.md
  static/img/riapic.jpg
Labels: netlify-cms/pending_publish

#1704 Update Blog “hpe-ezmeral-early-access-gives-developers-hands-on-experience-with-the-new-hpe-greenlake-for-data-fabric”
  content/blog/hpe-ezmeral-early-access-gives-developers-hands-on-experience-with-the-new-hpe-greenlake-for-data-fabric.md
Labels: netlify-cms/draft

#1705 Update Blog “willing-to-build-up-your-own-workshops-on-demand-infrastructure”
  content/blog/willing-to-build-up-your-own-workshops-on-demand-infrastructure.md
Labels: netlify-cms/draft

#1706 Update Blog “call-for-hpe-ezmeral-unified-analytics-beta-testers”
  content/blog/call-for-hpe-ezmeral-unified-analytics-beta-testers.md
Labels: netlify-cms/draft

#1707 Update Blog “developing-an-open-source-metadata-framework-to-enhance-the-ml-pipeline-experience”
  content/blog/developing-an-open-source-metadata-framework-to-enhance-the-ml-pipeline-experience.md
Labels: netlify-cms/draft

#1708 Update Blog “spiffe-spire-graduates-enabling-greater-security-solutions”
  content/blog/spiffe-spire-graduates-enabling-greater-security-solutions.md
Labels: netlify-cms/draft

#1709 Update Blog “hpe-joins-the-linux-foundation’s-spdx-workgroup-as-an-spdx-supporter”
  content/blog/hpe-joins-the-linux-foundation’s-spdx-workgroup-as-an-spdx-supporter.md
Labels: netlify-cms/draft

#1710 Update Blog “how-to-monitor-hpe-compute-ops-management”
  content/blog/how-to-monitor-hpe-compute-ops-management.md
Labels: netlify-cms/draft

#1711 Update Blog “galadriel-a-spire-federation-alternative”
  content/blog/galadriel-a-spire-federation-alternative.md
Labels: netlify-cms/draft

#1713 Update Blog “living-the-open-source-culture-at-hpe”
  content/blog/living-the-open-source-culture-at-hpe.md
Labels: netlify-cms/draft

#1703 Update GreenLake “aruba-central/home”
  content/greenlake/aruba-central/home.md
Labels: netlify-cms/pending_review

#1714 Update Blog “developing-an-open-source-metadata-framework-to-enhance-the-ml-pipeline-experience”
  content/blog/developing-an-open-source-metadata-framework-to-enhance-the-ml-pipeline-experience.md
Labels: netlify-cms/draft

#1715 Update Blog “greenlake-platform-infrastructure-monitoring-with-apache-skywalking”
  content/blog/greenlake-platform-infrastructure-monitoring-with-apache-skywalking.md
Labels: netlify-cms/draft

#1717 Update Blog “willing-to-build-up-your-own-workshops-on-demand-infrastructure”
  content/blog/willing-to-build-up-your-own-workshops-on-demand-infrastructure.md
Labels: netlify-cms/draft

#1718 Update Home Panel “07-spiffe-spire-graduates-enabling-greater-security-solutions”
  content/home/07-spiffe-spire-graduates-enabling-greater-security-solutions.md
  static/img/frederic-passeron-hpedev-192.jpg
Labels: netlify-cms/draft

#1719 Update Blog “using-raw-block-and-ephemeral-inline-volumes-on-kubernetes”
  content/blog/using-raw-block-and-ephemeral-inline-volumes-on-kubernetes.md
Labels: netlify-cms/draft

#1720 Update Blog “introducing-an-nfs-server-provisioner-for-the-hpe-csi-driver-for-kuberne”
  content/blog/introducing-an-nfs-server-provisioner-for-the-hpe-csi-driver-for-kuberne.md
Labels: netlify-cms/draft

#1721 Update Blog “hpe-csi-driver-for-kubernetes-snapshots-clones-and-volume-expansion”
  content/blog/hpe-csi-driver-for-kubernetes-snapshots-clones-and-volume-expansion.md
Labels: netlify-cms/draft

#1722 Update Blog “host-based-volume-encryption-with-hpe-csi-driver-for-kubernetes”
  content/blog/host-based-volume-encryption-with-hpe-csi-driver-for-kubernetes.md
Labels: netlify-cms/draft

#1723 Update Blog “synchronized-volume-snapshots-for-distributed-workloads-on-kubernetes”
  content/blog/synchronized-volume-snapshots-for-distributed-workloads-on-kubernetes.md
Labels: netlify-cms/draft

#1724 Update Blog “willing-to-build-up-your-own-workshops-on-demand-infrastructure”
  content/blog/willing-to-build-up-your-own-workshops-on-demand-infrastructure.md
Labels: netlify-cms/draft
