Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2023-10, with the labels that each got.

#2098 Update Blog “hpe-greenlake-for-private-cloud-enterprise-glpce-deploying-and-scaling-traditional-applications”
  content/blog/hpe-greenlake-for-private-cloud-enterprise-glpce-deploying-and-scaling-traditional-applications.md
Labels: netlify-cms/pending_review

#2099 Update Blog “the-ilorest-tool-in-conjunction-with-directly-attached-and-controller-connected-drives”
  content/blog/the-ilorest-tool-in-conjunction-with-directly-attached-and-controller-connected-drives.md
Labels: netlify-cms/pending_review

#2100 Update Blog “streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics”
  content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
Labels: netlify-cms/pending_review

#2101 Update Blog “streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics”
  content/blog/streamline-and-optimize-ml-workflows-with-hpe-ezmeral-unified-analytics.md
Labels: netlify-cms/pending_review

#2103 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2104 Update Hackshack Home Cards “hackshackhome-18”
  content/hackshackhome/hackshackhome-18.md
Labels: netlify-cms/pending_review

#2111 Update Blog “announcing-chapel-1-32”
  content/blog/announcing-chapel-1-32.md
Labels: netlify-cms/draft

#2112 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2113 Update Events “devops-alert-tool-sprawl-complexity-burnout-help”
  content/event/devops-alert-tool-sprawl-complexity-burnout-help.md
Labels: netlify-cms/draft

#2106 Create Events “the-open-source-advantage-exploring-machine-learning-through-thought-leadership”
  content/event/the-open-source-advantage-exploring-machine-learning-through-thought-leadership.md
Labels: netlify-cms/pending_review

#2105 Create Hackshack Home Cards “hackshackhome-21”
  content/hackshackhome/hackshackhome-21.md
Labels: netlify-cms/pending_review

#2115 Update Events “devops-alert-tool-sprawl-complexity-burnout-help-1”
  content/event/devops-alert-tool-sprawl-complexity-burnout-help-1.md
Labels: netlify-cms/draft

#2122 Update Blog “sivayanama-simplifying-open-api-specification-with-reusable-common-data-models”
  content/blog/sivayanama-simplifying-open-api-specification-with-reusable-common-data-models.md
Labels: netlify-cms/draft

#2123 Create Events “the-last-mile-of-the-self-hosted-llm”
  content/event/the-last-mile-of-the-self-hosted-llm.md
Labels: netlify-cms/pending_review

#2132 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#2135 Update Events “the-open-source-advantage-exploring-machine-learning-through-thought-leadership”
  content/event/the-open-source-advantage-exploring-machine-learning-through-thought-leadership.md
Labels: netlify-cms/pending_review

#2130 Create Hackshack Home Cards “hackshackhome-22”
  content/hackshackhome/hackshackhome-22.md
Labels: netlify-cms/pending_publish

#2137 Update Hackshack Home Cards “hackshackhome-22”
  content/hackshackhome/hackshackhome-22.md
Labels: netlify-cms/pending_publish

#2138 Update Events “devops-alert-tool-sprawl-complexity-burnout-help”
  content/event/devops-alert-tool-sprawl-complexity-burnout-help.md
Labels: netlify-cms/pending_review

#2133 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#2140 Create Events “automated-continuous-deployment-of-container-based-applications-onto-hpe-greenlake-for-private-cloud-enterprise”
  content/event/automated-continuous-deployment-of-container-based-applications-onto-hpe-greenlake-for-private-cloud-enterprise.md
Labels: netlify-cms/pending_review

#2139 Create Hackshack Home Cards “hackshackhome-23”
  content/hackshackhome/hackshackhome-23.md
Labels: netlify-cms/pending_review

#2141 Update Blog “hpe-greenlake-for-private-cloud-enterprise-scaling-and-orchestrating-modern-applications-for-the-enterprise”
  content/blog/hpe-greenlake-for-private-cloud-enterprise-scaling-and-orchestrating-modern-applications-for-the-enterprise.md
Labels: netlify-cms/pending_review

#2143 Update Events “the-open-source-advantage-exploring-machine-learning-through-thought-leadership”
  content/event/the-open-source-advantage-exploring-machine-learning-through-thought-leadership.md
Labels: netlify-cms/pending_review

#2142 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#2144 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#2145 Update Events “devops-alert-tool-sprawl-complexity-burnout-help-1”
  content/event/devops-alert-tool-sprawl-complexity-burnout-help-1.md
Labels: netlify-cms/pending_review

#2146 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2147 Update Events “devops-alert-tool-sprawl-complexity-burnout-help-1”
  content/event/devops-alert-tool-sprawl-complexity-burnout-help-1.md
Labels: netlify-cms/draft

#2149 Update Hackshack Home Cards “hackshackhome-20”
  content/hackshackhome/hackshackhome-20.md
Labels: netlify-cms/pending_publish
