Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2023-07, with the labels that each got.

#1991 Update Blog “new-for-hpe-discover-2023-hack-shack-serves-as-home-base-for-hpe’s-office-of-the-cto”
  content/blog/new-for-hpe-discover-2023-hack-shack-serves-as-home-base-for-hpe’s-office-of-the-cto.md
Labels: netlify-cms/draft

#1992 Update Home Panel “07-spiffe-spire-graduates-enabling-greater-security-solutions”
  content/home/07-spiffe-spire-graduates-enabling-greater-security-solutions.md
  static/img/isha-192x192.png
Labels: netlify-cms/draft

#1867 Create GreenLake “hpe-greenlake-for-private-cloud-enterprise/home”
  content/greenlake/hpe-greenlake-for-private-cloud-enterprise/home.md
  static/img/greenlake.svg
  static/img/hpegl4pce-api.png
  static/img/hpegl4pce-architecture-v2.png
  static/img/hpegl4pce-architecture.png
  static/img/hpegl4pce-cloud-shell.png
  static/img/hpegl4pce-devops.png
Labels: netlify-cms/pending_review

#1996 Update Platforms “ilo-restful-api/home”
  content/platform/ilo-restful-api/home.md
Labels: netlify-cms/pending_review

#1997 Update Blog “hpe-firmware-updates-part-1-file-types-and-smart-components”
  content/blog/hpe-firmware-updates-part-1-file-types-and-smart-components.md
  static/img/8-updatablebyarray.png
Labels: netlify-cms/pending_review

#1780 Create Blog “open-sourcing-workshops-on-demand-part4-managing-the-backend”
  content/blog/open-sourcing-workshops-on-demand-part4-managing-the-backend.md
Labels: netlify-cms/pending_review

#1998 Update Blog “hpe-firmware-updates-part-2-interaction-in-operating-modes”
  content/blog/hpe-firmware-updates-part-2-interaction-in-operating-modes.md
Labels: netlify-cms/pending_publish

#1999 Update Blog “hpe-firmware-updates-part-3-the-redfish-update-service”
  content/blog/hpe-firmware-updates-part-3-the-redfish-update-service.md
  static/img/12_taskstates.png
  static/img/27_commandvalues.png
  static/img/9_oemhpestates.png
Labels: netlify-cms/pending_review

#2000 Update Blog “getting-started-with-ilo-restful-api-redfish-api-conformance”
  content/blog/getting-started-with-ilo-restful-api-redfish-api-conformance.md
Labels: netlify-cms/pending_review

#2001 Update Blog “getting-started-with-the-redfish-api-part-2”
  content/blog/getting-started-with-the-redfish-api-part-2.md
Labels: netlify-cms/pending_review

#2004 Update Blog “master-the-redfish-server-states-to-improve-your-monitoring-and-manageme”
  content/blog/master-the-redfish-server-states-to-improve-your-monitoring-and-manageme.md
Labels: netlify-cms/pending_review

#2003 Create Blog “office-of-the-cto-announces-hiring-at-new-center-of-excellence-in-galway”
  content/blog/office-of-the-cto-announces-hiring-at-new-center-of-excellence-in-galway.md
Labels: netlify-cms/pending_review

#2006 Update Blog “managing-ilo-sessions-with-redfish”
  content/blog/managing-ilo-sessions-with-redfish.md
Labels: netlify-cms/pending_review

#2007 Update Blog “overview-of-the-platform-level-data-model-for-redfish®-device-enablement-standard”
  content/blog/overview-of-the-platform-level-data-model-for-redfish®-device-enablement-standard.md
Labels: netlify-cms/pending_publish

#2008 Update Blog “setting-bios-and-storage-controller-properties-with-redfish”
  content/blog/setting-bios-and-storage-controller-properties-with-redfish.md
Labels: netlify-cms/pending_review

#2009 Update Blog “storage-management-with-redfish”
  content/blog/storage-management-with-redfish.md
Labels: netlify-cms/pending_review

#2010 Update Home Panel “07-spiffe-spire-graduates-enabling-greater-security-solutions”
  content/home/07-spiffe-spire-graduates-enabling-greater-security-solutions.md
Labels: netlify-cms/pending_review

#2011 Update Blog “office-of-the-cto-announces-hiring-at-new-center-of-excellence-in-galway”
  content/blog/office-of-the-cto-announces-hiring-at-new-center-of-excellence-in-galway.md
Labels: netlify-cms/pending_review

#2012 Update Blog “end-to-end-easy-to-use-pipeline-for-training-a-model-on-medmnist-v2-using-hpe-machine-learning-development-environment-flask”
  content/blog/end-to-end-easy-to-use-pipeline-for-training-a-model-on-medmnist-v2-using-hpe-machine-learning-development-environment-flask.md
Labels: netlify-cms/pending_review

#2013 Update Blog “galadriel-a-spire-federation-alternative”
  content/blog/galadriel-a-spire-federation-alternative.md
Labels: netlify-cms/pending_review

#2014 Update Blog “open-sourcing-workshops-on-demand-part4-managing-the-backend”
  content/blog/open-sourcing-workshops-on-demand-part4-managing-the-backend.md
Labels: netlify-cms/pending_review

#2015 Update Blog “willing-to-build-up-your-own-workshops-on-demand-infrastructure”
  content/blog/willing-to-build-up-your-own-workshops-on-demand-infrastructure.md
Labels: netlify-cms/pending_review

#2016 Update Blog “production-ready-object-detection-model-training-workflow-with-hpe-machine-learning-development-environment”
  content/blog/production-ready-object-detection-model-training-workflow-with-hpe-machine-learning-development-environment.md
Labels: netlify-cms/draft

#2017 Update Blog “developing-an-open-source-metadata-framework-to-enhance-the-ml-pipeline-experience”
  content/blog/developing-an-open-source-metadata-framework-to-enhance-the-ml-pipeline-experience.md
Labels: netlify-cms/draft

#2018 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2020 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2022 Update Events “observability-in-action”
  content/event/observability-in-action.md
Labels: netlify-cms/pending_review

#2021 Update Hackshack Home Cards “hackshackhome-17”
  content/hackshackhome/hackshackhome-17.md
Labels: netlify-cms/pending_review
