Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2024-05, with the labels that each got.

#2519 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2520 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2523 Update Blog “introducing-chapelcon-24-the-chapel-event-of-the-year”
  content/blog/introducing-chapelcon-24-the-chapel-event-of-the-year.md
Labels: netlify-cms/pending_review

#2522 Update Blog “supercharged-chapel-editor-support”
  content/blog/supercharged-chapel-editor-support.md
Labels: netlify-cms/pending_review

#2524 Update Blog “curling-through-the-oneview-api”
  content/blog/curling-through-the-oneview-api.md
Labels: netlify-cms/draft

#2500 Create Blog “bulk-onboarding-of-users-in-hpe-greenlake-edge-to-cloud-platform”
  content/blog/bulk-onboarding-of-users-in-hpe-greenlake-edge-to-cloud-platform.md
Labels: netlify-cms/draft

#2529 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace.md
Labels: netlify-cms/pending_publish

#2535 Update Blog “generic-linear-multistep-method-evaluator-using-chapel”
  content/blog/generic-linear-multistep-method-evaluator-using-chapel.md
Labels: netlify-cms/draft

#2541 Update Events “the-family-of-hpe-greenlake-data-services-cloud-console-dscc-apis-–-putting-it-all-together”
  content/event/the-family-of-hpe-greenlake-data-services-cloud-console-dscc-apis-–-putting-it-all-together.md
Labels: netlify-cms/pending_publish

#2540 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_publish

#2542 Update GreenLake “data-services-on-the-hpe-greenlake-platform/home”
  content/greenlake/data-services-on-the-hpe-greenlake-platform/home.md
Labels: netlify-cms/pending_publish

#2543 Update Blog “ilorest-as-a-pypi-package”
  content/blog/ilorest-as-a-pypi-package.md
Labels: netlify-cms/pending_publish

#2544 Update Blog “getting-started-with-the-hpe-data-services-cloud-console-powershell-sdk”
  content/blog/getting-started-with-the-hpe-data-services-cloud-console-powershell-sdk.md
Labels: netlify-cms/draft

#2545 Update Blog “api-console-for-data-services-cloud-console”
  content/blog/api-console-for-data-services-cloud-console.md
Labels: netlify-cms/pending_publish

#2547 Update GreenLake “data-services-cloud-console/home”
  content/greenlake/data-services-cloud-console/home.md
Labels: netlify-cms/pending_review

#2548 Update GreenLake “data-services-on-the-hpe-greenlake-platform/home”
  content/greenlake/data-services-on-the-hpe-greenlake-platform/home.md
Labels: netlify-cms/draft

#2549 Update Events “the-family-of-hpe-greenlake-data-services-cloud-console-dscc-apis-–-putting-it-all-together”
  content/event/the-family-of-hpe-greenlake-data-services-cloud-console-dscc-apis-–-putting-it-all-together.md
Labels: netlify-cms/draft

#2550 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2556 Update Blog “ilorest-as-a-pypi-package”
  content/blog/ilorest-as-a-pypi-package.md
Labels: netlify-cms/pending_publish

#2557 Update Blog “title-demystifying-machine-learning-at-scale-hpe-ezmeral-unified-analytics-in-action”
  content/blog/title-demystifying-machine-learning-at-scale-hpe-ezmeral-unified-analytics-in-action.md
Labels: netlify-cms/pending_publish

#2558 Create Blog “do-not-miss-the-innovation-campus-at-discover-2024”
  content/blog/do-not-miss-the-innovation-campus-at-discover-2024.md
Labels: netlify-cms/draft

#2560 Update Blog “converting-hpe-greenlake-api-specifications-in-oas-3-1-using-openapi-tools”
  content/blog/converting-hpe-greenlake-api-specifications-in-oas-3-1-using-openapi-tools.md
Labels: netlify-cms/pending_publish

#2559 Update Blog “overview-of-the-platform-level-data-model-for-redfish®-device-enablement-standard”
  content/blog/overview-of-the-platform-level-data-model-for-redfish®-device-enablement-standard.md
Labels: netlify-cms/pending_publish

#2554 Create Platforms “dragonhpc/home”
  content/blog/3-ways-a-data-fabric-enables-a-data-first-approach.md
  content/opensource/dragonhpc.md
  content/platform/dragonhpc/home.md
  gatsby-config.js
  gatsby-node.js
  src/components/BlogTabs/index.js
  src/components/Header/index.js
  src/pages/blog/index.js
  static/img/platforms/dragon_deployment.jpg
Labels: netlify-cms/draft

#2563 Update Platforms “dragonhpc/home”
  content/platform/dragonhpc/home.md
Labels: netlify-cms/draft

#2566 Update Blog “getting-started-with-private-cloud-business-edition-apis”
  content/blog/getting-started-with-private-cloud-business-edition-apis.md
Labels: netlify-cms/draft
