Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2024-11, with the labels that each got.

#2762 Update Blog “getting-started-with-hpe-greenlake-api-for-backup-and-recovery”
  content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
Labels: netlify-cms/pending_publish

#2763 Update Blog “master-the-redfish-server-states-to-improve-your-monitoring-and-manageme”
  content/blog/master-the-redfish-server-states-to-improve-your-monitoring-and-manageme.md
Labels: netlify-cms/pending_publish

#2764 Create Blog “managing-morpheus-plugins-via-rest-api”
  content/blog/managing-morpheus-plugins-via-rest-api.md
  static/img/morpheus-logo-192x187.png
Labels: netlify-cms/pending_publish

#2765 Create Blog “morpheus-extensibility-with-plugins”
  content/blog/morpheus-extensibility-with-plugins.md
Labels: netlify-cms/pending_publish

#2766 Create Blog “morpheus-terraform-profiles”
  content/blog/morpheus-terraform-profiles.md
Labels: netlify-cms/pending_publish

#2768 Update Blog “hpe-greenlake-test-drive-on-your-mark-get-set-go”
  content/blog/hpe-greenlake-test-drive-on-your-mark-get-set-go.md
Labels: netlify-cms/pending_publish

#2769 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2773 Update Campaign “get-real-with-ai-–-jam-series”
  content/campaign/get-real-with-ai-–-jam-series.md
Labels: netlify-cms/draft

#2775 Create Blog “getting-started-with-retrieval-augmented-generation-rag”
  content/blog/getting-started-with-retrieval-augmented-generation-rag.md
  static/img/pcai.webp
  static/img/ragblog-1.jpg
  static/img/ragblog2.jpg
  static/img/ragblog3.jpg
  static/img/ragblog4.jpg
  static/img/ragblog5.jpg
  static/img/ragblog6.jpg
Labels: netlify-cms/pending_review

#2778 Update Home Panel “07-spiffe-spire-graduates-enabling-greater-security-solutions”
  content/home/07-spiffe-spire-graduates-enabling-greater-security-solutions.md
Labels: netlify-cms/pending_publish

#2780 Update Blog “small-language-models-the-next-frontier-with-private-cloud-ai”
  content/blog/small-language-models-the-next-frontier-with-private-cloud-ai.md
Labels: netlify-cms/pending_publish

#2782 Update Blog “implementing-your-ai-breakthroughs-effectively-–-the-infrastructure-to-your-a-i”
  content/blog/implementing-your-ai-breakthroughs-effectively-–-the-infrastructure-to-your-a-i.md
Labels: netlify-cms/pending_publish

#2784 Update Blog “hpe-sustainability-insight-center-api-at-a-glance”
  content/blog/hpe-sustainability-insight-center-api-at-a-glance.md
Labels: netlify-cms/pending_publish

#2785 Update Blog “getting-started-with-retrieval-augmented-generation-rag”
  content/blog/getting-started-with-retrieval-augmented-generation-rag.md
Labels: netlify-cms/pending_publish

#2786 Create Blog “developer-assistance-for-those-looking-to-work-with-ampere-arm-processors”
  content/blog/developer-assistance-for-those-looking-to-work-with-ampere-arm-processors.md
Labels: netlify-cms/pending_publish

#2791 Update Events “how-to-fix-your-biggest-security-hole”
  content/event/how-to-fix-your-biggest-security-hole.md
Labels: netlify-cms/pending_publish

#2793 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#2792 Update Events “nvidia-nim-agents-blueprints-do-your-own-ai-multimodal-pdf-data-extraction-101”
  content/event/nvidia-nim-agents-blueprints-do-your-own-ai-multimodal-pdf-data-extraction-101.md
Labels: netlify-cms/pending_publish

#2789 Update Hackshack Home Cards “hackshackhome-43”
  content/hackshackhome/hackshackhome-43.md
Labels: netlify-cms/pending_publish

#2794 Update Campaign “get-real-with-ai-–-jam-series”
  content/campaign/get-real-with-ai-–-jam-series.md
Labels: netlify-cms/draft

#2795 Update Campaign “get-real-with-ai-–-jam-series”
  content/campaign/get-real-with-ai-–-jam-series.md
Labels: netlify-cms/pending_publish

#2796 Update Events “implementing-your-ai-breakthroughs-effectively-the-infrastructure-to-your-ai”
  content/event/implementing-your-ai-breakthroughs-effectively-the-infrastructure-to-your-ai.md
Labels: netlify-cms/pending_publish
