Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2024-12, with the labels that each got.

#2797 Create Platforms “hpe-opsramp/home”
  content/platform/hpe-opsramp/home.md
  static/img/platforms/logo-opsramp-192x99.png
Labels: netlify-cms/pending_review

#2798 Create Blog “the-schrödinger’s-cat-challenge-of-observing-cloud-native-applications”
  content/blog/the-schrödinger’s-cat-challenge-of-observing-cloud-native-applications.md
  static/img/logo-opsramp-192x99.png
Labels: netlify-cms/pending_publish

#2802 Update Platforms “hpe-opsramp/home”
  content/platform/hpe-opsramp/home.md
Labels: netlify-cms/pending_review

#2803 Update Platforms “morpheus/home”
  content/platform/morpheus/home.md
Labels: netlify-cms/pending_review

#2804 Update Platforms “ilo-restful-api/home”
  content/platform/ilo-restful-api/home.md
Labels: netlify-cms/pending_review

#2805 Update Platforms “zerto/home”
  content/platform/zerto/home.md
Labels: netlify-cms/pending_review

#2808 Update Platforms “project-data-map/home”
  content/platform/project-data-map/home.md
Labels: netlify-cms/pending_review

#2811 Update Platforms “zerto/home”
  content/platform/zerto/home.md
Labels: netlify-cms/pending_publish

#2812 Update Platforms “swarm-learning/home”
  content/platform/swarm-learning/home.md
Labels: netlify-cms/pending_review

#2814 Update GreenLake “hpe-greenlake-for-private-cloud-enterprise/home”
  content/greenlake/hpe-greenlake-for-private-cloud-enterprise/home.md
Labels: netlify-cms/pending_review

#2813 Update GreenLake “data-services-on-the-hpe-greenlake-platform/home”
  content/greenlake/data-services-on-the-hpe-greenlake-platform/home.md
Labels: netlify-cms/pending_review

#2815 Update Platforms “hpe-nonstop/home”
  content/platform/hpe-nonstop/home.md
Labels: netlify-cms/pending_review

#2817 Update Blog “getting-started-with-the-hpe-data-services-cloud-console-public-rest-api”
  content/blog/getting-started-with-the-hpe-data-services-cloud-console-public-rest-api.md
Labels: netlify-cms/draft

#2819 Update Blog “streamline-your-server-deployments-bare-metal-provisioning-with-hpe-compute-ops-management-and-ansible”
  content/blog/streamline-your-server-deployments-bare-metal-provisioning-with-hpe-compute-ops-management-and-ansible.md
Labels: netlify-cms/draft

#2818 Update Blog “why-devsecops-approach-is-key-to-mainstream-container-use”
  content/blog/why-devsecops-approach-is-key-to-mainstream-container-use.md
Labels: netlify-cms/draft

#2822 Update Blog “storage-management-with-redfish”
  content/blog/storage-management-with-redfish.md
Labels: netlify-cms/pending_review

#2824 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis.md
Labels: netlify-cms/pending_review

#2825 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace.md
Labels: netlify-cms/pending_review

#2826 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-3-tracking-activities-and-monitoring-health”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-3-tracking-activities-and-monitoring-health.md
Labels: netlify-cms/pending_review

#2787 Create Blog “use-redfish-and-ipv6-to-find-lost-servers”
  content/blog/use-redfish-and-ipv6-to-find-lost-servers.md
Labels: netlify-cms/pending_publish

#2827 Update Hackshack Home Cards “hackshackhome-44”
  content/hackshackhome/hackshackhome-44.md
Labels: netlify-cms/pending_review

#2831 Update GreenLake “hpe-greenlake-for-compute-ops-management/home”
  content/greenlake/hpe-greenlake-for-compute-ops-management/home.md
Labels: netlify-cms/pending_review

#2839 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#2838 Update Campaign “get-real-with-ai-–-jam-series”
  content/campaign/get-real-with-ai-–-jam-series.md
Labels: netlify-cms/pending_review

#2842 Update Events “how-to-fix-your-biggest-security-hole”
  content/event/how-to-fix-your-biggest-security-hole.md
Labels: netlify-cms/pending_publish

#2843 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#2836 Create Events “it-new-year-resolution-building-an-ethical-and-trustworthy-ai-system”
  content/event/it-new-year-resolution-building-an-ethical-and-trustworthy-ai-system.md
Labels: netlify-cms/pending_publish

#2834 Create Events “from-log-files-to-ai-insights-the-60-year-evolution-of-observability-and-aiops”
  content/event/from-log-files-to-ai-insights-the-60-year-evolution-of-observability-and-aiops.md
Labels: netlify-cms/pending_publish

#2829 Create Events “unleashing-ai-innovation-a-deep-dive-into-the-hpe-private-cloud-ai-software-stack”
  content/event/unleashing-ai-innovation-a-deep-dive-into-the-hpe-private-cloud-ai-software-stack.md
Labels: netlify-cms/pending_publish

#2830 Create Hackshack Home Cards “hackshackhome-45”
  content/hackshackhome/hackshackhome-45.md
Labels: netlify-cms/pending_publish

#2845 Update Hackshack Home Cards “hackshackhome-44”
  content/hackshackhome/hackshackhome-44.md
Labels: netlify-cms/pending_publish

#2846 Update Events “ll-mesh-–-democratizing-gen-ai”
  content/event/ll-mesh-–-democratizing-gen-ai.md
Labels: netlify-cms/pending_publish

#2851 Update Platforms “hpe-machine-learning-development-environment/home”
  content/platform/hpe-machine-learning-development-environment/home.md
Labels: netlify-cms/pending_publish

#2850 Update Platforms “determined-ai/home”
  content/platform/determined-ai/home.md
Labels: netlify-cms/pending_publish

#2852 Update Blog “hpe-greenlake-edge-to-cloud-platform-scripting-fundamentals”
  content/blog/hpe-greenlake-edge-to-cloud-platform-scripting-fundamentals.md
Labels: netlify-cms/pending_review
