Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2024-06, with the labels that each got.

#2567 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2568 Update Hackshack Home Cards “hackshackhome-34”
  content/hackshackhome/hackshackhome-34.md
Labels: netlify-cms/pending_review

#2569 Update Events “using-hpe-greenlake-for-red-hat-openshift-to-migrate-modernize-and-run-your-applications-smoothly”
  content/event/using-hpe-greenlake-for-red-hat-openshift-to-migrate-modernize-and-run-your-applications-smoothly.md
Labels: netlify-cms/pending_review

#2572 Update Blog “glc-scim-api-integration-with-okta-scim-adapter-1”
  content/blog/glc-scim-api-integration-with-okta-scim-adapter-1.md
Labels: netlify-cms/pending_review

#2573 Update Blog “title-demystifying-machine-learning-at-scale-hpe-ezmeral-unified-analytics-in-action”
  content/blog/title-demystifying-machine-learning-at-scale-hpe-ezmeral-unified-analytics-in-action.md
  static/img/demystifying-ml-kserve-img6.png
  static/img/demystifying-ml-mlflow-img5.png
  static/img/demystifying-ml-presto-img3.png
  static/img/demystifying-ml-spark-img2.png
  static/img/demystifying-ml-superset-img4.png
  static/img/demystifying-ml-unifiedanalytics-img1.png
Labels: netlify-cms/pending_review

#2575 Update Hackshack Home Cards “hackshackhome-35”
  content/hackshackhome/hackshackhome-35.md
Labels: netlify-cms/pending_review

#2576 Update Hackshack Home Cards “hackshackhome-36”
  content/hackshackhome/hackshackhome-36.md
Labels: netlify-cms/pending_review

#2578 Create Events “vendor-neutral-gpu-programming-in-chapel”
  content/event/vendor-neutral-gpu-programming-in-chapel.md
Labels: netlify-cms/pending_review

#2577 Create Hackshack Home Cards “hackshackhome-37”
  content/hackshackhome/hackshackhome-37.md
Labels: netlify-cms/pending_review

#2580 Update Hackshack Home Cards “hackshackhome-35”
  content/hackshackhome/hackshackhome-35.md
Labels: netlify-cms/draft

#2581 Update Events “how-digital-twins-help-companies-reach-their-sustainability-goals”
  content/event/how-digital-twins-help-companies-reach-their-sustainability-goals.md
Labels: netlify-cms/draft

#2585 Update Blog “overview-of-the-platform-level-data-model-for-redfish®-device-enablement-standard”
  content/blog/overview-of-the-platform-level-data-model-for-redfish®-device-enablement-standard.md
Labels: netlify-cms/pending_publish

#2584 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2587 Update Blog “hpe-greenlake-for-private-cloud-enterprise-mastering-cloud-migration-with-the-6rs-approach”
  content/blog/hpe-greenlake-for-private-cloud-enterprise-mastering-cloud-migration-with-the-6rs-approach.md
Labels: netlify-cms/pending_review

#2583 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#2589 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2593 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#2592 Update Events “how-digital-twins-help-companies-reach-their-sustainability-goals”
  content/event/how-digital-twins-help-companies-reach-their-sustainability-goals.md
Labels: netlify-cms/pending_review

#2594 Create Blog “announcements-at-hpe-discover-2024-accelerate-ai-adoption-and-offer-optionality”
  content/blog/announcements-at-hpe-discover-2024-accelerate-ai-adoption-and-offer-optionality.md
Labels: netlify-cms/pending_review

#2595 Update Hackshack Home Cards “hackshackhome-36”
  content/hackshackhome/hackshackhome-36.md
Labels: netlify-cms/pending_review

#2596 Update Events “implementing-centralized-key-management-in-hpe-greenlake-with-thales-ciphertrust”
  content/event/implementing-centralized-key-management-in-hpe-greenlake-with-thales-ciphertrust.md
Labels: netlify-cms/pending_review

#2599 Update Blog “announcing-chapel-2-1”
  content/blog/announcing-chapel-2-1.md
Labels: netlify-cms/pending_review
