Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2024-01, with the labels that each got.

#2252 Update Blog “mixtral-8x7b-that-may-pave-the-trend-to-adopt-the-mixture-of-experts-model”
  content/blog/mixtral-8x7b-that-may-pave-the-trend-to-adopt-the-mixture-of-experts-model.md
Labels: netlify-cms/pending_publish

#2256 Update Blog “determined-ai-weekly-update-6”
  content/blog/determined-ai-weekly-update-6.md
Labels: netlify-cms/pending_publish

#2260 Update Blog “introduction-to-gpu-programming-in-chapel”
  content/blog/introduction-to-gpu-programming-in-chapel.md
Labels: netlify-cms/draft

#2261 Create Events “opportunities-and-challenges-of-self-hosting-genai”
  content/event/opportunities-and-challenges-of-self-hosting-genai.md
  static/img/data-science-community-virtual-meet-up-2-asset.jpg
Labels: netlify-cms/pending_review

#2269 Update Blog “dark-mode-theming-in-grommet-how-to-set-up-and-apply-a-theme”
  content/blog/dark-mode-theming-in-grommet-how-to-set-up-and-apply-a-theme.md
Labels: netlify-cms/pending_publish

#2268 Update Blog “highly-available-nfs-workload-on-hpe-greenlake-for-private-cloud-enterprise-using-serviceguard-for-linux”
  content/blog/highly-available-nfs-workload-on-hpe-greenlake-for-private-cloud-enterprise-using-serviceguard-for-linux.md
Labels: netlify-cms/pending_publish

#2267 Update Blog “mixtral-8x7b-that-may-pave-the-trend-to-adopt-the-mixture-of-experts-model”
  content/blog/mixtral-8x7b-that-may-pave-the-trend-to-adopt-the-mixture-of-experts-model.md
Labels: netlify-cms/pending_publish

#2266 Update Blog “end-to-end-easy-to-use-pipeline-for-training-a-model-on-medmnist-v2-using-hpe-machine-learning-development-environment-flask”
  content/blog/end-to-end-easy-to-use-pipeline-for-training-a-model-on-medmnist-v2-using-hpe-machine-learning-development-environment-flask.md
Labels: netlify-cms/pending_publish

#2265 Update Blog “open-sourcing-packetrusher-a-5g-core-performance-tester”
  content/blog/open-sourcing-packetrusher-a-5g-core-performance-tester.md
Labels: netlify-cms/pending_publish

#2264 Update Blog “open-sourcing-workshops-on-demand-part4-managing-the-backend”
  content/blog/open-sourcing-workshops-on-demand-part4-managing-the-backend.md
Labels: netlify-cms/pending_publish

#2263 Update Blog “introduction-to-gpu-programming-in-chapel”
  content/blog/introduction-to-gpu-programming-in-chapel.md
Labels: netlify-cms/pending_publish

#2262 Update Blog “help-us-prioritize-features-for-future-releases-of-chapel”
  content/blog/help-us-prioritize-features-for-future-releases-of-chapel.md
Labels: netlify-cms/pending_publish

#2274 Update Blog “how-multimodal-llms-work”
  content/blog/how-multimodal-llms-work.md
Labels: netlify-cms/draft

#2282 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2283 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2285 Update Hackshack Home Cards “hackshackhome-28”
  content/hackshackhome/hackshackhome-28.md
Labels: netlify-cms/draft

#2286 Update Events “using-hpe-greenlake-edge-to-cloud-platform-to-build-a-private-cloud”
  content/event/using-hpe-greenlake-edge-to-cloud-platform-to-build-a-private-cloud.md
Labels: netlify-cms/draft

#2288 Update Events “apis-for-hpe-greenlake-for-block-storage-and-next-gen-platforms”
  content/event/apis-for-hpe-greenlake-for-block-storage-and-next-gen-platforms.md
Labels: netlify-cms/draft

#2270 Create Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis.md
  static/img/blog-part1-bearertoken-testscript-image2.png
  static/img/blog-part1-collection-api-call-authorization-image4.png
  static/img/blog-part1-collection-level-authorization-image3.png
  static/img/blog-part1-collection-variables-image1.png
Labels: netlify-cms/pending_review

#2272 Create Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace.md
  static/img/blog-part2-adding-device-async-operation-image5.png
  static/img/blog-part2-assign-app-to-device-image6.png
  static/img/blog-part2-assign-subscriptionkey-to-device-image7.png
  static/img/blog-part2-get-invited-user-image2.png
  static/img/blog-part2-invite-user-image1.png
Labels: netlify-cms/pending_review

#2277 Create Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-3-tracking-activities-and-monitoring-health”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-3-tracking-activities-and-monitoring-health.md
  static/img/blog-part3-auditlog-application-specific-logs-image2.png
  static/img/blog-part3-auditlog-tracking-user-activities-image1.png
  static/img/blog-part3-list-wellness-events-for-service-product-severity-image3.png
  static/img/blog-part3-view-wellness-event-for-specific-event-id-image4.png
Labels: netlify-cms/pending_review

#2257 Create Blog “hpe-greenlake-edge-to-cloud-platform-scripting-fundamentals”
  content/blog/hpe-greenlake-edge-to-cloud-platform-scripting-fundamentals.md
  static/img/apiaccess.jpg
  static/img/auditlogui.jpg
  static/img/codesample-for-token.jpg
  static/img/don-picture.png
Labels: netlify-cms/pending_review

#2289 Update Blog “hpe-greenlake-edge-to-cloud-platform-scripting-fundamentals”
  content/blog/hpe-greenlake-edge-to-cloud-platform-scripting-fundamentals.md
Labels: netlify-cms/draft

#2290 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis.md
Labels: netlify-cms/draft

#2291 Update Home Panel “07-spiffe-spire-graduates-enabling-greater-security-solutions”
  content/home/07-spiffe-spire-graduates-enabling-greater-security-solutions.md
Labels: netlify-cms/pending_review

#2292 Update Blog “dark-mode-theming-in-grommet-how-to-set-up-and-apply-a-theme”
  content/blog/dark-mode-theming-in-grommet-how-to-set-up-and-apply-a-theme.md
Labels: netlify-cms/draft

#2293 Update Blog “mixtral-8x7b-that-may-pave-the-trend-to-adopt-the-mixture-of-experts-model”
  content/blog/mixtral-8x7b-that-may-pave-the-trend-to-adopt-the-mixture-of-experts-model.md
Labels: netlify-cms/draft

#2294 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis.md
Labels: netlify-cms/draft

#2295 Update Blog “introduction-to-gpu-programming-in-chapel”
  content/blog/introduction-to-gpu-programming-in-chapel.md
Labels: netlify-cms/draft

#2296 Update Blog “programing-with-chapel-making-the-power-of-parallelism-and-supercomputers-more-accessible”
  content/blog/programing-with-chapel-making-the-power-of-parallelism-and-supercomputers-more-accessible.md
Labels: netlify-cms/draft

#2297 Update Blog “hpe-greenlake-edge-to-cloud-platform-scripting-fundamentals”
  content/blog/hpe-greenlake-edge-to-cloud-platform-scripting-fundamentals.md
Labels: netlify-cms/draft

#2298 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace.md
Labels: netlify-cms/pending_review

#2299 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-3-tracking-activities-and-monitoring-health”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-3-tracking-activities-and-monitoring-health.md
Labels: netlify-cms/pending_review

#2300 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis.md
Labels: netlify-cms/draft

#2301 Update Blog “hpe-greenlake-edge-to-cloud-platform-scripting-fundamentals”
  content/blog/hpe-greenlake-edge-to-cloud-platform-scripting-fundamentals.md
Labels: netlify-cms/pending_review

#2284 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2304 Update Events “using-hpe-greenlake-edge-to-cloud-platform-to-build-a-private-cloud”
  content/event/using-hpe-greenlake-edge-to-cloud-platform-to-build-a-private-cloud.md
Labels: netlify-cms/pending_review

#2303 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#2305 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis.md
Labels: netlify-cms/draft

#2307 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2309 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace.md
Labels: netlify-cms/draft

#2310 Update Blog “hpe-greenlake-edge-to-cloud-platform-scripting-fundamentals”
  content/blog/hpe-greenlake-edge-to-cloud-platform-scripting-fundamentals.md
Labels: netlify-cms/draft
