Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2024-04, with the labels that each got.

#2438 Update Events “the-family-of-hpe-greenlake-data-services-cloud-console-dscc-apis-–-putting-it-all-together”
  content/event/the-family-of-hpe-greenlake-data-services-cloud-console-dscc-apis-–-putting-it-all-together.md
Labels: netlify-cms/pending_publish

#2439 Update Blog “introducing-chapelcon-24-the-chapel-event-of-the-year”
  content/blog/introducing-chapelcon-24-the-chapel-event-of-the-year.md
Labels: netlify-cms/pending_publish

#2442 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2443 Update Events “enabling-business-automation-using-hpe-greenlake-platform-foundational-apis”
  content/event/enabling-business-automation-using-hpe-greenlake-platform-foundational-apis.md
Labels: netlify-cms/pending_publish

#2444 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2449 Update Community “Twitter”
  content/community/Twitter.md
  static/img/logo-black.png
Labels: netlify-cms/pending_review

#2450 Update Platforms “grommet/home”
  content/platform/grommet/home.md
Labels: netlify-cms/pending_review

#2460 Update Community “Twitter”
  content/community/Twitter.md
Labels: netlify-cms/draft

#2466 Update Blog “hpe-firmware-updates-part-3-the-redfish-update-service”
  content/blog/hpe-firmware-updates-part-3-the-redfish-update-service.md
Labels: netlify-cms/pending_publish

#2467 Update Blog “hpe-firmware-updates-part-3-the-redfish-update-service”
  content/blog/hpe-firmware-updates-part-3-the-redfish-update-service.md
Labels: netlify-cms/pending_publish

#2470 Update Blog “navier-stokes-in-chapel-—-introduction”
  content/blog/navier-stokes-in-chapel-—-introduction.md
Labels: netlify-cms/pending_publish

#2472 Update Blog “hpe-athonet-llm-platform-first-pillar-from-personal-assistant-to-collaborative-corporate-tool”
  content/blog/hpe-athonet-llm-platform-first-pillar-from-personal-assistant-to-collaborative-corporate-tool.md
Labels: netlify-cms/pending_publish

#2471 Update Blog “supercharged-chapel-editor-support”
  content/blog/supercharged-chapel-editor-support.md
Labels: netlify-cms/pending_publish

#2473 Update Blog “hpe-firmware-updates-part-3-the-redfish-update-service”
  content/blog/hpe-firmware-updates-part-3-the-redfish-update-service.md
Labels: netlify-cms/pending_publish

#2475 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2474 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2477 Create Events “leveraging-the-open-source-ml-advantage”
  content/event/leveraging-the-open-source-ml-advantage.md
  static/img/dsmu-virtual-session-3-vol2.jpg
Labels: netlify-cms/pending_review

#2481 Update Events “the-transformative-impact-of-generative-ai-on-telco-products”
  content/event/the-transformative-impact-of-generative-ai-on-telco-products.md
Labels: netlify-cms/pending_review

#2480 Update Hackshack Home Cards “hackshackhome-33”
  content/hackshackhome/hackshackhome-33.md
Labels: netlify-cms/pending_review

#2482 Update Hackshack Home Cards “hackshackhome-32”
  content/hackshackhome/hackshackhome-32.md
Labels: netlify-cms/pending_review

#2476 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2490 Update Blog “why-is-redfish®-different-from-other-rest-apis-part-1”
  content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
Labels: netlify-cms/pending_publish

#2496 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2497 Update Blog “getting-started-with-hpe-greenlake-api-for-virtualization”
  content/blog/getting-started-with-hpe-greenlake-api-for-virtualization.md
Labels: netlify-cms/draft

#2491 Create Events “chapelcon-24”
  content/event/chapelcon-24.md
Labels: netlify-cms/pending_review

#2464 Create Hackshack Home Cards “hackshackhome-34”
  content/hackshackhome/hackshackhome-34.md
Labels: netlify-cms/pending_review

#2461 Create Events “using-hpe-greenlake-for-red-hat-openshift-to-migrate-modernize-and-run-your-applications-smoothly”
  content/event/using-hpe-greenlake-for-red-hat-openshift-to-migrate-modernize-and-run-your-applications-smoothly.md
Labels: netlify-cms/pending_review

#2495 Create Hackshack Home Cards “hackshackhome-36”
  content/hackshackhome/hackshackhome-36.md
Labels: netlify-cms/pending_review

#2494 Create Hackshack Home Cards “hackshackhome-35”
  content/hackshackhome/hackshackhome-35.md
Labels: netlify-cms/pending_review

#2493 Create Events “implementing-centralized-key-management-in-hpe-greenlake-with-thales-ciphertrust”
  content/event/implementing-centralized-key-management-in-hpe-greenlake-with-thales-ciphertrust.md
Labels: netlify-cms/pending_review

#2492 Create Events “how-digital-twins-help-companies-reach-their-sustainability-goals”
  content/event/how-digital-twins-help-companies-reach-their-sustainability-goals.md
Labels: netlify-cms/pending_review

#2499 Update Blog “getting-started-with-hpe-greenlake-api-for-backup-and-recovery”
  content/blog/getting-started-with-hpe-greenlake-api-for-backup-and-recovery.md
Labels: netlify-cms/draft

#2504 Update Hackshack Home Cards “hackshackhome-32”
  content/hackshackhome/hackshackhome-32.md
Labels: netlify-cms/draft

#2505 Update Events “the-family-of-hpe-greenlake-data-services-cloud-console-dscc-apis-–-putting-it-all-together”
  content/event/the-family-of-hpe-greenlake-data-services-cloud-console-dscc-apis-–-putting-it-all-together.md
Labels: netlify-cms/draft

#2506 Update Events “the-family-of-hpe-greenlake-data-services-cloud-console-dscc-apis-–-putting-it-all-together”
  content/event/the-family-of-hpe-greenlake-data-services-cloud-console-dscc-apis-–-putting-it-all-together.md
Labels: netlify-cms/pending_publish

#2507 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_publish

#2510 Update Blog “chapels-high-level-support-for-cpu-gpu-data-transfers-and-multi-gpu-programming”
  content/blog/chapels-high-level-support-for-cpu-gpu-data-transfers-and-multi-gpu-programming.md
Labels: netlify-cms/draft

#2509 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft
