Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2024-07, with the labels that each got.

#2597 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2591 Create Blog “hpe-sustainability-insight-center-api-at-a-glance”
  content/blog/hpe-sustainability-insight-center-api-at-a-glance.md
  static/img/sic-blog-graphs.jpg
Labels: netlify-cms/pending_review

#2601 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2602 Update Blog “reflections-on-chapelcon-24-a-community-growing-together”
  content/blog/reflections-on-chapelcon-24-a-community-growing-together.md
Labels: netlify-cms/draft

#2604 Update Hackshack Home Cards “hackshackhome-37”
  content/hackshackhome/hackshackhome-37.md
Labels: netlify-cms/pending_publish

#2606 Create Events “enhancing-nlp-with-retrieval-augmented-generation-a-practical-demonstration”
  content/event/enhancing-nlp-with-retrieval-augmented-generation-a-practical-demonstration.md
Labels: netlify-cms/pending_review

#2605 Create Hackshack Home Cards “hackshackhome-38”
  content/hackshackhome/hackshackhome-38.md
Labels: netlify-cms/pending_review

#2609 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#2608 Update Events “implementing-centralized-key-management-in-hpe-greenlake-with-thales-ciphertrust”
  content/event/implementing-centralized-key-management-in-hpe-greenlake-with-thales-ciphertrust.md
Labels: netlify-cms/pending_review

#2610 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2611 Create Blog “the-sleuth-and-the-storyteller-the-dynamic-duo-behind-rag”
  content/blog/the-sleuth-and-the-storyteller-the-dynamic-duo-behind-rag.md
Labels: netlify-cms/pending_review

#2615 Update Blog “getting-started-with-the-hpe-greenlake-developer-portal”
  content/blog/getting-started-with-the-hpe-greenlake-developer-portal.md
Labels: netlify-cms/pending_publish

#2618 Update Blog “integrating-k8sgpt-to-empower-kubernetes-with-ai-in-hpe-greenlake-for-private-cloud-enterprise”
  content/blog/integrating-k8sgpt-to-empower-kubernetes-with-ai-in-hpe-greenlake-for-private-cloud-enterprise.md
Labels: netlify-cms/pending_publish

#2624 Update Blog “configuring-azure-ad-with-long-term-token-for-scim-provisiong”
  content/blog/configuring-azure-ad-with-long-term-token-for-scim-provisiong.md
Labels: netlify-cms/pending_publish

#2628 Update Blog “reflections-on-chapelcon-24-a-community-growing-together”
  content/blog/reflections-on-chapelcon-24-a-community-growing-together.md
Labels: netlify-cms/pending_review

#2627 Update Blog “chapel-2-0-scalable-and-productive-computing-for-all”
  content/blog/chapel-2-0-scalable-and-productive-computing-for-all.md
Labels: netlify-cms/pending_review

#2626 Update Blog “introducing-chapelcon-24-the-chapel-event-of-the-year”
  content/blog/introducing-chapelcon-24-the-chapel-event-of-the-year.md
Labels: netlify-cms/pending_review

#2629 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2632 Update GreenLake “hpe-greenlake-for-private-cloud-enterprise/home”
  content/greenlake/hpe-greenlake-for-private-cloud-enterprise/home.md
Labels: netlify-cms/draft

#2631 Create Events “llm-finetuning-for-mere-mortals”
  content/event/llm-finetuning-for-mere-mortals.md
Labels: netlify-cms/pending_review

#2630 Create Hackshack Home Cards “hackshackhome-39”
  content/hackshackhome/hackshackhome-39.md
Labels: netlify-cms/pending_review

#2634 Update Blog “parallel-processing-of-a-billion-rows-of-data-in-chapel”
  content/blog/parallel-processing-of-a-billion-rows-of-data-in-chapel.md
Labels: netlify-cms/draft

#2639 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#2638 Update Events “enhancing-nlp-with-retrieval-augmented-generation-a-practical-demonstration”
  content/event/enhancing-nlp-with-retrieval-augmented-generation-a-practical-demonstration.md
Labels: netlify-cms/pending_publish

#2637 Update Hackshack Home Cards “hackshackhome-38”
  content/hackshackhome/hackshackhome-38.md
Labels: netlify-cms/pending_publish

#2635 Update Hackshack Home Cards “hackshackhome-37”
  content/hackshackhome/hackshackhome-37.md
Labels: netlify-cms/pending_publish

#2607 Create Blog “redfish-interoperability-profiles”
  content/blog/redfish-interoperability-profiles.md
Labels: netlify-cms/pending_review

#2641 Update Platforms “ilo-restful-api/home”
  content/platform/ilo-restful-api/home.md
Labels: netlify-cms/pending_review

#2644 Update Hackshack Home Cards “hackshackhome-37”
  content/hackshackhome/hackshackhome-37.md
Labels: netlify-cms/pending_review

#2645 Update Events “vendor-neutral-gpu-programming-in-chapel”
  content/event/vendor-neutral-gpu-programming-in-chapel.md
Labels: netlify-cms/pending_review

#2646 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review
