Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2024-02, with the labels that each got.

#2313 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2312 Update Events “getting-started-with-hpe-greenlake-for-compute-ops-management-apis”
  content/event/getting-started-with-hpe-greenlake-for-compute-ops-management-apis.md
Labels: netlify-cms/draft

#2311 Update Hackshack Home Cards “hackshackhome-25”
  content/hackshackhome/hackshackhome-25.md
Labels: netlify-cms/draft

#2314 Create Hackshack Home Cards “hackshackhome-29”
  content/hackshackhome/hackshackhome-29.md
Labels: netlify-cms/pending_review

#2315 Create Events “secure-genai-adoption-for-all”
  content/event/secure-genai-adoption-for-all.md
Labels: netlify-cms/pending_review

#2316 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-3-tracking-activities-and-monitoring-health”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-3-tracking-activities-and-monitoring-health.md
Labels: netlify-cms/draft

#2317 Update Blog “hpe-greenlake-edge-to-cloud-platform-scripting-fundamentals”
  content/blog/hpe-greenlake-edge-to-cloud-platform-scripting-fundamentals.md
Labels: netlify-cms/draft

#2318 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis.md
Labels: netlify-cms/draft

#2320 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#2319 Update Events “getting-started-with-hpe-greenlake-for-compute-ops-management-apis”
  content/event/getting-started-with-hpe-greenlake-for-compute-ops-management-apis.md
Labels: netlify-cms/pending_review

#2321 Update Blog “deploying-cribl-stream-containers-on-hpe-greenlake”
  content/blog/deploying-cribl-stream-containers-on-hpe-greenlake.md
Labels: netlify-cms/pending_publish

#2323 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis.md
Labels: netlify-cms/pending_publish

#2324 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace.md
Labels: netlify-cms/pending_publish

#2322 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2329 Update Blog “kubernetes-monitoring-using-prometheus-and-grafana-in-hpe-greenlake-for-private-cloud-enterprise”
  content/blog/kubernetes-monitoring-using-prometheus-and-grafana-in-hpe-greenlake-for-private-cloud-enterprise.md
Labels: netlify-cms/pending_publish

#2328 Update Blog “how-to-backup-and-restore-stateful-applications-on-kubernetes-using-kasten-k10-in-hpe-greenlake-for-private-cloud-enterprise”
  content/blog/how-to-backup-and-restore-stateful-applications-on-kubernetes-using-kasten-k10-in-hpe-greenlake-for-private-cloud-enterprise.md
Labels: netlify-cms/pending_publish

#2327 Update Blog “getting-started-with-volume-snapshots-on-a-kubernetes-cluster-in-hpe-greenlake-for-private-cloud-enterprise”
  content/blog/getting-started-with-volume-snapshots-on-a-kubernetes-cluster-in-hpe-greenlake-for-private-cloud-enterprise.md
Labels: netlify-cms/pending_publish

#2334 Update Blog “hpe-discover-2021-don’t-miss-these-hpe-dev-industry-expert-talks-and-hands-on-workshops”
  content/blog/hpe-discover-2021-don’t-miss-these-hpe-dev-industry-expert-talks-and-hands-on-workshops.md
Labels: netlify-cms/draft

#2335 Update Platforms “determined-ai/home”
  content/platform/determined-ai/home.md
Labels: netlify-cms/draft

#2337 Update Platforms “swarm-learning/home”
  content/platform/swarm-learning/home.md
Labels: netlify-cms/draft

#2333 Create Hackshack Home Cards “hackshackhome-30”
  content/hackshackhome/hackshackhome-30.md
Labels: netlify-cms/pending_publish

#2339 Update Blog “comparing-standard-library-sorts-the-impact-of-parallelism”
  content/blog/comparing-standard-library-sorts-the-impact-of-parallelism.md
Labels: netlify-cms/pending_publish

#2340 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace.md
Labels: netlify-cms/pending_publish

#2343 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2346 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2347 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2349 Update Events “secure-genai-adoption-for-all”
  content/event/secure-genai-adoption-for-all.md
Labels: netlify-cms/pending_publish

#2350 Update Hackshack Home Cards “hackshackhome-26”
  content/hackshackhome/hackshackhome-26.md
Labels: netlify-cms/draft

#2351 Update Hackshack Home Cards “hackshackhome-30”
  content/hackshackhome/hackshackhome-30.md
Labels: netlify-cms/draft

#2353 Update Hackshack Home Cards “hackshackhome-30”
  content/hackshackhome/hackshackhome-30.md
Labels: netlify-cms/draft

#2355 Create Events “learn-how-ai-hackers-detect-fragility-and-how-to-thwart-them-with-ai-model-resilience”
  content/event/learn-how-ai-hackers-detect-fragility-and-how-to-thwart-them-with-ai-model-resilience.md
Labels: netlify-cms/draft

#2354 Create Hackshack Home Cards “hackshackhome-31”
  content/hackshackhome/hackshackhome-31.md
Labels: netlify-cms/draft

#2356 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2358 Update Blog “master-the-redfish-server-states-to-improve-your-monitoring-and-manageme”
  content/blog/master-the-redfish-server-states-to-improve-your-monitoring-and-manageme.md
Labels: netlify-cms/pending_publish

#2359 Update Events “secure-genai-adoption-for-all”
  content/event/secure-genai-adoption-for-all.md
Labels: netlify-cms/draft

#2357 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft
