Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2024-03, with the labels that each got.

#2372 Update Blog “in-band-management-with-ilorest-and-a-livecd”
  content/blog/in-band-management-with-ilorest-and-a-livecd.md
Labels: netlify-cms/pending_publish

#2371 Update Blog “managing-ilo-sessions-with-redfish”
  content/blog/managing-ilo-sessions-with-redfish.md
  static/img/1-getsessionmemberswithcurl.png
  static/img/10-getsessiondetails.png
  static/img/11-deletesession.png
  static/img/12-regularilorest.png
  static/img/13-ilorestinband-nocache.png
  static/img/2-getsessionmemberswithilorest.png
  static/img/3-ilorestnologout.png
  static/img/4-createsessionheaders.png
  static/img/5-createsessionbody.png
  static/img/6-createsessionresponseheaders.png
  static/img/7-postmantestscripttostoretokenandsessionlocation.png
  static/img/8-getsessionheaders.png
  static/img/9-getsessionresponsebody.png
Labels: netlify-cms/pending_review

#2373 Update Blog “setting-bios-and-storage-controller-properties-with-redfish”
  content/blog/setting-bios-and-storage-controller-properties-with-redfish.md
  static/img/1-put-body.png
  static/img/10-dataguardpropertymissing.png
  static/img/11-emptylogicaldrivesarray.png
  static/img/12-wrongraidlevel.png
  static/img/2-put-return-status.png
  static/img/3-getpendinglogicadrives.bmp
  static/img/5-getafterreset.png
  static/img/6-getafterreset-2.png
  static/img/7-badpayload.png
  static/img/8-put-return-status-of-bad-request.png
  static/img/9-pendingzonewithbadrequest.png
Labels: netlify-cms/pending_publish

#2375 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_publish

#2374 Update Events “getting-started-with-aruba-central-automation”
  content/event/getting-started-with-aruba-central-automation.md
Labels: netlify-cms/pending_publish

#2378 Update Blog “how-to-change-the-factory-generated-ilo-administrator-password”
  content/blog/how-to-change-the-factory-generated-ilo-administrator-password.md
  static/img/1-change-password-with-ilorest.png
  static/img/2-ilorest-list-manager-account.png
Labels: netlify-cms/pending_publish

#2379 Update Blog “storage-management-with-redfish”
  content/blog/storage-management-with-redfish.md
  static/img/0-smartstoragearraysentrypoints.png
  static/img/0-smartstorageconfigentrypoints.png
  static/img/1-physicaldrives.png
  static/img/11-addlogicaldrive.png
  static/img/12-addlogicaldrivetoexistingarray.png
  static/img/13-runningzoneafteraddition.png
  static/img/2-physicaldrives.png
  static/img/3-deletealllogicaldrives.png
  static/img/3-logicaldrivecollection.png
  static/img/4-clearconfigmetadata.png
  static/img/5-sanitizephysicaldrive.png
  static/img/6-erasestatus.png
  static/img/7-deletespecificlogicaldrive.png
  static/img/8-logical-raid1spare-creation.png
  static/img/9-runningzoneaftercreation.png
Labels: netlify-cms/pending_publish

#2352 Create Blog “why-is-redfish®-different-from-other-rest-apis-part-2”
  content/blog/why-is-redfish®-different-from-other-rest-apis-part-2.md
  static/img/fig10-swordfishschema.png
Labels: netlify-cms/pending_publish

#2341 Create Blog “why-is-redfish®-different-from-other-rest-apis-part-1”
  content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
  static/img/dmtf-redfish-logo.jpg
Labels: netlify-cms/pending_publish

#2382 Update Blog “hpe-firmware-updates-part-3-the-redfish-update-service”
  content/blog/hpe-firmware-updates-part-3-the-redfish-update-service.md
Labels: netlify-cms/pending_review

#2381 Update Blog “hpe-firmware-updates-part-2-interaction-in-operating-modes”
  content/blog/hpe-firmware-updates-part-2-interaction-in-operating-modes.md
Labels: netlify-cms/pending_publish

#2380 Update Blog “hpe-firmware-updates-part-1-file-types-and-smart-components”
  content/blog/hpe-firmware-updates-part-1-file-types-and-smart-components.md
Labels: netlify-cms/pending_publish

#2383 Update Blog “the-redfish-event-service”
  content/blog/the-redfish-event-service.md
  static/img/event-subscription-diagram.png
  static/img/subscription.png
Labels: netlify-cms/pending_review

#2384 Update Blog “why-is-redfish®-different-from-other-rest-apis-part-1”
  content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
Labels: netlify-cms/pending_publish

#2385 Update Blog “why-is-redfish®-different-from-other-rest-apis-part-2”
  content/blog/why-is-redfish®-different-from-other-rest-apis-part-2.md
Labels: netlify-cms/pending_review

#2386 Update Blog “why-is-redfish®-different-from-other-rest-apis-part-1”
  content/blog/why-is-redfish®-different-from-other-rest-apis-part-1.md
Labels: netlify-cms/pending_publish

#2387 Update Blog “why-is-redfish®-different-from-other-rest-apis-part-2”
  content/blog/why-is-redfish®-different-from-other-rest-apis-part-2.md
Labels: netlify-cms/pending_publish

#2389 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-3-tracking-activities-and-monitoring-health”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-3-tracking-activities-and-monitoring-health.md
Labels: netlify-cms/draft

#2390 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-3-tracking-activities-and-monitoring-health”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-3-tracking-activities-and-monitoring-health.md
  static/img/blog-part3-list-wellness-v2beta2-events-for-service-product-severity-image3.png
  static/img/blog-part3-view-wellness-v2beta2-event-for-specific-event-id-image4.png
Labels: netlify-cms/pending_review

#2392 Update Blog “be-an-hpe-dev-blogger”
  content/blog/be-an-hpe-dev-blogger.md
Labels: netlify-cms/draft

#2279 Create Blog “getting-started-with-the-hpe-greenlake-developer-portal”
  content/blog/getting-started-with-the-hpe-greenlake-developer-portal.md
  static/img/blog-greenlake-dev-portal1.png
  static/img/blog-greenlake-dev-portal2.png
  static/img/blog-greenlake-dev-portal3.png
  static/img/blog-greenlake-dev-portal4.png
  static/img/blog-greenlake-dev-portal5.png
  static/img/blog-greenlake-dev-portal6.png
Labels: netlify-cms/pending_review

#2393 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace.md
Labels: netlify-cms/draft

#2363 Create Events “the-family-of-hpe-greenlake-data-services-cloud-console-dscc-apis-–-putting-it-all-together”
  content/event/the-family-of-hpe-greenlake-data-services-cloud-console-dscc-apis-–-putting-it-all-together.md
Labels: netlify-cms/draft

#2401 Update Blog “announcing-genai-studio-your-generative-ai-playground-built-on-determined”
  content/blog/announcing-genai-studio-your-generative-ai-playground-built-on-determined.md
Labels: netlify-cms/draft

#2399 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2407 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2412 Update Hackshack Home Cards “hackshackhome-31”
  content/hackshackhome/hackshackhome-31.md
Labels: netlify-cms/draft

#2411 Update Events “learn-how-ai-hackers-detect-fragility-and-how-to-thwart-them-with-ai-model-resilience”
  content/event/learn-how-ai-hackers-detect-fragility-and-how-to-thwart-them-with-ai-model-resilience.md
Labels: netlify-cms/draft

#2403 Create Events “the-transformative-impact-of-generative-ai-on-telco-products”
  content/event/the-transformative-impact-of-generative-ai-on-telco-products.md
Labels: netlify-cms/draft

#2402 Create Hackshack Home Cards “hackshackhome-33”
  content/hackshackhome/hackshackhome-33.md
Labels: netlify-cms/draft

#2413 Update Blog “introduction-to-gpu-programming-in-chapel”
  content/blog/introduction-to-gpu-programming-in-chapel.md
Labels: netlify-cms/pending_publish

#2414 Update Blog “open-sourcing-packetrusher-a-5g-core-performance-tester”
  content/blog/open-sourcing-packetrusher-a-5g-core-performance-tester.md
Labels: netlify-cms/pending_publish

#2415 Update Blog “hpe-athonet-llm-platform-first-pillar-from-personal-assistant-to-collaborative-corporate-tool”
  content/blog/hpe-athonet-llm-platform-first-pillar-from-personal-assistant-to-collaborative-corporate-tool.md
Labels: netlify-cms/pending_publish

#2418 Update Blog “getting-started-with-the-hpe-greenlake-developer-portal”
  content/blog/getting-started-with-the-hpe-greenlake-developer-portal.md
Labels: netlify-cms/pending_publish

#2419 Update Blog “using-postman-with-hpe-simplivity”
  content/blog/using-postman-with-hpe-simplivity.md
Labels: netlify-cms/draft

#2420 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2423 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis.md
Labels: netlify-cms/pending_review

#2424 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace.md
Labels: netlify-cms/pending_review

#2427 Update Blog “okta-sso-integration-for-green-lake-and-aruba-central”
  content/blog/okta-sso-integration-for-green-lake-and-aruba-central.md
Labels: netlify-cms/pending_review

#2430 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2431 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2432 Update Hackshack Home Cards “hackshackhome-30”
  content/hackshackhome/hackshackhome-30.md
Labels: netlify-cms/draft

#2433 Update Events “enabling-business-automation-using-hpe-greenlake-platform-foundational-apis”
  content/event/enabling-business-automation-using-hpe-greenlake-platform-foundational-apis.md
Labels: netlify-cms/draft

#2434 Update Hackshack Home Cards “hackshackhome-32”
  content/hackshackhome/hackshackhome-32.md
Labels: netlify-cms/pending_review

#2435 Update Events “the-family-of-hpe-greenlake-data-services-cloud-console-dscc-apis-–-putting-it-all-together”
  content/event/the-family-of-hpe-greenlake-data-services-cloud-console-dscc-apis-–-putting-it-all-together.md
Labels: netlify-cms/pending_review

#2436 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft
