Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2024-08, with the labels that each got.

#2648 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#2647 Update Events “vendor-neutral-gpu-programming-in-chapel”
  content/event/vendor-neutral-gpu-programming-in-chapel.md
Labels: netlify-cms/pending_review

#2650 Create Skillup “skillup-2”
  content/skillup/skillup-2.md
  static/img/innovation_2c_70x100.jpg
Labels: netlify-cms/pending_review

#2651 Update Campaign “hpe-innovation-workshops”
  content/campaign/hpe-innovation-workshops.md
Labels: netlify-cms/pending_review

#2643 Create Events “hpe-ai-foundations-workshop”
  content/event/hpe-ai-foundations-workshop.md
  static/img/innovation_2c_1600_0_72_rgb.jpg
  static/img/innovation_2c_207x300.jpg
Labels: netlify-cms/pending_review

#2652 Update Events “hpe-ai-foundations-workshop”
  content/event/hpe-ai-foundations-workshop.md
  static/img/innovation-workshops-icon-dale-427x413.png
Labels: netlify-cms/pending_review

#2653 Update Skillup “skillup-2”
  content/skillup/skillup-2.md
  static/img/innovation-workshops-icon-dale-207x200.png
Labels: netlify-cms/pending_review

#2654 Update Campaign “hpe-innovation-workshops”
  content/campaign/hpe-innovation-workshops.md
Labels: netlify-cms/pending_review

#2655 Update Skillup “skillup-2”
  content/skillup/skillup-2.md
  static/img/innovation-workshops-icon-dale-227x220.png
Labels: netlify-cms/pending_review

#2656 Create Blog “simplifying-code-migration-the-benefits-of-the-new-ampere-porting-advisor-for-x86-to-arm64”
  content/blog/simplifying-code-migration-the-benefits-of-the-new-ampere-porting-advisor-for-x86-to-arm64.md
Labels: netlify-cms/pending_review

#2658 Update Events “hpe-ai-foundations-workshop”
  content/event/hpe-ai-foundations-workshop.md
  static/img/medium-hpe-innovation-workshops-3-408x412.png
Labels: netlify-cms/draft

#2659 Update Skillup “skillup-2”
  content/skillup/skillup-2.md
  static/img/event-hpe-innovation-workshops-808x815.png
Labels: netlify-cms/pending_review

#2660 Update Campaign “hpe-innovation-workshops”
  content/campaign/hpe-innovation-workshops.md
  static/img/event-hpe-innovation-workshops-303x305.png
Labels: netlify-cms/pending_review

#2662 Update Platforms “hpe-nonstop/home”
  content/platform/hpe-nonstop/home.md
Labels: netlify-cms/pending_review

#2663 Create Events “hpe-and-451-research-joint-webinar”
  content/event/hpe-and-451-research-joint-webinar.md
  static/img/451-partner-webinar338x310.png
  static/img/451-partner-webinar438x402.png
Labels: netlify-cms/pending_publish

#2665 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2666 Create Events “exploring-transformative-ai-use-cases-across-industries”
  content/event/exploring-transformative-ai-use-cases-across-industries.md
Labels: netlify-cms/pending_review

#2667 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#2668 Update Platforms “swarm-learning/home”
  content/platform/swarm-learning/home.md
Labels: netlify-cms/pending_review

#2669 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2671 Update Hackshack Home Cards “hackshackhome-39”
  content/hackshackhome/hackshackhome-39.md
Labels: netlify-cms/draft

#2672 Update Hackshack Home Cards “hackshackhome-38”
  content/hackshackhome/hackshackhome-38.md
Labels: netlify-cms/draft

#2675 Update Campaign “hpe-innovation-workshops”
  content/campaign/hpe-innovation-workshops.md
Labels: netlify-cms/pending_review

#2674 Update Events “hpe-ai-foundations-workshop”
  content/event/hpe-ai-foundations-workshop.md
Labels: netlify-cms/pending_review

#2678 Update Platforms “chapel/home”
  content/platform/chapel/home.md
Labels: netlify-cms/pending_review

#2680 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2676 Create Events “exploring-the-hpe-sustainability-insight-center-key-features-innovations-and-sic-api-capabilities”
  content/event/exploring-the-hpe-sustainability-insight-center-key-features-innovations-and-sic-api-capabilities.md
Labels: netlify-cms/pending_publish

#2677 Create Hackshack Home Cards “hackshackhome-41”
  content/hackshackhome/hackshackhome-41.md
Labels: netlify-cms/pending_publish

#2682 Update Events “llm-finetuning-for-mere-mortals”
  content/event/llm-finetuning-for-mere-mortals.md
Labels: netlify-cms/pending_publish

#2681 Update Hackshack Home Cards “hackshackhome-39”
  content/hackshackhome/hackshackhome-39.md
Labels: netlify-cms/pending_publish

#2679 Update Platforms “hpe-ezmeral/home”
  content/platform/hpe-ezmeral/home.md
Labels: netlify-cms/pending_review

#2685 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2684 Update Platforms “hpe-ezmeral-data-fabric/home”
  content/platform/hpe-ezmeral-data-fabric/home.md
Labels: netlify-cms/pending_publish

#2687 Update Events “exploring-transformative-ai-use-cases-across-industries”
  content/event/exploring-transformative-ai-use-cases-across-industries.md
Labels: netlify-cms/pending_review

#2686 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft
