Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2024-10, with the labels that each got.

#2724 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2722 Update Events “exploring-the-hpe-sustainability-insight-center-key-features-innovations-and-sic-api-capabilities”
  content/event/exploring-the-hpe-sustainability-insight-center-key-features-innovations-and-sic-api-capabilities.md
Labels: netlify-cms/draft

#2725 Update Blog “keeping-it-real-with-a-new-ai-jam-series”
  content/blog/keeping-it-real-with-a-new-ai-jam-series.md
Labels: netlify-cms/draft

#2726 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2728 Update Blog “hpe-firmware-updates-part-3-the-redfish-update-service”
  content/blog/hpe-firmware-updates-part-3-the-redfish-update-service.md
Labels: netlify-cms/pending_publish

#2729 Update Campaign “get-real-with-ai-–-jam-series”
  content/campaign/get-real-with-ai-–-jam-series.md
Labels: netlify-cms/draft

#2730 Create Blog “small-language-models-the-next-frontier-with-private-cloud-ai”
  content/blog/small-language-models-the-next-frontier-with-private-cloud-ai.md
  static/img/1701400243241.jpeg
Labels: netlify-cms/pending_review

#2733 Update Hackshack Home Cards “hackshackhome-40”
  content/hackshackhome/hackshackhome-40.md
Labels: netlify-cms/pending_review

#2732 Update GreenLake “hpe-greenlake-platform/home”
  content/greenlake/hpe-greenlake-platform/home.md
Labels: netlify-cms/pending_review

#2735 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-2-configuring-and-managing-a-workspace.md
Labels: netlify-cms/pending_publish

#2736 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-3-tracking-activities-and-monitoring-health”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-3-tracking-activities-and-monitoring-health.md
Labels: netlify-cms/pending_publish

#2734 Update Blog “get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis”
  content/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-–-part-1-introduction-to-the-apis.md
Labels: netlify-cms/pending_publish

#2737 Update Events “enhancing-nlp-with-retrieval-augmented-generation-a-practical-demonstration”
  content/event/enhancing-nlp-with-retrieval-augmented-generation-a-practical-demonstration.md
Labels: netlify-cms/pending_publish

#2738 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#2741 Create Blog “introducing-the-ampere®-performance-toolkit-to-optimize-software”
  content/blog/introducing-the-ampere®-performance-toolkit-to-optimize-software.md
Labels: netlify-cms/pending_review

#2740 Update Events “cool-ai-use-case-now-what”
  content/event/cool-ai-use-case-now-what.md
Labels: netlify-cms/draft

#2739 Update Campaign “get-real-with-ai-–-jam-series”
  content/campaign/get-real-with-ai-–-jam-series.md
Labels: netlify-cms/draft

#2744 Create Events “nvidia-nim-agents-blueprints-do-your-own-ai-multimodal-pdf-data-extraction-101”
  content/event/nvidia-nim-agents-blueprints-do-your-own-ai-multimodal-pdf-data-extraction-101.md
Labels: netlify-cms/pending_review

#2745 Create Hackshack Home Cards “hackshackhome-43”
  content/hackshackhome/hackshackhome-43.md
Labels: netlify-cms/pending_review

#2747 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2749 Update Hackshack Home Cards “hackshackhome-40”
  content/hackshackhome/hackshackhome-40.md
Labels: netlify-cms/draft

#2706 Create Events “how-to-fix-your-biggest-security-hole”
  content/event/how-to-fix-your-biggest-security-hole.md
Labels: netlify-cms/pending_review

#2748 Update Campaign “get-real-with-ai-–-jam-series”
  content/campaign/get-real-with-ai-–-jam-series.md
Labels: netlify-cms/draft

#2705 Create Hackshack Home Cards “hackshackhome-42”
  content/hackshackhome/hackshackhome-42.md
Labels: netlify-cms/pending_review

#2750 Create Events “implementing-your-ai-breakthroughs-effectively-the-infrastructure-to-your-ai”
  content/event/implementing-your-ai-breakthroughs-effectively-the-infrastructure-to-your-ai.md
Labels: netlify-cms/pending_review

#2753 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2754 Update Events “hybrid-classical-quantum-workflows-on-hpe-supercomputers”
  content/event/hybrid-classical-quantum-workflows-on-hpe-supercomputers.md
Labels: netlify-cms/pending_publish

#2755 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#2756 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2752 Create Events “picking-the-right-software-for-your-ai-use-cases”
  content/event/picking-the-right-software-for-your-ai-use-cases.md
Labels: netlify-cms/pending_publish

#2751 Create Events “ll-mesh-–-democratizing-gen-ai”
  content/event/ll-mesh-–-democratizing-gen-ai.md
Labels: netlify-cms/pending_review

#2758 Create Hackshack Home Cards “hackshackhome-44”
  content/hackshackhome/hackshackhome-44.md
Labels: netlify-cms/pending_review

#2759 Update Hackshack Home Cards “hackshackhome-44”
  content/hackshackhome/hackshackhome-44.md
Labels: netlify-cms/pending_review
