Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2025-02, with the labels that each got.

#2901 Update Events “unleashing-ai-innovation-a-deep-dive-into-the-hpe-private-cloud-ai-software-stack”
  content/event/unleashing-ai-innovation-a-deep-dive-into-the-hpe-private-cloud-ai-software-stack.md
Labels: netlify-cms/pending_publish

#2902 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_publish

#2900 Create Events “ai-inferencing-at-the-edge-use-cases-from-earth-to-space”
  content/event/ai-inferencing-at-the-edge-use-cases-from-earth-to-space.md
Labels: netlify-cms/pending_publish

#2904 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2899 Update GreenLake “hpe-greenlake-platform/home”
  content/greenlake/hpe-greenlake-platform/home.md
Labels: netlify-cms/pending_publish

#2907 Update GreenLake “aruba-central/home”
  content/greenlake/aruba-central/home.md
Labels: netlify-cms/pending_publish

#2909 Update Blog “using-the-gdb4hpc-debugger-at-scale-with-a-cuda-mpi-hpc-application”
  content/blog/using-the-gdb4hpc-debugger-at-scale-with-a-cuda-mpi-hpc-application.md
Labels: netlify-cms/pending_publish

#2910 Create Blog “getting-started-with-the-hpe-greenlake-cloud-eventing-framework”
  content/blog/getting-started-with-the-hpe-greenlake-cloud-eventing-framework.md
  static/img/add-a-google-sheet.jpg
  static/img/add-a-router.jpg
  static/img/add-set-variabke-step.jpg
  static/img/add-webhook-response.jpg
  static/img/build-a-row.jpg
  static/img/building-a-row.jpg
  static/img/create-a-webhook.jpg
  static/img/create-webhook-2.jpg
  static/img/drag-drop-properties.jpg
  static/img/event-subscribed.jpg
  static/img/events-in-google-docs.jpg
  static/img/google-row-visible.jpg
  static/img/googlesheet-set.jpg
  static/img/post-event-in-postman.jpg
  static/img/postman-challenge.jpg
  static/img/presentation2-auto-saved-.jpg
  static/img/run-immediatly.jpg
  static/img/same-secret-key.jpg
  static/img/second-route-taken.jpg
  static/img/second-webhook-response.jpg
  static/img/select-challenge.jpg
  static/img/select-event-struture.jpg
  static/img/set-fallback.jpg
  static/img/setup-filter.jpg
  static/img/setwebhook-response.jpg
  static/img/slide-for-blog-webhooks.jpg
  static/img/step1-final.jpg
  static/img/subscribe.jpg
  static/img/webhooklist.jpg
  static/img/webhooksview.jpg
Labels: netlify-cms/pending_review

#2912 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#2911 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#2917 Update Campaign “get-real-with-ai-jam-series”
  content/campaign/get-real-with-ai-jam-series.md
Labels: netlify-cms/pending_publish

#2920 Update Campaign “get-real-with-ai-jam-series”
  content/campaign/get-real-with-ai-jam-series.md
Labels: netlify-cms/pending_publish

#2919 Update Events “ai-inferencing-at-the-edge-use-cases-from-earth-to-space”
  content/event/ai-inferencing-at-the-edge-use-cases-from-earth-to-space.md
Labels: netlify-cms/pending_publish

#2923 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#2922 Update Events “unlocking-private-ai-power-insurance-fraud-detection-and-beyond”
  content/event/unlocking-private-ai-power-insurance-fraud-detection-and-beyond.md
Labels: netlify-cms/pending_publish

#2921 Update Hackshack Home Cards “hackshackhome-48”
  content/hackshackhome/hackshackhome-48.md
Labels: netlify-cms/pending_publish

#2925 Update Events “ai-inferencing-at-the-edge-use-cases-from-earth-to-space”
  content/event/ai-inferencing-at-the-edge-use-cases-from-earth-to-space.md
Labels: netlify-cms/pending_publish

#2924 Update Campaign “get-real-with-ai-jam-series”
  content/campaign/get-real-with-ai-jam-series.md
Labels: netlify-cms/pending_publish

#2927 Update Events “ai-inferencing-at-the-edge-use-cases-from-earth-to-space”
  content/event/ai-inferencing-at-the-edge-use-cases-from-earth-to-space.md
Labels: netlify-cms/pending_publish

#2926 Update Campaign “get-real-with-ai-jam-series”
  content/campaign/get-real-with-ai-jam-series.md
Labels: netlify-cms/pending_publish

#2930 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#2929 Update Events “unlocking-private-ai-power-insurance-fraud-detection-and-beyond”
  content/event/unlocking-private-ai-power-insurance-fraud-detection-and-beyond.md
Labels: netlify-cms/pending_publish

#2916 Create Events “no-more-blind-spots-how-ebpf-transforms-observability”
  content/event/no-more-blind-spots-how-ebpf-transforms-observability.md
Labels: netlify-cms/pending_publish

#2915 Create Hackshack Home Cards “hackshackhome-50”
  content/hackshackhome/hackshackhome-50.md
Labels: netlify-cms/pending_publish

#2913 Create Events “chathpe-hub-enabling-secure-and-scalable-ai-transformation-at-hpe”
  content/event/chathpe-hub-enabling-secure-and-scalable-ai-transformation-at-hpe.md
Labels: netlify-cms/pending_publish

#2932 Create Blog “the-rise-of-the-distributed-enterprise”
  content/blog/the-rise-of-the-distributed-enterprise.md
  static/img/the-rise-of-the-distributed-enterprise-image-1.png
  static/img/the-rise-of-the-distributed-enterprise-image-2.png
Labels: netlify-cms/pending_publish

#2933 Update Blog “getting-started-with-the-hpe-greenlake-cloud-eventing-framework”
  content/blog/getting-started-with-the-hpe-greenlake-cloud-eventing-framework.md
Labels: netlify-cms/draft

#2934 Update Blog “the-rise-of-the-distributed-enterprise”
  content/blog/the-rise-of-the-distributed-enterprise.md
  static/img/denisvilfort_head_shot_2.png
Labels: netlify-cms/pending_publish

#2935 Update Blog “getting-started-with-the-hpe-greenlake-cloud-eventing-framework”
  content/blog/getting-started-with-the-hpe-greenlake-cloud-eventing-framework.md
  static/img/slide-pour-blog-webhooks.jpg
Labels: netlify-cms/draft

#2939 Update Events “introduction-to-hpe-greenlake-webhooks”
  content/event/introduction-to-hpe-greenlake-webhooks.md
Labels: netlify-cms/pending_publish

#2938 Update Hackshack Home Cards “hackshackhome-50”
  content/hackshackhome/hackshackhome-50.md
Labels: netlify-cms/pending_publish

#2937 Update Hackshack Home Cards “hackshackhome-49”
  content/hackshackhome/hackshackhome-49.md
Labels: netlify-cms/pending_publish

#2936 Update Hackshack Home Cards “hackshackhome-47”
  content/hackshackhome/hackshackhome-47.md
Labels: netlify-cms/pending_publish

#2940 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_publish

#2941 Update Home Panel “07-spiffe-spire-graduates-enabling-greater-security-solutions”
  content/home/07-spiffe-spire-graduates-enabling-greater-security-solutions.md
Labels: netlify-cms/pending_publish

#2942 Update Blog “small-language-models-the-next-frontier-with-private-cloud-ai”
  content/blog/small-language-models-the-next-frontier-with-private-cloud-ai.md
Labels: netlify-cms/pending_publish

#2944 Update Blog “implementing-your-ai-breakthroughs-effectively-–-the-infrastructure-to-your-a-i”
  content/blog/implementing-your-ai-breakthroughs-effectively-–-the-infrastructure-to-your-a-i.md
Labels: netlify-cms/pending_publish

#2949 Update Blog “getting-started-with-the-hpe-greenlake-cloud-eventing-framework”
  content/blog/getting-started-with-the-hpe-greenlake-cloud-eventing-framework.md
Labels: netlify-cms/pending_publish

#2948 Update Blog “getting-started-with-retrieval-augmented-generation-rag”
  content/blog/getting-started-with-retrieval-augmented-generation-rag.md
Labels: netlify-cms/pending_publish

#2947 Update Blog “7-questions-for-bill-reus-interactive-supercomputing-with-chapel-for-cybersecurity”
  content/blog/7-questions-for-bill-reus-interactive-supercomputing-with-chapel-for-cybersecurity.md
Labels: netlify-cms/pending_publish

#2946 Update Blog “what’s-new-with-chapel-nine-questions-for-the-development-team”
  content/blog/what’s-new-with-chapel-nine-questions-for-the-development-team.md
Labels: netlify-cms/pending_publish

#2945 Update Blog “why-private-ai”
  content/blog/why-private-ai.md
Labels: netlify-cms/pending_publish

#2951 Update Events “introduction-to-hpe-greenlake-webhooks”
  content/event/introduction-to-hpe-greenlake-webhooks.md
Labels: netlify-cms/pending_publish

#2950 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_publish
