Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2025-06, with the labels that each got.

#3064 Update GreenLake “hybrid-observability-flex-solutions/home”
  content/greenlake/hybrid-observability-flex-solutions/home.md
Labels: netlify-cms/pending_publish

#3063 Create Blog “10-myths-about-scalable-parallel-programming-languages-redux-part-2-past-failures-and-future-attempts”
  content/blog/10-myths-about-scalable-parallel-programming-languages-redux-part-2-past-failures-and-future-attempts.md
Labels: netlify-cms/draft

#3069 Create Blog “hpe-greenlake-cloud-integration-with-servicenow-using-webhooks”
  content/blog/hpe-greenlake-cloud-integration-with-servicenow-using-webhooks.md
  static/img/chethan.png
  static/img/servicenoew-webhook-note1.jpg
  static/img/servicenow-webhook-blog-0017ecb8-a01f-4ab8-9261-4d626d983491.jpeg
  static/img/servicenow-webhook-blog-10399983-7080-49e4-9fb6-9257e60aeeb5.jpeg
  static/img/servicenow-webhook-blog-2743dab1-f57e-4e38-9878-b9d78860ad1b.jpeg
  static/img/servicenow-webhook-blog-4d7ccf04-4626-45a9-998f-35d9a03acf6f.jpeg
  static/img/servicenow-webhook-blog-5c9b0e45-419b-4cb2-ab5d-62cd1d753712.jpeg
  static/img/servicenow-webhook-blog-a8242a8f-67d7-474e-8f06-60985ab1719a.jpeg
  static/img/servicenow-webhook-blog-b59f8ece-6b27-4b70-af46-2bc83a062a3a.jpeg
  static/img/servicenow-webhook-blog-c6a22d4d-56b9-41cb-8dfa-a8fdac99ab6d.jpeg
  static/img/servicenow-webhook-blog-cfb0ec5a-f2f3-4982-bf02-361f5efe9d73.jpeg
  static/img/servicenow-webhook-blog-e980f286-a395-48b7-9f8e-8596f0ab008b.jpeg
  static/img/servicenow-webhook-blog-eaabb59e-9fbb-4ddc-907b-8796ecd3c5e6.jpeg
  static/img/servicenow-webhook-blog-eceaeba3-a264-4fa7-af6b-434a1d26832d.jpeg
  static/img/servicenow-webhook-blog-f470575f-6d7a-48d1-a98c-ef161a54a827.jpeg
Labels: netlify-cms/draft

#3072 Create Blog “announcing-chapel-2-5”
  content/blog/announcing-chapel-2-5.md
Labels: netlify-cms/pending_publish

#3076 Update Be a Blogger “contribute”
  content/contribute/contribute.md
Labels: netlify-cms/pending_publish

#3080 Update Blog “open-sourcing-workshops-on-demand-part2-deploying-the-backend”
  content/blog/open-sourcing-workshops-on-demand-part2-deploying-the-backend.md
  static/img/wod-blogserie2-2repos.png
Labels: netlify-cms/pending_publish

#3082 Update Platforms “hpe-ezmeral/home”
  content/platform/hpe-ezmeral/home.md
Labels: netlify-cms/draft

#3085 Create Blog “new-features-in-hpe-morpheus-vm-essentials-software-8-0-5”
  content/blog/new-features-in-hpe-morpheus-vm-essentials-software-8-0-5.md
Labels: netlify-cms/pending_publish

#3084 Create Blog “integrating-hpe-greenlake-webhooks-with-splunk”
  content/blog/integrating-hpe-greenlake-webhooks-with-splunk.md
  static/img/03af2f59-ab50-443b-ae93-90d274738317.png
  static/img/310bb0be-5363-428a-99a2-5f64bef2ca8a.png
  static/img/dccf7431-b83b-4799-a795-25bccc7637db.png
  static/img/diagram.jpg
Labels: netlify-cms/pending_review
