Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2025-05, with the labels that each got.

#3036 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#3041 Create Events “lessons-in-ai-for-retailers-transforming-the-shopping-experience”
  content/event/lessons-in-ai-for-retailers-transforming-the-shopping-experience.md
Labels: netlify-cms/pending_publish

#3045 Update Events “hpe-private-cloud-ai-technical-demo”
  content/event/hpe-private-cloud-ai-technical-demo.md
Labels: netlify-cms/pending_publish

#3046 Update Platforms “hpe-private-cloud-ai/home”
  content/platform/hpe-private-cloud-ai/home.md
  static/img/thumbnail-pcai-demo-500-281.png
Labels: netlify-cms/pending_review

#3047 Update Home Panel “01-hpe-greenlake”
  content/home/01-hpe-greenlake.md
Labels: netlify-cms/draft

#3052 Update Events “hpe-compute-ops-management-apis-and-the-devops-ecosystem-updates-and-developer-tools”
  content/event/hpe-compute-ops-management-apis-and-the-devops-ecosystem-updates-and-developer-tools.md
Labels: netlify-cms/pending_publish

#3044 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#3053 Update Campaign “get-real-with-ai-jam-series”
  content/campaign/get-real-with-ai-jam-series.md
Labels: netlify-cms/draft

#3048 Create Blog “hybrid-observability-service-–-part-1-provisioning-and-activation-in-hpe-greenlake-flex-solutions”
  content/blog/hybrid-observability-service-–-part-1-provisioning-and-activation-in-hpe-greenlake-flex-solutions.md
  static/img/opsramp-activation-img-12.png
  static/img/opsramp-activation-img-19.png
  static/img/opsramp-activation-img-2.png
  static/img/opsramp-activation-img-20.png
  static/img/opsramp-activation-img-5.png
Labels: netlify-cms/pending_publish

#3056 Update Blog “hybrid-observability-service-–-part-1-provisioning-and-activation-in-hpe-greenlake-flex-solutions”
  content/blog/hybrid-observability-service-–-part-1-provisioning-and-activation-in-hpe-greenlake-flex-solutions.md
Labels: netlify-cms/pending_publish

#3049 Create Blog “hybrid-observability-service-–-part-2-initial-configuration-to-enable-the-discovery-of-resources-in-hpe-greenlake-flex-solutions”
  content/blog/hybrid-observability-service-–-part-2-initial-configuration-to-enable-the-discovery-of-resources-in-hpe-greenlake-flex-solutions.md
  static/img/network-deployment-requirements.png
  static/img/opsramp-client-setup-img-6.png
  static/img/opsramp-gateway-install-img-10.png
  static/img/opsramp-gateway-install-img-2.png
  static/img/opsramp-gateway-install-img-4.png
  static/img/opsramp-gateway-install-img-5.png
  static/img/opsramp-gateway-install-img-8.png
  static/img/opsramp-gateway-install-img-9.png
Labels: netlify-cms/pending_publish

#3057 Update Blog “hybrid-observability-service-–-part-2-initial-configuration-to-enable-the-discovery-of-resources-in-hpe-greenlake-flex-solutions”
  content/blog/hybrid-observability-service-–-part-2-initial-configuration-to-enable-the-discovery-of-resources-in-hpe-greenlake-flex-solutions.md
Labels: netlify-cms/pending_publish

#3058 Update Blog “hybrid-observability-service-–-part-1-provisioning-and-activation-in-hpe-greenlake-flex-solutions”
  content/blog/hybrid-observability-service-–-part-1-provisioning-and-activation-in-hpe-greenlake-flex-solutions.md
Labels: netlify-cms/pending_publish

#3050 Create Blog “hybrid-observability-service-–-part-3-enabling-the-monitoring-of-agentless-ssh-enabled-systems-in-hpe-greenlake-flex-solutions”
  content/blog/hybrid-observability-service-–-part-3-enabling-the-monitoring-of-agentless-ssh-enabled-systems-in-hpe-greenlake-flex-solutions.md
  static/img/agentless-ssh-integration-img2.png
  static/img/agentless-ssh-integration-img3.png
  static/img/agentless-ssh-integration-img6.png
  static/img/agentless-ssh-monitoring-img1.png
  static/img/agentless-ssh-monitoring-img10.png
  static/img/agentless-ssh-monitoring-img2.png
  static/img/agentless-ssh-monitoring-img4.png
  static/img/agentless-ssh-monitoring-img7.png
Labels: netlify-cms/pending_publish

#3055 Create Blog “hybrid-observability-service-–-part-4-enabling-the-monitoring-of-physical-devices-in-hpe-greenlake-flex-solutions”
  content/blog/hybrid-observability-service-–-part-4-enabling-the-monitoring-of-physical-devices-in-hpe-greenlake-flex-solutions.md
  static/img/create-dashboard-img10.png
  static/img/create-dashboard-img14.png
  static/img/create-dashboard-img2.png
  static/img/create-dashboard-img7.png
  static/img/create-dashboard-img8.png
  static/img/create-dashboard-img9.png
  static/img/integration-alletramp-img5.png
  static/img/integration-redfish-img10.png
  static/img/integration-redfish-img7-bis2.png
  static/img/integration-redfish-img7.png
  static/img/integration-redfish-img8-bis.png
  static/img/integration-redfish-img9.png
Labels: netlify-cms/pending_publish

#3060 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft
