Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2025-01, with the labels that each got.

#2854 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2856 Update Events “ll-mesh-–-democratizing-gen-ai”
  content/event/ll-mesh-–-democratizing-gen-ai.md
Labels: netlify-cms/pending_publish

#2861 Update Hackshack Home Cards “hackshackhome-45”
  content/hackshackhome/hackshackhome-45.md
Labels: netlify-cms/pending_publish

#2860 Update Hackshack Home Cards “hackshackhome-46”
  content/hackshackhome/hackshackhome-46.md
Labels: netlify-cms/pending_publish

#2853 Update Platforms “spiffe-and-spire-projects/home”
  content/platform/spiffe-and-spire-projects/home.md
Labels: netlify-cms/pending_publish

#2841 Create Blog “why-private-ai”
  content/blog/why-private-ai.md
  static/img/jordan-nanos.jpg
Labels: netlify-cms/pending_review

#2849 Create Events “introduction-to-hpe-greenlake-webhooks”
  content/event/introduction-to-hpe-greenlake-webhooks.md
Labels: netlify-cms/pending_publish

#2863 Create Events “unlocking-private-ai-power-insurance-fraud-detection-and-beyond”
  content/event/unlocking-private-ai-power-insurance-fraud-detection-and-beyond.md
Labels: netlify-cms/pending_publish

#2862 Create Hackshack Home Cards “hackshackhome-48”
  content/hackshackhome/hackshackhome-48.md
Labels: netlify-cms/pending_publish

#2871 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#2870 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#2875 Update Hackshack Home Cards “hackshackhome-46”
  content/hackshackhome/hackshackhome-46.md
Labels: netlify-cms/pending_publish

#2876 Update Events “from-log-files-to-ai-insights-the-60-year-evolution-of-observability-and-aiops”
  content/event/from-log-files-to-ai-insights-the-60-year-evolution-of-observability-and-aiops.md
Labels: netlify-cms/pending_publish

#2848 Create Hackshack Home Cards “hackshackhome-47”
  content/hackshackhome/hackshackhome-47.md
Labels: netlify-cms/pending_publish

#2880 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2882 Update Campaign “get-real-with-ai-–-jam-series”
  content/campaign/get-real-with-ai-–-jam-series.md
Labels: netlify-cms/draft

#2883 Update GreenLake “aruba-central/home”
  content/greenlake/aruba-central/home.md
Labels: netlify-cms/draft

#2884 Update Events “it-new-year-resolution-building-an-ethical-and-trustworthy-ai-system”
  content/event/it-new-year-resolution-building-an-ethical-and-trustworthy-ai-system.md
Labels: netlify-cms/pending_publish

#2885 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2887 Update Events “it-new-year-resolution-building-an-ethical-and-trustworthy-ai-system”
  content/event/it-new-year-resolution-building-an-ethical-and-trustworthy-ai-system.md
Labels: netlify-cms/pending_publish

#2888 Create Campaign “get-real-with-ai-jam-series”
  content/campaign/get-real-with-ai-jam-series.md
Labels: netlify-cms/draft

#2889 Update Skillup “skillup-2”
  content/skillup/skillup-2.md
Labels: netlify-cms/draft

#2890 Update Blog “keeping-it-real-with-a-new-ai-jam-series”
  content/blog/keeping-it-real-with-a-new-ai-jam-series.md
Labels: netlify-cms/draft

#2891 Update Hackshack Home Cards “hackshackhome-45”
  content/hackshackhome/hackshackhome-45.md
Labels: netlify-cms/pending_publish

#2892 Update Events “unleashing-ai-innovation-a-deep-dive-into-the-hpe-private-cloud-ai-software-stack”
  content/event/unleashing-ai-innovation-a-deep-dive-into-the-hpe-private-cloud-ai-software-stack.md
Labels: netlify-cms/pending_publish

#2893 Update Hackshack Home Cards “hackshackhome-48”
  content/hackshackhome/hackshackhome-48.md
Labels: netlify-cms/pending_publish

#2894 Update Hackshack Home Cards “hackshackhome-47”
  content/hackshackhome/hackshackhome-47.md
Labels: netlify-cms/pending_publish

#2896 Update Blog “dragonhpc-featured-at-sc24”
  content/blog/dragonhpc-featured-at-sc24.md
Labels: netlify-cms/pending_publish

#2895 Update Blog “3-ways-a-data-fabric-enables-a-data-first-approach”
  content/blog/3-ways-a-data-fabric-enables-a-data-first-approach.md
Labels: netlify-cms/pending_publish

#2897 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2898 Update Campaign “get-real-with-ai-jam-series”
  content/campaign/get-real-with-ai-jam-series.md
Labels: netlify-cms/draft
