Repository hpe-dev-incubator/hpe-dev-portal, pull requests merged in 2025-03, with the labels that each got.

#2952 Update Blog “optimizing-data-processing-with-apache-spark-best-practices-and-strategies”
  content/blog/optimizing-data-processing-with-apache-spark-best-practices-and-strategies.md
Labels: netlify-cms/pending_review

#2957 Update Blog “deploying-a-hugging-face-llm-in-hpe-private-cloud-ai”
  content/blog/deploying-a-hugging-face-llm-in-hpe-private-cloud-ai.md
Labels: netlify-cms/draft

#2961 Update Blog “sivabala-opsql-opsramps-kalpavriksha-wish-fulfilling-tree”
  content/blog/sivabala-opsql-opsramps-kalpavriksha-wish-fulfilling-tree.md
Labels: netlify-cms/pending_publish

#2963 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/draft

#2962 Update Blog “sivabala-opsql-opsramps-kalpavriksha-wish-fulfilling-tree”
  content/blog/sivabala-opsql-opsramps-kalpavriksha-wish-fulfilling-tree.md
Labels: netlify-cms/pending_publish

#2968 Update Blog “sivabala-opsql-opsramps-kalpavriksha-wish-fulfilling-tree”
  content/blog/sivabala-opsql-opsramps-kalpavriksha-wish-fulfilling-tree.md
Labels: netlify-cms/pending_review

#2972 Update Skillup “EzmeralLearnOnDemand”
  content/skillup/EzmeralLearnOnDemand.md
Labels: netlify-cms/pending_review

#2975 Update Blog “hpe-oneview-python-sdk-v450-has-been-released”
  content/blog/hpe-oneview-python-sdk-v450-has-been-released.md
Labels: netlify-cms/pending_publish

#2974 Update Blog “hpe-oneview-ansible-modules-v500-has-been-released”
  content/blog/hpe-oneview-ansible-modules-v500-has-been-released.md
Labels: netlify-cms/pending_publish

#2973 Update Blog “hpe-oneview-ruby-sdk-now-available-with-support-for-hpe-oneview-40”
  content/blog/hpe-oneview-ruby-sdk-now-available-with-support-for-hpe-oneview-40.md
Labels: netlify-cms/pending_publish

#2978 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_publish

#2977 Update Events “chathpe-hub-enabling-secure-and-scalable-ai-transformation-at-hpe”
  content/event/chathpe-hub-enabling-secure-and-scalable-ai-transformation-at-hpe.md
Labels: netlify-cms/pending_publish

#2980 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_review

#2970 Create Blog “no-code-integration-of-hpe-greenlake-cloud-with-servicenow”
  content/blog/no-code-integration-of-hpe-greenlake-cloud-with-servicenow.md
  static/img/webhook-blog-servicenow-picture-2.jpg
  static/img/webhook-blog-servicenow-picture-3.jpg
  static/img/webhook-blog-servicenow-picture-4.jpeg
  static/img/webhook-blog-servicenow-picture-5.jpg
  static/img/webhook-blog-servicenow-picture-6.jpg
  static/img/webhook-blog-servicenow-picture-7.jpg
  static/img/webhook-blog-servicenow-picture-8.jpg
  static/img/webhook-blog-servicenow-picture-9.jpg
Labels: netlify-cms/pending_review

#2979 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/pending_review

#2984 Update Campaign “munch-and-learn”
  content/campaign/munch-and-learn.md
Labels: netlify-cms/draft

#2985 Update Events “chathpe-hub-enabling-secure-and-scalable-ai-transformation-at-hpe”
  content/event/chathpe-hub-enabling-secure-and-scalable-ai-transformation-at-hpe.md
Labels: netlify-cms/pending_publish

#2986 Create Blog “the-rise-commoditization-and-integration-of-virtualization-into-the-private-cloud”
  content/blog/the-rise-commoditization-and-integration-of-virtualization-into-the-private-cloud.md
  static/img/adly-picture-2-192.jpg
  static/img/hand-drawn-k8s-larger-2.png
  static/img/virtualization-privatecloud-image1.png
  static/img/virtualization-privatecloud-image2.png
  static/img/virtualization-privatecloud-image4.png
Labels: netlify-cms/pending_review

#2988 Update Hackshack Home Cards “hackshackhome-50”
  content/hackshackhome/hackshackhome-50.md
Labels: netlify-cms/pending_publish

#2989 Update Events “no-more-blind-spots-how-ebpf-transforms-observability”
  content/event/no-more-blind-spots-how-ebpf-transforms-observability.md
Labels: netlify-cms/pending_publish

#2990 Update Campaign “meetups”
  content/campaign/meetups.md
Labels: netlify-cms/pending_publish

#2992 Create Events “dayn-a-new-way-to-look-at-observability”
  content/event/dayn-a-new-way-to-look-at-observability.md
Labels: netlify-cms/pending_publish

#2991 Create Hackshack Home Cards “hackshackhome-51”
  content/hackshackhome/hackshackhome-51.md
Labels: netlify-cms/pending_publish
